### ISSUE TITLE
Formatter styles are applied to the <g> tag and not inherited

### ISSUE THREAD

**Issue by umesh-timalsina** [annotorious/annotorious#112]
Thanks for this Plugin. I read through the documentation and tried to implement a custom style for the annotated rectangle. It looks like the style (returned as an object) or class (as a string) is applied to the parent svg `<g>` tag. But, its not actually inherited. I have attached the screen shots below. Is this a bug? What's the correct way to apply formatter styles?

![image](https://user-images.githubusercontent.com/11476842/117103088-49584a80-ad3f-11eb-9deb-0d9768db4240.png)
![image](https://user-images.githubusercontent.com/11476842/117103168-7278db00-ad3f-11eb-9697-77d606bf849d.png)

**Comment by vivekgoyal-2** [comment]
please provide a syntax to set style for rectangle annotation

**Comment by vivekgoyal-2** [comment]
> @rsimon Thanks for the solution. I can attest to it being a good workaround

> Thanks for this Plugin. I read through the documentation and tried to implement a custom style for the annotated rectangle. It looks like the style (returned as an object) or class (as a string) is applied to the parent svg `<g>` tag. But, its not actually inherited. I have attached the screen shots below. Is this a bug? What's the correct way to apply formatter styles?
> 
> ![image](https://user-images.githubusercontent.com/11476842/117103088-49584a80-ad3f-11eb-9deb-0d9768db4240.png) ![image](https://user-images.githubusercontent.com/11476842/117103168-7278db00-ad3f-11eb-9697-77d606bf849d.png)

please provide syntax to this solution,i want to set stroke-width and color to both rectangle and polygon

**Comment by rsimon** [comment]
See docs here:
https://recogito.github.io/annotorious/api-docs/annotorious/#formatters

Styles are the normal CSS properties you can apply to any SVG element (stroke width, color, etc.)

**Comment by vivekgoyal-2** [comment]
> See docs here: https://recogito.github.io/annotorious/api-docs/annotorious/#formatters
> 
> Styles are the normal CSS properties you can apply to any SVG element (stroke width, color, etc.)

sorry,but i am enable to understand how and where to use formatters to style my annotations,,,here is my code where i set some previous annotation and also draw new annotation

`import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { ImageAnnotation } from '../Model/ImageAnnotation';
import { v4 as uuidv } from 'uuid'
import { UploadService } from '../upload.service';
declare var OpenSeadragon: any;
declare var Annotorious: any;
declare var toastr: any;
declare var $: any;
import { Subject } from 'rxjs';
import { ChangeDetectorRef } from '@angular/core'

@Component({
  selector: 'app-annotorious',
  templateUrl: './annotorious.component.html',
  styleUrls: ['./annotorious.component.css']
})
export class AnnotoriousComponent implements OnInit {
  constructor(private uploadservice: UploadService, private ref: ChangeDetectorRef) {
    this.uploadservice.getAllObjectList().subscribe(obj => {
      if (obj) {
        this.AllObjectList = obj;
      }
    });
  }
 

  Updatesubject:any = new Subject<any>();
  objectClickSubject: any = new Subject<any>();

  //Input variables from parent component
  @Input() imagepath: any;

  //Global variables for this component
  @Output() nextImageClick: EventEmitter<any> = new EventEmitter<any>();
  @Output() previousImageClick: EventEmitter<any> = new EventEmitter<any>();
  selectedAttributeOfObject:any = [];
  imageAnnotations:any;
  selectedAnnotation: any = {};
  annotoriousInstance: any;
  viewer: any;
  imageName: string = "";
  AllObjectList: any=[];
  isAnnotationSelected: boolean = false;
  isObjectSelected: boolean = false;
  objectChoosen: string = "";
  SelectedDatasetObjectsNames: any=[];
  attributeListOfSelectedObject: any = [];
  ListAttr: any;
  nodeIcon: string = "";
 // structures for polygon and rectangle
  polygon = 
    {
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "id": "",
    "type": "Annotation",
    "body": [{
      "type": "TextualBody",
      "purpose": "tagging",
      "value": ""
    }],
    "target": {
      "selector": [{
        "type": "SvgSelector",
        "value": ""
      }]
    }
    }  ;
  rectangle = {
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "id": "",
    "type": "Annotation",
    "stylesheet": {
      "type": "CssStylesheet",
      "value": ".a9s-annotation.long {stroke-width: 10;stroke: red;}"
    },
    "body": [{
      "type": "TextualBody",
      "purpose": "tagging",
      "value": "firstTag"
    }],
    "target": {
      "selector": {
        "type": "FragmentSelector",
        "conformsTo": "http://www.w3.org/TR/media-frags/",
        "value": ""
      },
    }
  }

  
  ngOnChanges() {

  }

  ngOnInit() {
    this.Updatesubject.subscribe((data) => {
      if (data) {
        this.saveImageAnnotations();
      }
    });
    this.objectClickSubject.subscribe((annotation) => {
      this.isAnnotationSelected = true;
        if (annotation) {
          let index = this.imageAnnotations.Annotation.findIndex(m => m.Id == annotation.id);
          if (index > -1) {
            this.objectChoosen = this.imageAnnotations.Annotation[index].ObjectName;
            this.isObjectSelected = true;
            this.setAttributeListOfSelectedObject(this.objectChoosen);

            if (this.imageAnnotations.Annotation[index].Attributes) {
              for (const key in this.imageAnnotations.Annotation[index].Attributes) {
                let attributeIndex = this.attributeListOfSelectedObject.findIndex(m => m.AttributeName == key)
                if (attributeIndex > -1) {
                  this.attributeListOfSelectedObject[attributeIndex].value = this.imageAnnotations.Annotation[index].Attributes[key];
                }
              }
            }
          }
      }
      this.ref.detectChanges();
    });
  }
  ngAfterViewInit(): void {
    $(window).on('keyup', undefined);
    $(window).on('keyup', (e) => {

      var code = (e.keyCode ? e.keyCode : e.which);
      if (code == 39) {
        this.nextImage();
      } else if (code == 37) {
        this.previousImage();
      }
    });
  }
  
  public setSelectedDatasetObjectList(objectNameList) {
    if (objectNameList) {
      this.SelectedDatasetObjectsNames = objectNameList;
    }
  }
  setAttributeListOfSelectedObject(objectName: string) {
    this.attributeListOfSelectedObject = [];
    if (this.AllObjectList) {
      var SelectedObject = this.AllObjectList.find(objlist => objlist.ObjectName == objectName);
      if (SelectedObject) {
        if (SelectedObject.Attributes) {
          SelectedObject.Attributes.forEach(attribute => {
            if (attribute.TypeValues == null)
              attribute.TypeValues = [];
            this.attributeListOfSelectedObject.push(attribute);
          })
        }
      }
    }
  }
  public InitializeInstanceOfAnnotoriousClass(imagepath, image, nodeicon) {
    this.nodeIcon = nodeicon;
    this.objectChoosen = "";
    this.selectedAnnotation = {};
    this.imageAnnotations = image;
    if (this.viewer) {
      this.viewer.destroy();
    }

    this.viewer = OpenSeadragon({
      id: "seadragon-viewer",
      tileSources: {
        type: "image",
        url: imagepath
      }
    });
    
    const config = { disableEditor: true, allowEmpty: true, formatter: Annotorious.ShapeLabelsFormatter()};
    this.annotoriousInstance = OpenSeadragon.Annotorious(this.viewer, config);
    Annotorious.Toolbar(this.annotoriousInstance, document.getElementById('seadragon-viewer'));
    this.onCreateAnnotation();
    this.onclickAnnotation();
    this.onDeleteAnnotation();
    this.onUpdateAnnotation();
    if (image.Annotation) {
      this.setAnnotations(image.Annotation);
    }
  }
    formatter = function (annotation) {

  var contributors = [];

  annotation.bodies.forEach(function (body) {
    if (body.creator)
      contributors.push(body.creator.id);
  });

  if (contributors.length > 1) {
    return {
      'data-users': contributors.join(', '),
      'style': 'stroke-width:10; stroke: red'
    }
  }
}
   
  startDrawing(shape: string) {
    this.annotoriousInstance.setDrawingTool(shape);
    this.annotoriousInstance.setDrawingEnabled(true);
  }

  setAnnotations(annotations: any) {
    if (annotations) {
      let Annotations = [];
      annotations.forEach(annotation => {
        if (annotation.Shape == "Polygon") {
          let polygonJsonString = JSON.stringify(this.polygon);
          let polygon = JSON.parse(polygonJsonString);
          polygon.target.selector[0].value = this.convertI2vCordinatesToPolygonCordinates(annotation.Coordinates);
          polygon.id = annotation.Id;
          polygon.body[0].value = annotation.ObjectName;
          Annotations.push(polygon);
        }
        else if (annotation.Shape == "Rectangle") {
          let rectangleJsonString = JSON.stringify(this.rectangle);
          let rectangle = JSON.parse(rectangleJsonString);
          rectangle.target.selector.value = this.convertI2vCordinatesToRectangleCordinates(annotation.Coordinates);
          rectangle.id = annotation.Id;
          rectangle.body[0].value = annotation.ObjectName;
          Annotations.push(rectangle);
        }
      });
      this.annotoriousInstance.setAnnotations(Annotations);
      this.formatter(Annotations[0]);
    }
  }

  // Attach handlers to listen to events

  onCreateAnnotation() {
    //this.annotoriousInstance.on('createAnnotation', function (a: any) {
    //  let data = a;
    //  // Do something
    //});
    // the 'createAnnotation' eventhandler fires only when disableEditor sets true ,so we use 'createSelection' eventhandler to get co-ordinates of drawing
    this.annotoriousInstance.on('createSelection', (function (selection) {
      this.isAnnotationSelected = true;
      this.selectedAnnotation = selection;
    }).bind(this));
    
  }

  onclickAnnotation() {
    this.annotoriousInstance.on('clickAnnotation', (function (annotation) {
      this.selectedAnnotation = annotation;
      this.isAnnotationSelected = true;
      this.objectClickSubject.next(annotation);
    }).bind(this));
}

  onDeleteAnnotation() {
    this.annotoriousInstance.on('deleteAnnotation', function (annotation) {
      let annotationToDelete = annotation;
    });
  }
  onUpdateAnnotation() {
    this.annotoriousInstance.on('updateAnnotation', (function (annotation, previous) {
      this.selectedAnnotation = annotation;
      this.Updatesubject.next("data");
    }).bind(this));
  }

  //otherMethods
  onSelectObject() {
    this.isObjectSelected = true;
    this.setAttributeListOfSelectedObject(this.objectChoosen);
  }
  convertRectangleCordinatesToI2vCordinates(cordinatesString: string) {
    let splitstring = cordinatesString.split(":");
    let stringArray = splitstring[1].split(",");
    let cordinate = [];
    stringArray.forEach(cordinte => {
      cordinate.push(parseInt(cordinte));
    });
    let x1 = cordinate[0];
    let y1 = cordinate[1];
    let width = cordinate[2];
    let height = cordinate[3];
    let x2 = width + x1;
    let y2 = height + y1;
    let rectanglePoits = [[x1, y1], [x2, y2]];
    let coordinates = [];
    let cordinatesSaveInDatabase = [rectanglePoits[0], [rectanglePoits[1][0], rectanglePoits[0][1]], rectanglePoits[1], [rectanglePoits[0][0], rectanglePoits[1][1]]];
    cordinatesSaveInDatabase.forEach((coordinate) => {
      coordinates.push("" + coordinate[0]);
      coordinates.push("" + coordinate[1]);
    })
    return coordinates;
  }
  convertI2vCordinatesToRectangleCordinates(cordinates) {
    var coordinates: number[][] = [];
    cordinates.forEach((value, index) => {
      if (index % 2 == 0) {
        var x = parseInt(value);
        var y = parseInt(cordinates[index + 1]);
        if (x < 0) {
          x = 0;
        }
        if (y < 0) {
          y = 0;
        }
        coordinates.push([x, y]);
      }
    });
    let x1y1x2y2Cordinates = [coordinates[0], coordinates[2]];
    let x1 = x1y1x2y2Cordinates[0][0];
    let y1 = x1y1x2y2Cordinates[0][1];
    let width = x1y1x2y2Cordinates[1][0] - x1y1x2y2Cordinates[0][0];
    let height = x1y1x2y2Cordinates[1][1] - x1y1x2y2Cordinates[0][1];
    let RequiredString = `xywh = pixel: ${x1}, ${y1}, ${width}, ${height}`;
    return RequiredString
  }
  convertI2vCordinatesToPolygonCordinates(cordinates: string[]) {
    var cordinatestring = "";
    
    for (let index = 0; index < cordinates.length; index = index + 2)
    {
      cordinatestring = cordinatestring + cordinates[index] + "," + cordinates[index + 1] + " ";
    }
    let requiredstring = `<svg><polygon points='${cordinatestring}'></polygon></svg > `
    return requiredstring;
  }
  convertPolygonCordinatesToI2vCordinates(cordinatestring: string) {
    let cordinatesString = [];
    var SubString = cordinatestring.substring(
      cordinatestring.indexOf("\"") + 1,
      cordinatestring.lastIndexOf("\"")
    );
    let splitThird = SubString.split(" ");
    splitThird.forEach((splitdata) => {
      let splitcordi = splitdata.split(",");
      cordinatesString.push(splitcordi[0]);
      cordinatesString.push(splitcordi[1]);
    });
    return cordinatesString;
  }
  ClearAllAnnotation() {
    this.annotoriousInstance.clearAnnotations();
  }
  DeleteSelectedObject() {
    this.annotoriousInstance.removeAnnotation(this.selectedAnnotation.id);
    if (this.imageAnnotations.Annotation) {
    let index =  this.imageAnnotations.Annotation.findIndex(m => m.Id == this.selectedAnnotation.id);
      if (index > -1) {
        this.imageAnnotations.Annotation.splice(index, 1);
        this.imageAnnotations._Annotation = null;
        this.uploadservice.saveImageAnnotation(this.imageAnnotations).subscribe(data => {
          this.objectChoosen = "";
          this.selectedAnnotation = {};
          toastr.success("object deleted");
        });
      }
    }
  }

  AddORModifyAnnotations() {
    if (this.objectChoosen != "") {
      let annotation = this.selectedAnnotation;
      if (annotation) {
        var i2vAnnotationFormat: ImageAnnotation;
        const attributeObject = new Object();
        i2vAnnotationFormat = new ImageAnnotation();
        if (annotation.id) {
          i2vAnnotationFormat.Id = annotation.id;
        }
        else {
          i2vAnnotationFormat.Id = uuidv();
          this.selectedAnnotation.id = i2vAnnotationFormat.Id;
        }
        let valueWithSelectorIndexZero = annotation.target.selector[0];
        let valueWithSelectorIndex = annotation.target.selector;
        let shape = "Polygon";
        if (valueWithSelectorIndexZero != undefined) {
          if (annotation.target.selector[0].value.includes("polygon")) {
            shape = "Polygon";
            i2vAnnotationFormat.Shape = "Polygon";
            i2vAnnotationFormat.Coordinates = this.convertPolygonCordinatesToI2vCordinates(annotation.target.selector[0].value);

          }
        }
        else if (valueWithSelectorIndex != undefined) {
          if (annotation.target.selector.value.includes("xywh")) {
            shape = "Rectangle";
            i2vAnnotationFormat.Shape = "Rectangle";
            i2vAnnotationFormat.Coordinates = this.convertRectangleCordinatesToI2vCordinates(annotation.target.selector.value);
          }
          else if (annotation.target.selector.value.includes("polygon")) {
            shape = "Polygon";
            i2vAnnotationFormat.Shape = "Polygon";
            i2vAnnotationFormat.Coordinates = this.convertPolygonCordinatesToI2vCordinates(annotation.target.selector.value);

          }
        }
 

        i2vAnnotationFormat.ObjectName = this.objectChoosen;
        if (this.attributeListOfSelectedObject.length > 0) {
          this.attributeListOfSelectedObject.forEach(attribute => {
            attributeObject[attribute.AttributeName] = attribute.Value;
          });
        }

        i2vAnnotationFormat.Attributes = attributeObject;
        if (this.imageAnnotations.Annotation == null) {
          this.imageAnnotations.Annotation = [];
        }
        let index = this.imageAnnotations.Annotation.findIndex(m => m.Id == i2vAnnotationFormat.Id);
        if (index > -1) {
          this.imageAnnotations.Annotation[index] = i2vAnnotationFormat;
        }
        else {
          this.imageAnnotations.Annotation.push(i2vAnnotationFormat);
        }
      }
    }
    else {
      toastr.error("please chose object");
    }
  }
  saveImageAnnotations() {
    if (this.selectedAnnotation
      && Object.keys(this.selectedAnnotation).length != 0) {
      if (this.objectChoosen != "") {
        let annotation = this.selectedAnnotation;
        if (annotation) {
          var i2vAnnotationFormat: ImageAnnotation;
          const attributeObject = new Object();
          i2vAnnotationFormat = new ImageAnnotation();
          if (annotation.id) {
            i2vAnnotationFormat.Id = annotation.id;
          }
          else {
            i2vAnnotationFormat.Id = uuidv();
            this.selectedAnnotation.id = i2vAnnotationFormat.Id;
          }
          let valueWithSelectorIndexZero = annotation.target.selector[0];
          let valueWithSelectorIndex = annotation.target.selector;
          let shape = "Polygon";
          if (valueWithSelectorIndexZero != undefined) {
            if (annotation.target.selector[0].value.includes("polygon")) {
              shape = "Polygon";
              i2vAnnotationFormat.Shape = "Polygon";
              i2vAnnotationFormat.Coordinates = this.convertPolygonCordinatesToI2vCordinates(annotation.target.selector[0].value);

            }
          }
          else if (valueWithSelectorIndex != undefined) {
            if (annotation.target.selector.value.includes("xywh")) {
              shape = "Rectangle";
              i2vAnnotationFormat.Shape = "Rectangle";
              i2vAnnotationFormat.Coordinates = this.convertRectangleCordinatesToI2vCordinates(annotation.target.selector.value);
            }
            else if (annotation.target.selector.value.includes("polygon")) {
              shape = "Polygon";
              i2vAnnotationFormat.Shape = "Polygon";
              i2vAnnotationFormat.Coordinates = this.convertPolygonCordinatesToI2vCordinates(annotation.target.selector.value);

            }
          }


          i2vAnnotationFormat.ObjectName = this.objectChoosen;
          if (this.attributeListOfSelectedObject.length > 0) {
            this.attributeListOfSelectedObject.forEach(attribute => {
              attributeObject[attribute.AttributeName] = attribute.Value;
            });
          }

          i2vAnnotationFormat.Attributes = attributeObject;
          if (this.imageAnnotations.Annotation == null) {
            this.imageAnnotations.Annotation = [];
          }
          let index = this.imageAnnotations.Annotation.findIndex(m => m.Id == i2vAnnotationFormat.Id);
          if (index > -1) {
            this.imageAnnotations.Annotation[index] = i2vAnnotationFormat;
          }
          else {
            this.imageAnnotations.Annotation.push(i2vAnnotationFormat);
          }

          this.imageAnnotations._Annotation = null;
          this.uploadservice.saveImageAnnotation(this.imageAnnotations).subscribe(data => {
            if (this.imageAnnotations.Annotation.length > 0) {
              this.nodeIcon = "assets/check.png";
            }
            else {
              this.nodeIcon = "assets/file.png";
            }
            this.setAnnotations(this.imageAnnotations.Annotation);
            this.objectChoosen = "";
            this.selectedAnnotation = {};
            toastr.success("object saved");
          });


        }
      }
      else {
        toastr.error("please chose object");
      }
    }
  }

  

 public previousImage() {
    if (this.selectedAnnotation) {
      this.saveImageAnnotations();
   }
   this.previousImageClick.emit(this.nodeIcon);
  }
 public nextImage() {
    if (this.selectedAnnotation) {
      this.saveImageAnnotations();
    }
   this.nextImageClick.emit(this.nodeIcon);
  }
}
`

**Comment by vivekgoyal-2** [comment]
i am in trouble please help me out , i am using openseadragon to make a image annotation tool where i annotate multiple objects in a single image with rectangle and polygon shape i just want to set stroke-width and stroke color to annotation and i dont know how to set style

**Comment by vivekgoyal-2** [comment]
Sir,Thanks for your reply ,please help me I enable to to understand how to
set style in openseadragon ,I readout the formatter article but I don't
know how to do it

**Comment by rsimon** [comment]
Do you want to apply the same style to all of your shapes? If so, you can simply apply your own CSS stylesheet. See here:

https://recogito.github.io/guides/customizing-styles/

If you want to change the style depending on what's contained in the annotation, then things would be more complicated. You will need to follow the guide on implementing your own formatter function (see link above). __However:__ I can see you are already using the formatter from the ShapeLabels plugin. Applying multiple formatters isn't supported yet (see https://github.com/recogito/annotorious/issues/159) but will come in a future release.

**Comment by rsimon** [comment]
Ok sounds like you really only need to apply your own CSS stylesheet according to https://recogito.github.io/guides/customizing-styles/

I'm not and Angular programmer I'm afraid. But adding your own stylesheet should be easy enough and well documented.

**Comment by vivekgoyal-2** [comment]
Ok, thanks. I am trying
