### ISSUE TITLE
anno.cancelSelected() does not cancel uncompleted annotation

### ISSUE THREAD

**Issue by derekbekoe** [annotorious/annotorious#114]
`anno.cancelSelected()` works if the shape is complete but if the drawing is not complete, calling `anno.cancelSelected()` does not cancel the annotation.

For example, with the polygon tool, if `anno.cancelSelected()` is called before the double click to close the shape, the annotation is not cancelled.

For the rect tool, if `anno.cancelSelected()` is called after onmousedown and before onmouseup (i.e. the user is still holding the mouse down), the annotation is not cancelled.

**Comment by rsimon** [comment]
Yes, good point. `.cancelSelected` only covers the state where the selection has already been completed. But I agree it should work while drawing is still in progress, too. Putting it on the list for one of the next releases.
