### ISSUE TITLE
Annotorious getSelected throws error after delete

### ISSUE THREAD

**Issue by alaksandarjesus** [annotorious/annotorious#118]
The below code is implemeneted on Angular 11. 

On fresh load, only one annotation is created. I get an error. When i try to initiate a delete annotation using click event

```
 onDelete(event:Event){
    event.preventDefault();
    event.stopPropagation();
    setTimeout(()=>{
      console.clear();
      const selected = this.annotorius.getSelected();
      console.log(selected);
      setTimeout(()=>{
        const annotations = this.annotorius.getAnnotations();
        const annotationIndex = findIndex(annotations, (item: any) => isEqual(item.id, annotations[0].id));
        console.log(annotationIndex);
        this.annotorius.removeAnnotation(annotations[annotationIndex]);
      })
    
    })
  }
```
![image](https://user-images.githubusercontent.com/4712552/118668448-811cc300-b812-11eb-9cd9-674d68567c7c.png)

If i comment of this.annotorius.getSelected()

```
 onDelete(event:Event){
    event.preventDefault();
    event.stopPropagation();
    setTimeout(()=>{
      console.clear();
    //  const selected = this.annotorius.getSelected();
    //  console.log(selected);
      setTimeout(()=>{
        const annotations = this.annotorius.getAnnotations();
        const annotationIndex = findIndex(annotations, (item: any) => isEqual(item.id, annotations[0].id));
        console.log(annotationIndex);
        this.annotorius.removeAnnotation(annotations[annotationIndex]);
      })
    
    })
  }
```

The first annotation is deleted successfully

**Comment by rsimon** [comment]
Thanks for reporting. I think I figured out where the problem lies. `.getAnnotations()` doesn't currently return the selected annotation. Expect a fix soon!

**Comment by rsimon** [comment]
P.S.: on second thought: both versions of the code should work if you call the `onDelete` handler while no annotation is selected. Can you confirm that this is the case?

**Comment by kaanersoy** [comment]
@rsimon `.selectAnnotation(<annotation-id>)` is bringing same error like this issue :sob: 

(It works but it is bringing error in `try catch` block)

```
TypeError: Cannot read property 'clone' of undefined
    at annotorious.min.js:2
    at Array.map (<anonymous>)
    at u.<anonymous> (annotorious.min.js:2)
    at e.<anonymous> (annotorious.min.js:2)
```

**Comment by rsimon** [comment]
Hi @kaanersoy, weird... I confirmed that `.selectAnnotation` works properly in principle, both when calling with an ID string, or an annotation object. Are you doing anything additional that might cause the issue? Which version of Annotorious are you using?

**Comment by kaanersoy** [comment]
Hi again @rsimon :wave: ,

I am using:
```
"dependencies": {
    "@recogito/annotorious": "^2.3.3",
    "vue": "^2.5.17",
    ...
```

and there is my code:
```vue
<button @click="selectSelection(id)" >Select</button> 
```
```js
// ...
function selectSelection(id) {
  this.annoInstance.selectAnnotation(id)
}
```

**Comment by rsimon** [comment]
Where's `id` coming from? Can you verify it's a valid string Id?

**Comment by kaanersoy** [comment]
@rsimon Yeah it is a valid `id` and it works great, but it is throwing error when event triggered in `try catch` block.

**Comment by rsimon** [comment]
Sorry I can't reproduce the problem. Can you provide a full code sample?

**Comment by kaanersoy** [comment]
It is a Vue.js code and imagine it like if button clicked trigger the `selectSelection` function with true and valid id of selection.

```vue
<div v-for="selection in selections">
   /* think like it is a true selection.id */
  <button @click="selectSelection(selection.id)" >Select</button>
</div>
```

```js
function selectSelection(id) {
  try{
    this.annoInstance.selectAnnotation(id)
  } catch(err) {
    console.log(err)
  }
}
```
It is working and it selecting the right one. But it is console.log error too. and error is:
```
TypeError: Cannot read property 'clone' of undefined
    at annotorious.min.js:2
    at Array.map (<anonymous>)
    at u.<anonymous> (annotorious.min.js:2)
    at e.<anonymous> (annotorious.min.js:2)
```

**Comment by rsimon** [comment]
Weird. Can you add a `console.log(id)` at the start of `selectSelection`, so the log shows how often the method is called, and what the value of `id` is in each case?

**Comment by kaanersoy** [comment]
It logs id: `#c3a8f65c-e2b7-4ef5-977e-57c6d2046ffb`

and this error: 
```
TypeError: e is undefined
    u annotorious.min.js:2
    u annotorious.min.js:2
    e annotorious.min.js:2
```
(screenshot)
![image](https://user-images.githubusercontent.com/57914492/119220047-283e7a80-baf1-11eb-8579-4be4a1c0f7c6.png)

**Comment by rsimon** [comment]
@kaanersoy sorry, I simply cannot reproduce this with the latest version. I tried calling `.selectAnnotation` when there's no current selection, when there is already a different annotation selected, and when the same annotation is already selected. Always works properly, without causing errors (tested in Chrome and FF).

Can you retry with the latest version (2.4.0)? If the problem persists, can you please post a full working example online that shows the error? Also: please open another issue, because this issue is actually about an entirely different bug.

**Comment by rsimon** [comment]
@alaksandarjesus I think your original problem is actually not with `.getSelected`, but with `.getAnnotations` throwing an error when there is currently an active selection. I'm looking into this.
