### ISSUE TITLE
updateAnnotation event does nothing

### ISSUE THREAD

**Issue by kaanersoy** [annotorious/annotorious#119]
I am using annotorious in `Vue.js 2`, there is a problem with `updateAnnotation` event.
It is doing nothing is there any reason for that?

I just want to start callback function -> `getSelections()` when update fires up.

(i am carried instance to data object on `Vue.js Options API` for use it everywhere.)

```js
export default {
  data() {
    return {
      annoInstance: {}
   },
   mounted() {
     this.annoInstance = new Annotorious({
        image: 'image-labelling-image',
        widgets: [{ widget: 'TAG', vocabulary: ['something'] }]
     })
     this.annoInstance.on('updateAnnotation', () => this.getSelections())
   },
   methods: {
     getSelections() {
       try {
         const annotations = this.annoInstance.getAnnotations()
         this.selections = annotations
       } catch (err) {
         console.log(err)
       }
   },
}
```

**Comment by rsimon** [comment]
Hi,

I just confirmed that the `updateAnnotation` event is properly working. E.g.:

```js
anno.on('updateAnnotation', function(annotation, previous) {
  console.log('updated', previous, 'with', annotation);
});
```

Can you confirm that it's really the handler function that's not called in your example? Or something about `getSelections()`?

**Comment by rsimon** [comment]
P.S.: which version of Annotorious are you using?

**Comment by kaanersoy** [comment]
I am using:
```
"dependencies": {
    "@recogito/annotorious": "^2.3.3",
    ...
```

Sorry maybe it is my bad :/ I am trying..

(EDIT)

It is my bad it working with your way like:

```js
this.annoInstance.on('updateAnnotation', function(annotation, previous) {
  console.log('updated', previous, 'with', annotation);
});
```
and 

```js
this.annoInstance.on('updateAnnotation', () => this.getSelections())
```

**Comment by rsimon** [comment]
Yes good point. I think `this` and arrow functions generally don't play week together.
