### ISSUE TITLE
.getAnnotations() raises TypeError: Cannot read property 'clone' of undefined

### ISSUE THREAD

**Issue by linfordbacon-ngenius** [annotorious/annotorious#120]
running `anno.getAnnotations()` while an annotation is currently selected throws:
```
annotorious.min.js:2 Uncaught TypeError: Cannot read property 'clone' of undefined
```

**Steps to reproduce**

```
anno = Annotorious.init({
    image: 'cameraViewport', // image element or ID
    //headless: true
});

anno.setDrawingTool('polygon');
```

Use the GUI to save the annotation and then select it with the cursor

then run `anno.getAnnotations()` in the console and cry...

**Comment by rsimon** [comment]
Weird... are you using the latest version (v2.4.0)?

**Comment by rsimon** [comment]
Sorry, I just checked and this was indeed fixed just __after__ the last release. That means you could build yourself from source of you need the fix now, or wait for the next release which will include the fix.

**Comment by linfordbacon-ngenius** [comment]
thanks, @rsimon - I've got a workaround that works for now but good to know this will be fixed soon.
