### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by alexzorin** [annotorious/annotorious#121]
Hi,

Just as the person in #10, I am very grateful for this library. It works great!

I noticed that since [your comment here](https://github.com/recogito/annotorious/issues/10#issuecomment-620193504), the bundle size has grown back to a bit under 400KB.

I tried to do a bisect between ec481c104da74a05aca2f24de5c5126379ee818f (small) and d2e329db0463d16763d0888ca1d5b34081de3230 (big), it seems that the size has crept up slowly over time, rather than there being one big jump. Though there were a couple of major culprits, like the addition of `@babel/polyfill`.

Some suggestions and hints for anybody else who is interested in reducing the bundle size:

- Make the IE11 polyfill optional. For me, using this in a Vue 3 project, it's not useful. 
- Allow people to opt-in to the editor by packaging it as a separate module. Annotorious is still super useful even without the editor. 
- Try an optimizing bundler; the difference can sometimes be dramatic. On top of the above two exclusions, building using `vite` rather than `webpack` cut the bundle size from 265KB to 96KB!

For me, my project shrank from 458KB to 140KB.

**Comment by rsimon** [comment]
Thanks!

Separating the editor is actually something I've been planning. But that will first need a few architectural changes, so you shouldn't expect it anytime soon I'm afraid. But it's definitely on the list. (Also, there's one specific autocomplete lib dependency that, I think, adds almost around 70k, and which I want to get rid of.)

Re polyfills: yes, they add a lot that's true. If you have ideas how to change the code + build process, so that it could produce two versions in one go (e.g. an "annotorious.min.js" and an "annotorious.compact.min.js", or something), I'd appreciate a pull request. (If that's something I'd have to maintain manually, frankly, I'm not going to do it. Annotorious is still 95% a hobby/side project . No offence, but I wouldn't invest extra time for every release to save a couple of kB, especially since most applications that use it will most likely download several 100s of kB of images, anyway.)

Re vite: exciting! I wasn't aware of that. Thanks for pointing it out. Would you mind an example (or PR? :-) showing what a build config would look like?

**Comment by alexzorin** [comment]
Thanks for responding.

> so you shouldn't expect it anytime soon I'm afraid.

No rush! I stuck a vendored copy of Annotorious into my project with these changes and it's working great.

> No offence, but I wouldn't invest extra time for every release to save a couple of kB

Sure, I get the sentiment. That said, iirc from yesterday, `@babel/polyfill` is adding ~100KB to the bundle size, at least when using the current Webpack config.

More generally about browser polyfills, it feels to me that compatibility is a decision for the developer of the final application.

My idea here was putting something in the README like "hey, this won't work in IE11 unless you add this polyfill". Though, I get that it's not as trivial to do this after the project has been around for a long time.

> Re vite: exciting! I wasn't aware of that. Thanks for pointing it out. Would you mind an example (or PR? :-) showing what a build config would look like?

Yep, totally, maybe after this coming week. Off the top of my head, it builds just fine by:

1. Using the vite preact preset.
2. Renaming a couple of `.js` files to `.jsx` in `annotorious` and the `recognito-client-core` project. vite made a decision that they won't support JSX in `.js` files :shrug:.
3. `npm install -D sass`

```js
// vite.config.js
import { defineConfig } from 'vite'
import preact from '@preact/preset-vite'
const path = require('path')

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [preact()],
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/index.jsx'),
      name: 'annotorious'
    }
  }
})
```

I think that Webpack supports some kind of tree-shaking optimization as well, but I don't really know and  can't comment.

**Comment by rsimon** [comment]
Thanks, that's really helpful! I'll try out the vite config.

> More generally about browser polyfills, it feels to me that compatibility is a decision for the developer of the final application.

That's a good point... I'd definitely need to document to process before making the switch though. (And write up examples for how to add the polyfills, both when using a bundler, and when including via the `<script>` tag.) But either way - I agree the 100k would be worth that.

**Comment by rsimon** [comment]
Hi again,

I tried your config & it seemed to work fine - and reduced the output size by ~70k with no code changes! However I couldn't figure out how to properly expose the library. The UMD build seems to expose an empty `Annotorious` object `{}`. I assume I need to change something about the export in the `index.js` file?

P.S.: My changes are in [this new branch](https://github.com/recogito/annotorious/tree/vite-build)

**Comment by alexzorin** [comment]
Cool! Thanks for continuing to check this out. Yeah, there are a couple of things to do in the `recognito-client-core` library.

0. As before, a handful of `js`->`jsx` renames.

1. The import [here](https://github.com/recogito/recogito-client-core/blob/785036ac4354b3cb1eeb740c6170abc6d75d5327/src/i18n/index.js#L1 ) needs to be:

    ```js
    import Polyglot from 'node-polyglot';
    ```

2. The import [here](https://github.com/recogito/recogito-client-core/blob/785036ac4354b3cb1eeb740c6170abc6d75d5327/src/WebAnnotation.js#L2) needs the same change.

(There may still be a couple of identical changes elsewhere, but I did strip the dependencies for headless mode down quite a bit, so I may have ended up avoiding those crashes inadvertently.)

With those changes, the `index.html` with the `umd` bundle seems to run correctly (at least, after re-adding `style.css`). 

The `esm` bundle seems to run alright too in latest Chrome and Firefox (with some minor rewriting of `index.html`).

**Comment by rsimon** [comment]
I made the .jsx renames, that worked fine. The build looked ok (=no error messages) even without changing the `import * as ...` statements. It's just when I imported the umd build into the page via the `<script>` tag, `window.Annotation` ended up being an empty object.

But in general I think I'm still missing a few steps. Is `vite preview` supposed to launch the page in hot-reload mode? (Or just `vite`?)

**Comment by alexzorin** [comment]
> It's just when I imported the umd build into the page via the <script> tag, window.Annotation ended up being an empty object.

Yep, I found that this was caused by the  `import * ...` in `recognito-client-core`. Once I fixed those, `Annotorious` was exported properly and the demo application worked.

> Is vite preview supposed to launch the page in hot-reload mode? (Or just vite?)

I haven't tried to get HMR to work yet!

**Comment by rsimon** [comment]
Indeed, that go me one step further. The library is exported properly, and part of it works. However when I select an annotation, and the editor is supposed to pop up, I get the following error:

```js
Cannot read property '__H' of undefined
```

That's a familiar thing and happens whenever something's broken with Preact. Did you encounter this before? I am using

```js
plugins: [preact()]
```

in the vite config. But perhaps there's something else I'm missing.

**Comment by alexzorin** [comment]
I didn't hit anything like that. The editor was fully functional for me. I'll try find some time to upload forks of both projects as a demo.

**Comment by rsimon** [comment]
I got it working! 🎉 I don't know what the reason was exactly, but it must have had something to do with having `npm link`ed to my local version of `recogito-client-core`. Or maybe by linking in the wrong way somehow... Anyways: I now published an updated `recogito-client-core` version (v1.2.1) which has all the vite-compatible fixes. The build seems to work just fine, and size is down by ~75k, with no modifications.

**Comment by rsimon** [comment]
Just a quick update: I added the vite build config to the main branch. The current build sizes are:

- webpack: 374kB
- vite: 307kB
- webpack without polyfills: 283kb
- vite without polyfills: 227kB

I'll use vite for the upcoming release (v2.4.1), but with the polyfills still included. For the next point release (v2.5), I'm planning to split the polyfills out into a separate bundle. 

Thanks for all the info so far - and thanks a lot for your donation!

**Comment by alexzorin** [comment]
Very exciting! I guess if 3.0 is ever a thing one could consider the API changes to make the Editor tree-shakable as well.

Thanks for working on this.

My Annotorious app (*yet another* ML labeling UI) has been in production for about a week and works fantastically fwiw.

**Comment by dosstx** [comment]
> Very exciting! I guess if 3.0 is ever a thing one could consider the API changes to make the Editor tree-shakable as well.
> 
> Thanks for working on this.
> 
> My Annotorious app (_yet another_ ML labeling UI) has been in production for about a week and works fantastically fwiw.

would you mind showing a link to it in action? Would love to see it. Thanks!

**Comment by rsimon** [comment]
@alexzorin absolutely. 3.0 would definitely reorganize a few basic architectural things, including the split between editor and drawing. 

I'd also be interested in learning more about your ML labeling UI. (If it's something you can share publicly. Fully understood if not, of course.)

**Comment by alexzorin** [comment]
Can't share the app itself, but its aim was to make the particular cropping + re-labeling task we had, as efficient as possible. [Short video](https://user-images.githubusercontent.com/311534/122902010-731e0d00-d391-11eb-9ef7-c9ec6f30100a.mp4).

As far as Annotorious goes:

- the API and also the SVG/CSS was very easy and pleasant to work with.
- The crosshair would have been nice to have as a built-in, but it's simple enough to add separately.
-  Some kind of zoom functionality would be great. I couldn't quite figure it out without messing up the coordinates of the annotations. It might be possible and I just didn't spend enough time figuring it out. Zooming the browser works too :) .

**Comment by rsimon** [comment]
Hi @alexzorin, thanks for the update. The crosshair is nice. Maybe an option that could be packed into the new [selector pack plugin](https://github.com/recogito/annotorious-selector-pack)...

I agree on the zoom option (see also #6). I'm pretty sure some kind of "hover lens" would be feasible. But haven't thought about how to do this myself either yet.

**Comment by dosstx** [comment]
Thanks for the video, @alexzorin ! I agree about the zoom feature...I posted about it in the beginning (which rsimon linked to). It would be a cool feature! We would have to think about the UX for that because I don't know how you could zoom AND add annotations at the same time.

**Comment by rsimon** [comment]
In terms of the interaction, I think you' hit a key and then the mouse cursor goes away, and gets replaced with a circle "magnifier window" shape, perhaps with a crosshair. You'd simply move around with the magnifier, but otherwise click and drag as normal.

That should be fairly easy to do as far as magnifying the underlying image is concerned, I think. Haven't thought about whether scaling the shape might be tricky, i.e. when you are dragging a box or polygon, you'd probably have to re-draw (parts of) it on the magnified image in a clever way...

**Comment by rsimon** [comment]
For info: the next release removes legacy polyfills, and moves them into a [separate, optional bundle](https://github.com/recogito/legacy-polyfills) instead. Overall bundle size will shrink to around 250kB then.

**Comment by rsimon** [comment]
The build is officially switched to vite, and polyfills are a separate package as of [v2.5](https://github.com/recogito/annotorious/releases/tag/v2.5.0).

The last remaining issue is making the editor tree-shakeable, for which I created a separate issue here:
https://github.com/recogito/annotorious/issues/144

**Comment by Caleb1917** [comment]
Hello, 
Im trying to add annotation to my image, it is working fine. When i zoom my image and try to add annotation, at that time annoatation editor box is also getting zoomed 
How to handle this?

**Comment by rsimon** [comment]
Do you mean that the editor box is moving along with the annotation? That's the desired behavior. Or am I misunderstanding your problem?

**Comment by Caleb1917** [comment]
![No issue](https://github.com/annotorious/annotorious/assets/135332226/ce87436f-8cad-4fab-896a-7417ccdc34e8)
![Screenshot 2023-06-02 171151](https://github.com/annotorious/annotorious/assets/135332226/c9d24a47-93d2-4489-8b68-f782fa87674a)

If you see in first image, annotation editor box is working fine. Whereas when i zoom the image, it is behaving differently 
Would be great, if you help me on this

**Comment by rsimon** [comment]
Is this with the OpenSeadragon version? If not, it depends you are zooming the image. For normal responsive images, behavior looks fine (at least I cannot reproduce your problem). For zooming the whole browser scale, behavior seems to look good also. If you set up a public demo so I can reproduce the issue, I can try to take a look.

**Comment by Caleb1917** [comment]
"@recogito/annotorious": "^2.7.2" above is the version im using. We can have a image and some transform property is applied to it to increase its size. When i annotate after zooming the image, the issue is happening. Shall i share demo of the issue?

**Comment by rsimon** [comment]
Ok, I'm afraid if you scale the image with a transform, there's no way for Annotorious to automatically keep track. You may be able to achieve the same effect by putting the image in a container and then scaling that. See:
https://annotorious.github.io/getting-started/ ("A note on styled images")

But otherwise, what you want to achieve may not be possible. Alternatively you could also try the OpenSeadragon version. (The OpenSeadragon viewer can open normal images as well.)

**Comment by Caleb1917** [comment]
Im not scaling the image. Image is inside the container and im scaling the container. Now the annotorious r6o-editor is coming inside the container which is causing the issue
