### ISSUE TITLE
Custom Plugin Error: `Uncaught TypeError: Cannot read property 'split' of null`

### ISSUE THREAD

**Issue by n0mn0m** [annotorious/annotorious#127]
Hi,

Want to start out by saying thanks for the library. It's really useful. I was recently attempting to upgrade to latest and ran into #120. Based on that I cloned the repo, ran the build command and used commit 12797a58567ae866c6e8bd0c8f44f0388569e131 in my project. When doing that `getAnnotations` works, and the initial interactions work as expected, but when I click on an existing annotation I get this error:

```js
SVG.js:6 Uncaught TypeError: Cannot read property 'split' of null
    at u (SVG.js:6)
    at wu (Formatting.js:42)
    at new i (EditableRect.js:77)
    at i.createEditableShape (RubberbandRectTool.js:64)
    at n.selectShape (AnnotationLayer.js:332)
    at AnnotationLayer.js:306
    at i.emit (index.js:36)
    at ToolsRegistry.js:48
    at i.emit (index.js:36)
    at RubberbandRectTool.js:53
```

I thought maybe there was an error with my plugin, so I tested the HelloWorldPlugin at `public/examples/editor-plugin`:

```bash
npm run-script build
cd public/examples/editor-plugin
cp ../../640px-Hallstatt.jpg . 
cp ../../../dist/annotorious.min.* . 
npm i http-server
http-server
```

I then navigate to the page, add an annotation box with a color. Save, then click that annotation, the widget fails to load and the error above is shown in the console. 

This appears related to `selectShape` in `AnnotationLayer.js` line 329 and how `SVG.js` expects the parent node to have a `class`, but the parent node is a bare `<g>` element.

```html
<g>
    <rect class="a9s-outer" x="414" y="110" width="226" height="251">
    </rect>
    <rect class="a9s-inner" x="414" y="110" width="226" height="251">
    </rect>
</g>
```

Full `svg` element from the page:

```html
<svg class="a9s-annotationlayer" viewBox="0 0 640 361">
    <g>
        <g style="pointer-events: none; display: none;">
            <path fill-rule="evenodd" d="M0 0 h640 v361 h-640 z M268.0933532714844 109.86066436767578 h2 v2 h-2 z"
                  class="a9s-selection-mask"></path>
            <g class="a9s-selection">
                <rect class="a9s-outer" x="268.0933532714844" y="109.86066436767578" width="2" height="2"></rect>
                <rect class="a9s-inner" x="268.0933532714844" y="109.86066436767578" width="2" height="2"></rect>
            </g>
        </g>
        <g>
            <path fill-rule="evenodd"
                  d="M0 0 h640 v361 h-640 z M138.07476806640625 45.355316162109375 h223.75291442871094 v265.07665634155273 h-223.75291442871094 z"
                  class="a9s-selection-mask"></path>
            <g class="a9s-annotation editable selected">
                <g>
                    <rect class="a9s-outer" x="138.07476806640625" y="45.355316162109375" width="223.75291442871094"
                          height="265.07665634155273"></rect>
                    <rect class="a9s-inner" x="138.07476806640625" y="45.355316162109375" width="223.75291442871094"
                          height="265.07665634155273"></rect>
                </g>
                <g class="a9s-handle" transform-origin="138.07476806640625px 45.355316162109375px">
                    <g transform-origin="138.07476806640625px 45.355316162109375px">
                        <circle cx="138.07476806640625" cy="45.355316162109375" r="7" class="a9s-handle-outer"></circle>
                        <circle cx="138.07476806640625" cy="45.355316162109375" r="6" class="a9s-handle-inner"></circle>
                    </g>
                </g>
                <g class="a9s-handle" transform-origin="361.8276824951172px 45.355316162109375px">
                    <g transform-origin="361.8276824951172px 45.355316162109375px">
                        <circle cx="361.8276824951172" cy="45.355316162109375" r="7" class="a9s-handle-outer"></circle>
                        <circle cx="361.8276824951172" cy="45.355316162109375" r="6" class="a9s-handle-inner"></circle>
                    </g>
                </g>
                <g class="a9s-handle" transform-origin="361.8276824951172px 310.4319725036621px">
                    <g transform-origin="361.8276824951172px 310.4319725036621px">
                        <circle cx="361.8276824951172" cy="310.4319725036621" r="7" class="a9s-handle-outer"></circle>
                        <circle cx="361.8276824951172" cy="310.4319725036621" r="6" class="a9s-handle-inner"></circle>
                    </g>
                </g>
                <g class="a9s-handle" transform-origin="138.07476806640625px 310.4319725036621px">
                    <g transform-origin="138.07476806640625px 310.4319725036621px">
                        <circle cx="138.07476806640625" cy="310.4319725036621" r="7" class="a9s-handle-outer"></circle>
                        <circle cx="138.07476806640625" cy="310.4319725036621" r="6" class="a9s-handle-inner"></circle>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>
```

Looking through some of the history I thought that this may be related to mentions of a previous version as mentioned in #112.

I wanted to first check if this is expected behavior, if so how can I help update the editor-plugin example to work with the current version? If this isn't the intended behavior (`shape.parentNode.removeChild(shape);` failing on lookup when the parent element is bare/missing the `class` attribute) is there anything I can help update to fix this?

**Comment by rsimon** [comment]
Hi, sorry for this. It's, quite frankly, simply where I left off last weekend (before having to leave for my COVID vaccination ;-) The latest state in the main branch is currently broken. You analysed everything correctly. It happens when a CSS class is supposed to get added to the SVG shape, and there's no class attribute present yet.

That's one part of the issue. But, generally, I need to rethink the last changes to the formatter framework a little bit. But in any case: no changes are needed to the plugins - this will be fixed once I figured out how to proceed exactly (next weekend...) 

If you need the fix to #120 before the official release of the next version, this commit should be safe to use:
458f032f68985f9612a473c4af9f5835ca003950

**Comment by n0mn0m** [comment]
@rsimon thanks! I'll test things out with that commit. Let me know if I can help out testing updates or anything once you figure out how you want to proceed.

**Comment by n0mn0m** [comment]
@rsimon running into this on 458f032f68985f9612a473c4af9f5835ca003950

```bash
# rm annotorious.min.*  
# cd ../../../
# git checkout 458f032f68985f9612a473c4af9f5835ca003950
# git status                                                                                                                                                                                     
HEAD detached at 458f032
# rm -r dist/
# rm -rf node_modules/
# npm install
# npm run-script build
# cd public/examples/editor-plugin
# cp ../../../dist/annotorious.min.* .   
# http-server
```

![image](https://user-images.githubusercontent.com/2118138/121379098-b9935680-c911-11eb-8428-b11dfce03c47.png)

Select the annotation:

![image](https://user-images.githubusercontent.com/2118138/121379211-d0d24400-c911-11eb-9501-0ed304a326b3.png)

Anything stand out that I'm doing wrong at that checkout?

**Comment by rsimon** [comment]
I just added a fix which should solve the issue you are seeing. The formatter framework is still a bit of a work in progress (hopefully only until the end of this weekend.) But that should no longer interfere with existing plugins. At least not unless they inject additional DOM elements into the annotation like the [Shape Labels Plugin](https://github.com/recogito/recogito-client-plugins/tree/main/packages/annotorious-shape-labels) does.

**Comment by n0mn0m** [comment]
Thanks @rsimon! The hello-world plugin is looking great again 😃 . I'll test this with my custom plugin this evening (UTC -4). Thanks for the update. Really appreciate it.
