### ISSUE TITLE
After use selectAnnotation API ,The image cannot be dragged.

### ISSUE THREAD

**Issue by WT-SML** [annotorious/annotorious#138]
i use selectAnnotation api,but image cannot be dragged.

**Comment by rsimon** [comment]
Sorry, I don't understand your problem description. You are using `.selectAnnotation` to select an existing annotation on the image. Does the selection work? Does the editor window popup up & do the resize handles appear around the shape? You should now be able to drag the shape.

Are you using Annotorious standard version (normal image)? Or the Annotorious OpenSeadragon plugin (high-res zoomable image)?
