### ISSUE TITLE
Mouse coords vs. SVG coords

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious#14]
There is a mix in some places between SVG coordinates and DOM element offsets. Make sure all mouse coordinates are __always__ transformed to SVG coordinates for drawing operations. That will make sure drawing also works correctly on scaled/responsive images.

Bonus benefit: once that is implemented, we should be able to reuse this as-is for the OpenSeadragon implementation.

**Comment by noorsyyed** [comment]
that would be a killer feature

**Comment by rsimon** [comment]
This is now almost complete. There is one remaining issue, which is that the resize handles scale with the image. That's undesired - only the shape should scale, the resize handles should remain same size.
