### ISSUE TITLE
CTRL+select

### ISSUE THREAD

**Issue by sanjayaaucterra** [annotorious/annotorious#143]
I want to link the bounding boxes. 
I am just trying to select the bounding boxes while Ctrl+click. But the "selectAnnotation" has no event to check weather click or CTRL+Click
anno.on('selectAnnotation', function(annotation) {
  // 
});

What I want is , When click on the bounding box if ### mouse click open the modal dialog else  ### CTRL+click another function
Thanks in advance

**Comment by rsimon** [comment]
I actually discussed the ability to CTRL+select multiple annotations in the context of another project recently. This might come as a feature (or, ideally, as a plugin). I still need to think through the user interaction for this one first, though.

Can you share a bit about what your use case is, and how you would imagine the interaction would look like in your scenario, after you clicked CTRL+select? (Would you pop up anther box etc.?)

**Comment by rsimon** [comment]
While CTRL+Click functionality won't come as a core feature of Annotorious, it is now possible to build plugins that achieve this. The most important recent API additions are:

- [disableSelect](https://recogito.github.io/annotorious/api-docs/annotorious/#disableselect). This causes Annotorious to no longer select annotations when they are clicked
- the [clickAnnotation event](https://recogito.github.io/annotorious/api-docs/annotorious/#clickannotation). This will fire when an annotation is clicked, regardless of whether selection is currently en- or disabled.

A plugin can, for example, disable selection when the CTRL key is pressed, and then do other things when the user clicks another annotation. I'm currently using this in [another project](https://github.com/machines-reading-maps/mrm-recogito-ui) to build a plugin that allows users to group annotations. It's likely the plugin will be released as a self-contained project later. Currently, it's part of the [project codebase here](https://github.com/machines-reading-maps/mrm-recogito-ui/tree/main/src/group).
