### ISSUE TITLE
selectAnnotation API fires selectAnnotation event

### ISSUE THREAD

**Issue by yyhhkk12** [annotorious/annotorious#145]
version: Standard version
I added `selectAnnotation` event handler and called `selectAnnotation` API.
As the result, 'selectAnnotation event fired.' printed in console.

    anno.on('selectAnnotation', (annotation) => console.log('selectAnnotation event fired.'));
    anno.selectAnnotation(annotationId);

    ---console---
    selectAnnotation event fired.
    -------------

But, according to [API Docs](https://recogito.github.io/annotorious/api-docs/annotorious/#selectannotation), `selectAnnotation` API don't fires `selectAnnotation`  event.

**Comment by rsimon** [comment]
Thanks for reporting! Fixed in b5df3d8b03d6613d77f7ccaae5f52c7e25aeef6b
