### ISSUE TITLE
Unclosed polygon while drawing

### ISSUE THREAD

**Issue by brianbourke75** [annotorious/annotorious#150]
It would be great when drawing a new polygon the polygon would not be closed (and would be more of a polyline) until the drawing is completed.

Thanks for the great tool!

**Comment by rsimon** [comment]
Thanks for the nice feedback! Yes, the polygon tool is still a in a bit of the-most-basic-version-that-work mode ;-) One advantage of the current version is that it works nicely with the [dim mask](https://recogito.github.io/guides/customizing-styles/). But a) the polygon tool will be improved in the longer run anyway (see #45), and b) there might as well be different polygon tool versions (or one with config options). I'll definitely keep the request in mind for further planning.

**Comment by rsimon** [comment]
Just a quick update that work on an improved polygon tool is now underway here:
- https://github.com/recogito/recogito-client-plugins/issues/15

This will include the UX described above. I'm closing this issue in favor of the https://github.com/recogito/recogito-client-plugins/issues/15
