### ISSUE TITLE
No point when ending polygon drawing

### ISSUE THREAD

**Issue by brianbourke75** [annotorious/annotorious#151]
When one ends the drawing of a polygon with a double click a final point is placed at the point of the double click.  Generally when I am drawing I am looking at the polygon as is and I don't think about the final point when I go to end.  It would be a change in behavior where the double click is a simple acknowledgement of the completion of the polygon without that final point.

Again, this and the open seadragon tool are lovely and I thank you so much for making them!

**Comment by rsimon** [comment]
I agree, that behavior would be better. (And/or another commonly seen pattern, where clicking the first point of the polygon again would close the shape. This is planned for #45.)

**Comment by brianbourke75** [comment]
Great, thanks for the feedback!

**Comment by rsimon** [comment]
I'm moving this issue over to the plugin repository. In the [improved polygon selection tool](https://github.com/recogito/recogito-client-plugins/issues/15) I'm currently working, closing the shape will work by clicking the first point of the polygon again.

**Comment by rsimon** [comment]
__Update:__ the plan for the [new polygon tool](https://github.com/recogito/recogito-client-plugins/tree/main/plugins/annotorious-improved-polygon) is that either of the following actions will close the polygon:

1. hovering the mouse over/nearby the first point and clicking once (when hovering nearby, the cursor will snap over the first point)
2. double click (anywhere) will close the polygon, without creating a new point, as you suggest above

Like the other issues, I'm closing this one in favour of the "todo-list" issue for the new polygon tool:
- https://github.com/recogito/recogito-client-plugins/issues/15
