### ISSUE TITLE
Custom widget not showing on production

### ISSUE THREAD

**Issue by alaksandarjesus** [annotorious/annotorious#153]
I am trying to integrate angular+openseadragon+annotorius
In my component 
```
import * as OpenSeadragon from 'openseadragon';
import * as Annotorious from '@recogito/annotorious-openseadragon';
import { SELECT } from 'src/app/widgets/select';
```

And after initializing openseadragon viewer

`this.annotorius = Annotorious(this.viewer, { widgets: [SELECT] });`

I am getting a dropdown on development mode

![image](https://user-images.githubusercontent.com/4712552/126765607-75f38bf1-7ed7-4cbd-a5c7-59cef717c6a0.png)

But the dropdown is missing on the production mode.

![image](https://user-images.githubusercontent.com/4712552/126766219-efe9cbef-55ab-404f-bb83-1a1612c467a0.png)

Below is my code for select widget

```
import { get, forEach, isEqual } from 'lodash';

export const SELECT = (args:any) => {

const purpose = get(args, 'purpose', 'select-purpose');
  // 1. Find a current color setting in the annotation, if any
  var currentSelectBody = args.annotation ? 
    args.annotation.bodies.find((b:any) => {
      return b.purpose == purpose;
    }) : null;

  // 2. Keep the value in a variable
  var currentSelectValue = currentSelectBody ? currentSelectBody.value : null;

  // 3. Triggers callbacks on user action
  var addTag = (evt:any) => {
    if (currentSelectBody) {
      args.onUpdateBody(currentSelectBody, {
        type: 'TextualBody',
        purpose: purpose,
        value: evt.target.value
      });
    } else { 
      args.onAppendBody({
        type: 'TextualBody',
        purpose: purpose,
        value: evt.target.value
      });
    }
  }

  var createOptions = (options) => {
   
    let html$ = '<option value="">Select</option>';
    forEach(options, (option)=>{
      if(isEqual(option,currentSelectValue)){
        html$ += '<option value="'+option+'" selected>'+option+'</option>';
      }
      else{
        html$ += '<option value="'+option+'">'+option+'</option>';
      }
    });
    return html$;
  }

  // 4. This part renders the UI elements
  var createSelect = () =>{
    var select = document.createElement('select');
    select.className = 'form-select';
    select.addEventListener('change', addTag); 
    let html$ = '';
    const options = get(args, 'options', []);
    const parent = get(args, 'parent', false)
    if(!parent){
     html$ = createOptions(options);
    }else{
     const parentBody =  args.annotation.bodies.find((b:any) => {
        return b.purpose == parent;
      });
      if(parentBody && parentBody.value){
        const choices = get(args, 'options.'+parentBody.value, []);
        html$ = createOptions(choices);
      }else{
        html$ = createOptions([]);
      }
    }
    select.innerHTML = html$;
    return select;
  }

  var container = document.createElement('div');
  container.className = 'select-widget';
  container.appendChild(createSelect());
  return container;
}

```

**Comment by rsimon** [comment]
Yikes... that might be hard to debug. Any chance you can post a compiled version of your widget? I'm assuming something might break [when Annotorious decides whether this is a vanilla JS function or a React widget](https://github.com/recogito/recogito-client-core/blob/main/src/editor/widgets/index.jsx#L32-L41). This is the only part where I could imagine things looking significantly different between dev and prod mode...

I assume there are no error messages on the console, right?

**Comment by alaksandarjesus** [comment]
It seems, the passed function is considered as React Component.

I swapped the elseif condition in node_modules\@recogito\recogito-client-core\src\editor\widgets\index.js getWidget function

![image](https://user-images.githubusercontent.com/4712552/126897543-899fdfde-217e-4bdc-8d45-13059094fa15.png)

And it worked.

Note: I tried with example, ColorEditorWidget too https://recogito.github.io/guides/editor-widgets/

Note: After this, the annotorius-openseadragon folder must be rebuilt using npm run build
Reference: https://recogito.github.io/guides/hackers-guide/

**Comment by rsimon** [comment]
Yes, this works as a hack. But doesn't solve the problem as such: React components are functions, too. (Most of them at least, nowadays.) Therefore the check would fail for those now.

In general however, I'm pretty unhappy with my hacked auto-detection anyway. Perhaps in the future it would be better to let the user identify the type of plugin (function or React component) as a config param...

I'm keeping this issue open as a reminder for this change.

**Comment by rsimon** [comment]
__Update:__ it's still not clear what causes the auto-detection of the widget type (vanilla JS function vs. React component) to fail sometimes. As a workaround, the widget API now (= with the next release) supports an additional config parameter to force a widget into a specific mode: `force: 'React'` or `force: 'PlainJS`. E.g.:

```js
var anno = Annotorious.init({
  image: 'hallstatt',
  widgets: [ 
    { widget: ColorSelectorWidget, force: 'React' },
    'COMMENT',
    'TAG'
  ]
});
```
