### ISSUE TITLE
Bug in moving selection boxes

### ISSUE THREAD

**Issue by KennySmash** [annotorious/annotorious#155]
I've been getting an error where as soon as the event triggers to move a rect selection box, it jumps to some location off canvas with the handles in the top right corner, I've attached a vid showing the problem and the error that occurs on the stack is: 

```js
Uncaught TypeError: this.svg.viewBox.baseVal is null
    resizeObserver webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:21
    yd webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:21
    yd webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:21
    Sd webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:21
    Ad webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:21
    Ld webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:21
    emit webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:1
    Fd webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:21
    emit webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:1
    Ad webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:21
    mouseUp webpack:///./node_modules/@recogito/annotorious/dist/annotorious.min.js?:21
```

https://user-images.githubusercontent.com/7831621/127176921-e5384db3-f436-4a8b-be3a-1310065318c5.mp4

**Comment by rsimon** [comment]
Weird. Are you modifying the Annotorious SVG element in some way? Is the element under Annotorious an image? I could imagine this happens when you attach it to a normal DOM node.

**Comment by KennySmash** [comment]
So I've only changed the css for it and have my own formatter (using Annotorious's interface for it), the image I am using is an empty image with my height and width set before anno starts, but it sits on top of a canvas that I am piping PDF data into

**Comment by KennySmash** [comment]
Aha, so it appears to lock the selection box to a 1:1 aspect when I use a 1x1 transparent png, and its doing the jump bug when the img has no src property

**Comment by rsimon** [comment]
Annotorious uses the image naturalWidth and naturalHeight properties to size the annotation canvas. Just guessing that this might not work if the img tag had no src, or you're using eg a 1x1px image as a placeholder. Possible workaround, perhaps, would be to skip the img altogether, attach Annotorious to the canvas, and monkey-patch the canvas with fake naturalWidth/naturalHeight props equal to element width/height.

**Comment by KennySmash** [comment]
Thanks, I'll give that a try.

**Comment by KennySmash** [comment]
thanks again @rsimon for the lead, I got something pretty workable.  
for posterity here is how to do it : 

use the below code to generate an empty png of the right natural size using a canvas, in my case I use vue so my target img for annotations has its src value bound to the output of the generator, this keeps it consistent with the pdf pages I am pulling in (PDF pages can have independent sizes from the entire document)

this allows me to stream in the PDF in a canvas under the annotation layer in a performant layer, and I am tracking the annotation layers size and only running the generator if it changes size

I'll look at putting a pull request to add an option in annotorious to swap between using natural sizes and provided sizes for the annotation layer just to cover future cases like this (annotating non-images)

```
imageGenerator(pdfViewport){
    console.log('imageGen::pre', pdfViewport)

    let internalCanvas = document.createElement('canvas')
    internalCanvas.width = pdfViewport.width
    internalCanvas.height = pdfViewport.height

    const internalContext = internalCanvas.getContext('2d')

    $data.emptyOutput = internalCanvas.toDataURL('image/png')

    console.log('imageGen::post', $data.emptyOutput, internalCanvas, internalContext)
},
```

**Comment by rsimon** [comment]
Thanks for this! I think another fix (inside Annotorious) would be to keep using naturalWidth/-height like before, but falling back in width/height of that doesn't exist. With this in place, you should be able to attach Annotorious to the canvas element directly I think.

**Comment by KennySmash** [comment]
Seems like a good plan, I did a load of googling and couldn't dig up ways to make natural sizing mutable
