### ISSUE TITLE
Is there an event that's published as a selection is being resized?

### ISSUE THREAD

**Issue by kesinger** [annotorious/annotorious#156]
That is, createSelection is published when the  user clicks to start a selection, but is there a way to  get the dimensions of the selection as it's being  made?  

Basically what I'm after is I want to be able to display to the user the area they're selecting so  that they can  do things like 'select a 1  megapixel region'.

Thanks!

**Comment by rsimon** [comment]
When moving/resizing an existing annotation, the `changeSelectionTarget` event will provide updates for the selection shape. However, this event does **not** fire when a new selection is first created.

In other words: between `startSelection` (= user starts drawing a new shape) and `createSelection` (=user finished creating a new shape) there are no events at the moment. When modifying the newly created shape, `changeSelectionTarget` will get you the updates though.
