### ISSUE TITLE
Support for relative coordinates

### ISSUE THREAD

**Issue by martimpassos** [annotorious/annotorious#162]
It would be useful to be able to choose between absolute pixel coordinates and width/height percentages, specially for use with Wikidata's `relative position within image` qualifier

![image](https://user-images.githubusercontent.com/49573683/130674473-868610b8-99e9-4e09-b29e-aca851003f54.png)

**Comment by rsimon** [comment]
+1! Although that would fit the spec only for rectangle shapes. For those, however, it would be fairly easy to implement, if anyone fancies a pull request :-) (Changes would be needed in the RectFragment source file.

**Comment by martimpassos** [comment]
my JS skills are still incipient, but now that you pointed to the correct file to modify (which is normally what I spend hours looking for) I'll try and see if I can get it done sometime soon

**Comment by martimpassos** [comment]
So, I can add an argument on `toRectFragment` like 
```
const coordinateMode = {
  Pixel = "pixel"
  Percent = "percent"
}

export const toRectFragment = (x, y, w, h, image, mode) => ({
  const coordinates =
    mode === coordinateMode.Pixel 
      ? `xywh=pixel:${x},${y},${w},${h}`
      :  `xywh=percent:${Math.round(x/image.width*100)},${Math.round(y/image.height*100)},${Math.round(w/image.width*100)},${Math.round(h/image.height*100)}`
  source: image?.src,
  selector: {
    type: "FragmentSelector",
    conformsTo: "http://www.w3.org/TR/media-frags/",
    value: coordinates
  }
});
```
which is a bit ugly IMO, or split the function like 
```
export const toPixelRectFragment = (x, y, w, h, image) => ({
  source: image?.src,
  selector: {
    type: "FragmentSelector",
    conformsTo: "http://www.w3.org/TR/media-frags/",
    value: `xywh=pixel:${x},${y},${w},${h}`
  }
});

export const toPercentRectFragment = (x, y, w, h, image) => ({
  source: image?.src,
  selector: {
    type: "FragmentSelector",
    conformsTo: "http://www.w3.org/TR/media-frags/",
    value: `xywh=percent:${Math.round(x/image.width*100)},${Math.round(y/image.height*100)},${Math.round(w/image.width*100)},${Math.round(h/image.height*100)}`
  }
});
```
I'm not sure if this image parameter has the dimensions attributes I'm calling, or if they need to come from elsewhere. W3C requires 4 comma-separated integers, so I had to round them despite the Wikidata example above handling floats. Other than that, if this is something you/we want the user to choose when creating annotations, there's an UI element to this issue that is out of my league. Sorry if I completely murdered your code or misunderstood how it works... Let me know if this is along the lines of what you expect, I'll be happy to work on it towards a successful PR :)

**Comment by rsimon** [comment]
Thanks, this looks good! Splitting up the functions is probably a bit more readable. But I don't have strong opinions about that.

Regarding width/height: these need to come from the image `naturalWidth` and `naturalHeight` attributes. Width and height describe the size of the HTML image element, and that might be scaled from the original size 

Regarding a UI element: I don't think that's necessary. I'd expect the host application to define that, which means an extra init parameter to Annotorious should be enough (something like `fragmentCordinates: 'percent'`). (Plus: in the first instance, it's already an improvement if Annotorious can __read__ pct fragments. Even if it still would write it pixel coords.)

**Comment by martimpassos** [comment]
Ok, I _think_ I did it right. If you'd be so kind to review [this commit](https://github.com/martimpassos/annotorious/commit/170bacc898c8381f10c91c9325d435cc3b4b4838?branch=170bacc898c8381f10c91c9325d435cc3b4b4838&diff=split) before I open the PR... I had to make a stupid extra commit for the semicolons (can you tell I'm coming from Python?) and another when I realised it made more sense for it to be a boolean config (which by the way I added to the docs [here](https://github.com/martimpassos/project-website-source/commit/18c444be133ae0d1f1bcb7a7a5fd83d95a5bc579))

**Comment by rsimon** [comment]
Thanks for this! I think it looks good. I'm on the road now, but feel free to make the PR. I can always clean up and rearrange things in case this should be necessary. Eg. I'd rather keep the property in the config rather than the env (but think the respective code areas only might have access to the env?)

Also I think I'd rather keep the decision logic inside the RectFragment rather than the EditableRect class. But as I said, I can always rearrange things later if needed.

**Comment by martimpassos** [comment]
Ok. When you're able, let me know if these modifications get automatically carried over to the OpenSeaDragon plugin too (it seems to import the tools from the main API), so I can edit the documentation there as well. And thanks for `annotorious` too!

**Comment by rsimon** [comment]
Yes that's right. AnnotoriousOSD imports the relevant parts from Annotorious. Once the changes are published, the next AnnotoriousOSD release will automatically inherit them.

**Comment by rsimon** [comment]
Thanks again for your PR! I made a few tweaks. Support in AnnotoriousOSD does actually require a handful of (minimal) changes, but I'll take care of that.

**Comment by martimpassos** [comment]
Happy to help!
