### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious#165]
Looks like the Vite build (or, rather, the manual renaming afterwards) breaks connection between the minified JS and the source map build.

**Comment by darkmich** [comment]
If it helps, it looks like it starts at version 2.4.2 - 2.4.1 loads just fine.

**Comment by rsimon** [comment]
Thanks, yes. I changed the build tool between these versions. Already have an idea how to fix it. Will be ok again in the next release.

**Comment by rsimon** [comment]
Fixed in commit cf94545ebdf4ffc6d4ee35c5a8ed9493f1054589
