### ISSUE TITLE
Clicking outside image while creating polygon

### ISSUE THREAD

**Issue by Taveeh** [annotorious/annotorious#166]
While creating a polygon annotation, clicking outside the image given to the `Annotorious({image})` class randomly assigns a point to the polygon.

**Comment by rsimon** [comment]
Do you have an screenshot example for this? I was under the impression that the point would be "correct", at the mouse coordinates - which (obviously) is useless because they are outside the image. But I haven't seen any randomness. Might be browser-specific though, and/or depend on the CSS `position` settings of DOM elements that are parent to the image.

**Comment by Taveeh** [comment]
Before (triangle marks the click location):
![BeforeClick](https://user-images.githubusercontent.com/34962630/135051156-980f0e05-d5d0-47d8-8ff7-fb510aa42b66.jpg)
After clicking(the right point went wayoutside the image):
![AfterClick](https://user-images.githubusercontent.com/34962630/135051163-5787d732-5012-4a33-98bc-0a895b2952c0.jpg)

I believe it should stop at the maximum of the image

**Comment by rsimon** [comment]
Ok, that looks weird indeed. What browser is this on? I haven't encountered it before, but will check - thanks for reporting!

**Comment by Taveeh** [comment]
Chrome... it happens as well on Edge

**Comment by rsimon** [comment]
Ok, weird. I can't reproduce the exact same behavior [on the demo page though](https://recogito.github.io/annotorious/getting-started/) - the click seems aligned with the mouse exactly (but still outside, of course). So there must be some additional factor in play in your case.

![image](https://user-images.githubusercontent.com/470971/135055114-c5bbae82-3d5d-4aa8-8499-04a52ede679d.png)


Probably doesn't matter perhaps... Restricting to the image should resolve in any case.

**Comment by rsimon** [comment]
This might also be related to the following issue on the OpenSeadragon plugin:
https://github.com/recogito/annotorious-openseadragon/issues/13
