### ISSUE TITLE
changeSelection Event

### ISSUE THREAD

**Issue by KennySmash** [annotorious/annotorious#170]
Hey, would it be possible to add an event to annotorious that fires when changing selections but not targets,  
a potential config would be:  
```
anno.on('changeSelection', (oldTarget, newTarget) => {
  // 
});
```

a case would be when one note is selected and then another element is selected.  
if coming in as a new selection then the oldTarget could be null or if no new selection is made then the newTarget could be null

**Comment by rsimon** [comment]
You mean e.g. when an annotation is selected, and the user clicks into another one? Agreed - sounds like a useful shorthand. Need to look what that would take in terms of plumbing. (Probably not too much, actually...)

At the moment - in case you need a quick workaround - the `cancelSelected` and `selectAnnotation` would both be fired, and in the right sequence. (In terms of timing, I guess a `changeSelected` should follow these two events?)

**Comment by KennySmash** [comment]
Exactly, it would help reduce some overhead in detecting new/old notes and ones that my users have shared already.
I have some logic listening to what notes are selected and it applies a display class in another part of the app

**Comment by rsimon** [comment]
Added with the last commit. Works as follows:

```js
anno.on('changeSelected', function(annotation, previous) {
  // the new selected annotation
  console.log(annotation);

  // the previously selected annotation
  console.log(previous);
});
```
