### ISSUE TITLE
I'm Missing something obvious

### ISSUE THREAD

**Issue by Pdd68** [annotorious/annotorious#171]
Hi 
My code is below, all is ok but not tags are showing and they are never saved. Using the latest version 2.5.6
Edit function works well.
No matter what i put in widgets etc nothing changes.
Any advice pointers would be appreciated. thanks!

            var anno = Annotorious.init({
                image: 'ima',
                locale: 'auto',
                widgets: [
                    { widget: 'COMMENT' },
                    { widget: 'TAG', vocabulary: ['Colour', 'Font', 'Size', 'Image'] }
                ]
            });

**Comment by rsimon** [comment]
How are you saving (and loading) the tags? When you create a new tag in the interface, is it shown? Have you tried logging the annotation that's coming with the `createAnnotation` event? It should have a `body` for each tag with purpose `tagging`.

**Comment by rsimon** [comment]
If everything else works, this might also be a regression bug related to the introduction of semantic tagging vocab support... You could try switching back to V2.5.4 and see if that changes anything.

**Comment by Pdd68** [comment]
Thanks i'll go and look at the console logs plus try a roll back to 2.5.4  I'm actually saving the annotations in our database and retrieving them on image load. No Tag data is appearing anywhere i can see. All working quite well. just a few niggles.

**Comment by Pdd68** [comment]
anno.on('createAnnotation', function (a) {
                console.log('created', a);


Image attached from console log. No Tag info i can see. I'm capturing this before i'm saving to database. Many Thanks for any guidance. Roll back did not change anything. 


![image](https://user-images.githubusercontent.com/91965997/136049520-7ef76be9-5622-4e71-be2e-664d6360e53c.png)

**Comment by Pdd68** [comment]
removed locate: auto - no change.
Image of page when i click and drag to draw box- no tags appear at all.

![image](https://user-images.githubusercontent.com/91965997/136054366-6aa6df70-3dc8-406b-8696-52955006dc52.png)

**Comment by rsimon** [comment]
Ok weird. I can't reproduce, but will dig deeper. However: that screenshot can't be from any of the recent versions. (The corner handles are circles since version 2.2x I think!) Can you double check how you are importing Annotorious? 

There might be a stray script import that pulls in an ancient Annotorious version, and the 2.5x isn't actually loaded.

**Comment by rsimon** [comment]
That BTW also match your error characteristic, because the way the widgets (and tag vocab) are initialized had changed since back then.

**Comment by Pdd68** [comment]
Interesting, i'm downloading from here and putting in same directory as page. Think it should work ok?

![image](https://user-images.githubusercontent.com/91965997/136061232-d61c8d00-a7fe-474e-aedf-f14dc1bd716f.png)

**Comment by rsimon** [comment]
Nope, something must be going in on in your HTML page, about the way you are importing the script file. I just tested the .js and .css file from the release package & that works as it should. (Tested in Chrome + FF.)

![screencast](https://user-images.githubusercontent.com/470971/136063218-3367b7b3-605d-484c-9373-895066c2a753.gif)

Make sure you check all your `<script>` import tags in the HTML page. There must be some import that's pulling an older version (possible from the CDN).

**Comment by Pdd68** [comment]
thanks will look

**Comment by Pdd68** [comment]
Hi, sorry for delay, when I copy my files to the server it works great as expected, something very odd with my machine. As you say must be finding old file somewhere. i'll do a search. thanks, for your help.

**Comment by Pdd68** [comment]
FYI - Emptied cached data in chrome browser sorted the issue!

**Comment by rsimon** [comment]
Argh - yes, I should have thought about this. The old classic. The distributions have always had the same filename (annotorious.min.js), so browser cache can indeed be an issue. Good to hear it's working now!
