### ISSUE TITLE
Question about using customizing placement of annotation text body

### ISSUE THREAD

**Issue by elitz123** [annotorious/annotorious#181]
I have a general question about using customizing the placement of an annotorious annotation text body. As you can see on the attached screen shot, i am using it to outline rooms on a house floor plan drawing (<img> resource). The outline is represented by an  svg polygon annotation shape that effectively outlines a room. On top of that, i'd like to place text with a transparent background that i can position in a specific location on top of the underlying polygon shape. The text effectively identifies the name of the room. I've looked at the API and do not see a clear way to control the placement of the text body. I saw one of the plugins called something like "Shape Label" that places a label above the shape...but i want the annotation to appear on top of the shape in a text box with a transparent background. Any ideas how i can achieve this using annotorious ? 

thanks much

Elliot Litz 

![annotoriousQuestion](https://user-images.githubusercontent.com/5573076/141513786-b06df668-e432-4c7c-8dac-c85fe887cca1.png)

**Comment by rsimon** [comment]
Hm, that might not be exactly the use case that Annotorious is trying to address.

You would probably be able to create your own plugin that works in a similar way than the ShapeLabels plugin (or modify the existing plugin). But that would definitely mean writing your own CSS to achieve this effect. If your main intent is to label the image, something like marker.js or EasyAnnotate might be a better fit.
