### ISSUE TITLE
Can I edit some functions?

### ISSUE THREAD

**Issue by Zvyozdo4ka** [annotorious/annotorious#182]
I am gonna use your library with making or adding some features, like static changing the color of polygon. How can I edit the function? 

For using library I have to provoke these files:
 <script src="../annotorious-2.5.10/annotorious.min.js"></script>
    <link rel="stylesheet" href="../annotorious-2.5.10/annotorious.min.css">
    <script src="../annotorious-2.5.10/recogito-polyfills.js"></script>

But if I edit any of js files, nothing has been changed. How to get know precisely to which js scripts should I provoke in index.html?

I am freshman in such kind of issues, I would appreciate any help.

**Comment by rsimon** [comment]
Dear @Zvyozdo4ka,

I would recommend against making changes to the distribution files directly. (They are minified, and most hacks to the source code will almost certainly lead to unexpected side effects.) Luckily, most aspect of Annotorious are quite flexible & you can configure and adapt without the need to hack the source code.

If you want to make changes to the style, see this guide:
https://recogito.github.io/guides/customizing-styles/

If you want to add your own elements to the popup editor, see here:
https://recogito.github.io/guides/editor-widgets/

If you really end up hacking Annotorious code, there's an introductory guid here. (But do keep in mind that this is where things start to get complicated, in case you are still beginning with JavaScript.)
https://recogito.github.io/guides/hackers-guide/

Cheers,
R

**Comment by Zvyozdo4ka** [comment]
@rsimon Thank you very much for your recommendations!
