### ISSUE TITLE
Making saveSelected() also work for new annotations

### ISSUE THREAD

**Issue by Dzeri96** [annotorious/annotorious#185]
I'm trying to add keyboard shortcuts to my widget, by mapping the rumber row on the keyboard to a set of pre-defined buttons which represent classes. The desired behavior is to have these shortcuts both set the class and save the annotation which is currently being created, but I can't find a way to do it reliably.

`saveSelected` only seems to work when editing an already existing annotation, and I can't click the OK button trough the DOM, because a new version of the widget with the annotation class correctly set has not been rendered yet, making the OK button just close the widget.

I suggest making `saveSelected` work in those cases when the actual annotation hasn't been saved yet, but I'm open to any workarounds.

**Comment by rsimon** [comment]
Are you using this in [headless mode](https://recogito.github.io/guides/headless-mode/)?

**Comment by Dzeri96** [comment]
No, I'm using it with the editor enabled. In fact I'm using the OSD plugin but thought the issue was more relevat for this repo.

**Comment by rsimon** [comment]
Added this to OpenSeadragon version, too: https://github.com/recogito/annotorious-openseadragon/commit/4bb7ff2551c241fdf2685dd6c96bee080011dddc
