### ISSUE TITLE
Latest version of annotorious  does not work well for drawing boundaries

### ISSUE THREAD

**Issue by Vidyadayini** [annotorious/annotorious#190]
The previous version  2.6.0 works fine but 2.6.1 does not allow drawing boundaries when testing from localhost where the image from the server cannot be downloaded.

I see the following console error

annotorious.min.js?73e3:24 Uncaught TypeError: r.clone is not a function
    at eval (annotorious.min.js?73e3:24)
    at iS.emit (annotorious.min.js?73e3:1)
    at HTMLImageElement.eval (annotorious.min.js?73e3:24)

```
      <img
            ref={imgEl}
            id={`${id}`}
            alt="result"
            onError={onError}
            src={`/repo/path1/${id1}/image/${id2}/`}
        />
```
        
 It now only works fine when the image is like this
    

```
     <img
            ref={imgEl}
            id={`${id}`}
            alt="result"
            onError={onError}
            src="https://media.istockphoto.com/photos/winter-in-the-sequoias-picture-id1292624259"
       />
```

```
         annotorious = new Annotorious({
          image: imgEl.current,
          drawOnSingleClick: true,
          disableEditor: true,
          allowEmpty: true,
        });

```

**Comment by rsimon** [comment]
Thanks for reporting. There was a minor change to how lazy loading is handled. It might be related to that. Just to confirm: you are using Annotorious standard version in a Rect project, right? Are you using the `onLoad` handler on the image anywhere?

**Comment by Vidyadayini** [comment]
Yes I am using Annotorious standard version in a React project. No onLoad handler.

**Comment by rsimon** [comment]
The bug is now fixed on the main branch. Will work again in the next release (v2.6.2).

**Comment by adnanrafique** [comment]
Hello @rsimon , I am also facing this issue.

![image](https://user-images.githubusercontent.com/20041254/177535666-4868a06d-aece-4a36-b5aa-dc394bd408ea.png)

This happens only when image is loaded first time in the browser. Second time it works fine.

When image loads first time:
![image](https://user-images.githubusercontent.com/20041254/177538213-c1d33f5a-12b6-429a-a4bd-01338c672090.png)

When it loads second time:
![image](https://user-images.githubusercontent.com/20041254/177538455-bcec1b73-b8af-42b9-94a0-75a439733812.png)

Annotorious Version
"@recogito/annotorious": "^2.6.1",

**Comment by adnanrafique** [comment]
Fixed. I was using version 2.6.1.  Just upgraded it to 2.6.2 as mentioned in the above comment by @rsimon and it works fine now.
