### ISSUE TITLE
Can Annotorious also support an overrideId function on createAnnotation ?

### ISSUE THREAD

**Issue by Vidyadayini** [annotorious/annotorious#196]
I see the Recognito supports and overrideId function

```
r.on('createAnnotation', async (annotation, overrideId) => {
  // POST to the server and receive a new ID
  const newId = await server.createAnnotation(annotation);

  // Inject that ID into RecogitoJS
  overrideId(newId);
});
```

I am trying to override the default Id set by Annotorious and use the Id sent by the server. Was wondering if this enhancement can be done on Annotorious createAnnotation

**Comment by rsimon** [comment]
Annotorious already supports the same. See here: https://recogito.github.io/annotorious/api-docs/annotorious/#createannotation

**Comment by rsimon** [comment]
P.S.: if you are using headless mode: there's a bug in the current release (v.2.6.1) that prevents this from working. The bug is already fixed on the main branch (if you are able to build from source). The next release (v2.6.2) should be out soon, and include the fix.

**Comment by Vidyadayini** [comment]
Yes. Was trying this in headless mode. Thanks for informing about the bug and fixing it in v2.6.2.

**Comment by rsimon** [comment]
Ok, great. Closing this issue then, since it's fixed for the next release.
