### ISSUE TITLE
Storing annotations

### ISSUE THREAD

**Issue by eric-clutch** [annotorious/annotorious#201]
Hello everyone,

How can I access the coordinates of my annotations? I am using the plugin that allows me to draw points, to which I add a couple tags. I can see the annotation metadata using:

```
    // Attach listeners to handle annotation events
    anno.on('createAnnotation', function(annotation) {
        console.log(annotation.body);
    });

```
But I can't find a way to obtain the (x,y) coordinates of the point annotation I've drawn. I want to pass them directly to my python backend, or even just display them on the JS console.
How can I do that? I have looked everywhere.

The code I use to draw points and so on:

```
<!-- JS -->
<script src="https://cdn.jsdelivr.net/npm/@recogito/annotorious@2.7.1/dist/annotorious.min.js"></script>
<!-- Selector Pack plugin -->
<script src="https://cdn.jsdelivr.net/npm/@recogito/annotorious-selector-pack@latest/dist/annotorious-selector-pack.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@recogito/annotorious@2.7.1/dist/annotorious.min.css">

<img id="image-to-annotate" src="{{ path_to_img }}" alt="img">

<script>
    var anno = Annotorious.init({
        image: document.getElementById("image-to-annotate")
    });

    // Init the plugin
    Annotorious.SelectorPack(anno);
    anno.setDrawingTool('point');

    // Attach listeners to handle annotation events
    anno.on('createAnnotation', function(annotation) {
        console.log(annotation.body);
    });
    annos = anno.getAnnotations();
    console.log(annos)

</script>
```

**Comment by rsimon** [comment]
Did you try logging the `annotation` object, not just `annotation.body`? The annotated region is encoded in the `annotation.target`. You can find more information about the annotation data model here:

https://recogito.github.io/annotorious/getting-started/web-annotation/

**Comment by eric-clutch** [comment]
Awesome, got it now :)
