### ISSUE TITLE
New events onEditorOpen and onEditorClose

### ISSUE THREAD

**Issue by lauxley** [annotorious/annotorious#214]
Right now to track if the editor is opened (in my use case this is needed to disable applications shortcuts) one have to bind to 7 currently available events, this is quite cumbersome and hard to maintain.  
Would it be possible to create 2 new events `onEditorOpened` and `onEditorclosed`?  Would be best if it would be the same for recogito.js as well.  
I can make a pull request for this but I would appreciate some pointers :)

**Comment by rsimon** [comment]
Won't get implemented, since v2.x is now deprecated & v3 is organized differently.
