### ISSUE TITLE
Is there a way to copy paste annotations ?

### ISSUE THREAD

**Issue by Vidyadayini** [annotorious/annotorious#215]
I am trying to clone annotations. Is there a way to do that ?

**Comment by rsimon** [comment]
You could just get the selected annotation, change the ID and re-add?

**Comment by Vidyadayini** [comment]
ok. will try.

**Comment by Vidyadayini** [comment]
@rsimon  How do we manually created an annotation in headless mode ?

**Comment by rsimon** [comment]
The drawing tools work just the same way in headless mode. See demo page here: https://recogito.github.io/guides/headless-mode/

Or am I misunderstanding what you need?

**Comment by Vidyadayini** [comment]
Looking for something like anno.createAnnotation(obj) since we need to create it on paste

**Comment by rsimon** [comment]
`anno.addAnnotation` perhaps?

See https://recogito.github.io/annotorious/api-docs/annotorious/ for full API docs.

**Comment by Vidyadayini** [comment]
One thing I see is the x, y coords of the label is not the same as the offsetX, offsetY, relative to the image. How are the  coords in an annotorious label calculated ? I need to convert the offsetX, offsetY coords to annotorious coords before addAnnotation. Otherwise they are not positioned correctly.

**Comment by rsimon** [comment]
Annotation coordinates are always in the coordinate space of the natural resolution of the image. That means: in Annotorious standard, cords are equal to offsetX/offsetY - unless the image is scaled via CSS. In Annotorious OpenSeadragon, you'd need to use the functions (in OSD) for coordinate translation to go from viewport to image cords.

**Comment by rsimon** [comment]
Annotation coordinates are always in the coordinate space of the natural resolution of the image. That means: in Annotorious standard, cords are equal to offsetX/offsetY - unless the image is scaled via CSS. In Annotorious OpenSeadragon, you'd need to use the functions (in OSD) for coordinate translation to go from viewport to image cords.

**Comment by Vidyadayini** [comment]
Thanks.
