### ISSUE TITLE
getAnnotationById returning undefined when annotation is already selected

### ISSUE THREAD

**Issue by hsellik** [annotorious/annotorious#219]
Hi!

I have noticed that `getAnnotationById` method returns `undefined` when the same annotation is already manually selected/highlighted in the image. Are you able to reproduce this easily or should I try to provide an example?

I'm using the OpenSeadragon plugin, but I imagine this also affects standard version as well. 

Best regards,
Hendrig

**Comment by rsimon** [comment]
Weird - I can't seem to reproduce this. I tried with a standard Annotorious OpenSeadragon setup, in both normal and read-only mode. `getAnnotationById` returned the annotation, regardless of whether I selected it or not. There must be something additional going on in your case. Coud you set up an example, so I can have a look?

**Comment by hsellik** [comment]
Sorry for the delayed response. Currently, I wasn't able to reproduce a minimalistic example. I'll come back to it, if it starts to be a problem in my application. I guess this issue can be closed for now.
