### ISSUE TITLE
Seeing error on loading annotations using percent on first load

### ISSUE THREAD

**Issue by Vidyadayini** [annotorious/annotorious#220]
I see the following error when I use percent to load annotations for the first time.

annotorious.min.js?73e3:24 Error: <g> attribute transform: Expected number, "scale(NaN)".

    anno.setAnnotations([
      {
        'id': 123,
        'type': 'Annotation',
        'body': [{ 'type': abc, 'test': false }],
        'target': {
          'selector': {
            'type': 'FragmentSelector',
            'conformsTo': 'http://www.w3.org/TR/media-frags/',
            'value': 'xywh=percent:22,14,64,47',
          },
        },
      },
    ]);

However, this works fine if I use pixel

    anno.setAnnotations([
      {
        'id': 123,
        'type': 'Annotation',
        'body': [{ 'type': abc, 'test': false }],
        'target': {
          'selector': {
            'type': 'FragmentSelector',
            'conformsTo': 'http://www.w3.org/TR/media-frags/',
            'value': 'xywh=pixel:22,14,64,47',
          },
        },
      },
    ]);

Kindly help.

**Comment by kovtun77** [comment]
scale is defined in the function in AnnotationLayer.js:
```
  getCurrentScale = () => {
    const svgBounds = this.svg.getBoundingClientRect();
    const { width, height } = this.svg.viewBox.baseVal;

    return Math.max(
      width / svgBounds.width,
      height / svgBounds.height
    );
  }
```
You may debug what is happening there. 
May be svgBounds are 0x0?

**Comment by Vidyadayini** [comment]
So looks like this was not really an issue. The image was not loaded properly before I adjusted annotations depending on image size.
