### ISSUE TITLE
DEL key removes entire note while editing note contents

### ISSUE THREAD

**Issue by KennySmash** [annotorious/annotorious#227]
User found that using the DEL key to fix spelling issues deletes the entire note, 

the problem line seems to be : https://github.com/recogito/annotorious/blob/1c5fbeb4551486b76c51d4141021112d3c7e2677/src/ImageAnnotator.jsx#L82

**Comment by KennySmash** [comment]
Its the above line for sure, I appended a &&false and it stopped deleting the note

**Comment by rsimon** [comment]
Hm, it's a tricky one. The above hack disables the DEL key altogether, which means people can't use it to delete the annotation. Not sure about what the ideal UX would look like here.

The best I could come up with is that the DEL key event will be stopped from propagating when it originates from the comment field. ([I just added this to the base library](https://github.com/recogito/recogito-client-core/commit/f4d9ccaf08c328b7958e93f12bc6c3293a5dfbdb).) This way, pressing DEL will not delete the annotation while the comment field has focus. It will still keep working for folks who use headless mode though, or who don't use the comment field.

This will go live with the next release (v2.7.9).
