### ISSUE TITLE
Drag an annotation without first selecting it

### ISSUE THREAD

**Issue by sbendif** [annotorious/annotorious#229]
Hi,

we are placing annotations on the image programmatically and let the user resize them and move them around afterwards.
There are two things we would like to improve:

1. The user has to select the annotation with a single click and has to click again to move it around. Is there a way to prevent the selection click?
2. The user shouldn't be able to draw an annotation by himself because adding annotations is done programmatically. This is not a big deal because we delete such annotations afterwards. I just wanted to point that out because it could help finding a solution for 1.

Is there a way to achieve this behaviour with annotorious or any hint how we could implement that by means of a plugin or something?

Thanks a lot!

**Comment by rsimon** [comment]
Neither is possible out of the box, I'm afraid. But concerning 1.) you might be able to select annotations programmatically on hover. Listen to the `mouseEnterAnnotation` and `mouseLeaveAnnotation` events, and then call `anno.selectAnnotation` perhaps?

**Comment by rsimon** [comment]
Question 2) might be trickier... There was a discussion a while back about this on the chat. I think they solved it with a bit of a creative hack, by listening to the `startSelection` event, and then programmatically dispatching an Escape key event. Pretty wild... But has the effect of canceling the selection instantly when it starts.

FWIW I'm starting to think/work on a version 3 of Annotorious, which will introduce much stronger separation between shape drawing and popup editor, and also make behaviour changes easier. (But that might still be a longer time in the future.)

**Comment by sbendif** [comment]
Thank you very much for your input! We will try out 1 while leaving out 2 for the moment. That sounds too wild to me :-)
