### ISSUE TITLE
Can annotorious used in OpenSeaDragon like the old version?

### ISSUE THREAD

**Issue by samyuan31515** [annotorious/annotorious#23]
Hello, It's nice to find out that someone have rebooted the annotorious. I have used the old version of annotorious in my project for the Openseadragon Viewer, so I'm wondering can this new version use in the OpenSeaDragon like the old one?

**Comment by rsimon** [comment]
Eventually :-) Everything's still a bit under construction. But the basics work. If you can let me know which particular features of the old version you need, I can answer more specifically. 

There is one major difference in terms of how the project is set up, however. The version in this repository works __only__ for images. The OpenSeadragon plugin now has a separate repository (and is a separate JavaScript file):

https://github.com/recogito/annotorious-openseadragon

**Comment by samyuan31515** [comment]
Thanks for your fast reply! Unfortunately, my project is using the DZI on OpenSeaDragon not the image type. I am looking for a way to add a label or button beside the annotation when create the annotation just like the image below. Do you have any advise about dealing with this? Anyway thanks for your help!
![image](https://user-images.githubusercontent.com/16483648/83036207-e9581f00-a06c-11ea-87da-cbd8fe9abcfd.png)

**Comment by rsimon** [comment]
As I said: you need to check out https://github.com/recogito/annotorious-openseadragon for the  OpenSeadragon version. Support is basic, but it’s there.

You might be able to hack the labels into the annotationlayer yourself. If they have to show all the time, this might be tricky. If only mouseover is needed, that would be easy to do by using the `onEnterAnnotation` and `onLeaveAnnotation` events.

**Comment by rsimon** [comment]
P.S. I looked into the code quickly. This is where the OpenSeadragon plugin draws the shape:

https://github.com/recogito/annotorious-openseadragon/blob/master/src/annotations/OSDAnnotationLayer.js#L81

`drawRect` is an imported function from the normal Annotorious package (see [here](https://github.com/recogito/annotorious/blob/master/src/annotations/RectFragment.js)). You‘d need to replace that with your own SVG drawing code. Then you‘d have all the freedom to add extra SVG shapes, add labels based on Annotation contents etc.

The only downside at the moment is that you‘ll be creating a separate fork of Annotorious. It‘s not possible to do this without hacking it, I‘m afraid. But probably an ok solution nonetheless for now.
