### ISSUE TITLE
Draw features

### ISSUE THREAD

**Issue by M-Bekheet** [annotorious/annotorious#235]
Is there a way to store drawn shapes in the Annotorious object? 

I am thinking of having a brush tool for example on the canvas and want to use the Annotorious features on it. 
Also any idea on how to erase part of the annotation rectangle/polygon shape?

For the brush, I am thinking of storing the brush coordinates and converting them to Annotorious polygon, but then I will push a lot of boundaries points to Annotorious and I think there may be a better way.

**Comment by rsimon** [comment]
Do you mean you'd like to have a raster drawing layer? That would be interesting - but difficult to implement. Everything in Annotorious is based on SVG, which means that raster drawing (with a Canvas element) would effectively mean you'd have to implement an all-new drawing layer from scratch. The current Annotorious framework wouldn't provide much of a timesaver I think.  Or did you mean something else?
