### ISSUE TITLE
getting started suggestion

### ISSUE THREAD

**Issue by rlzijdeman** [annotorious/annotorious#236]
Hi, would it make sense to add an example html file and example image with the release? (The documentation seems to come from an angle where you have such a page already, but all I have is a bunch of folders with images that I'd like to annotate).

**Comment by rsimon** [comment]
Hi, the old release ZIPs had a sample HTML, image and annotations included. (More or less the contents of the development [public folder](https://github.com/recogito/annotorious/tree/main/public).) I guess it doesn't hurt to add them again in future releases.

The reason I no longer included them was that I had the impression that few people actually downloaded the ZIPs, but just grabbed the script + stylesheet from the CDN & the [Getting Started docs](https://recogito.github.io/annotorious/getting-started/) pretty much give you exactly the HTML code you need.

**Comment by rsimon** [comment]
Next releases will include the HTML sample file.
