### ISSUE TITLE
Select widget tags from dropdown llist

### ISSUE THREAD

**Issue by Sadhikakichu** [annotorious/annotorious#237]
config= {widgets: [
				'COMMENT',
				{ widget: 'TAG', vocabulary: [ 'Abnormal', 'Normal'], dropdown: true }
				]};

It shows the tags as dropdown but can't select the tags why ??  I want to display the tags in normal dropdown list and also select the multiple tags or single tag based on dependings.

**Comment by rsimon** [comment]
The drop-down option is a third-party contribution that is, unfortunately, a bit unmaintained. I'll try to look into this for one of the next releases.

(In the long term, the plan is to deprecate the  `dropdown: true` option, and implement a separate dropdown widget instead. There's this issue for reference: https://github.com/recogito/recogito-client-core/issues/96)

**Comment by rsimon** [comment]
Closing this issue. Tag widget will only support autocomplete. A `<select>`-style dropdown would e scope for a (3rd party) editor plugin.
