### ISSUE TITLE
Error: \node_modules\@recogito\annotorious\src\index.js: Unexpected token (47:6)

### ISSUE THREAD

**Issue by Usman55555** [annotorious/annotorious#24]
Hi,

The demo example on this (https://www.npmjs.com/package/@recogito/annotorious) and the github page worked fine when using simple index and js files with "python -m http.server" but I was then planing for the big project.

I developed whole backend in Node.js using this library but now when I implemented it in React.js by the method that is written in the same pages as the following steps

1) npm i @recogito/annotorious
2) import { Annotorious } from '@recogito/annotorious';
3) const anno = new Annotorious({ image: 'annotoriousLabels' });

but It produces error on step no. 2 (import), below is the error picture
![image](https://user-images.githubusercontent.com/58660671/83334354-6aa6f000-a2bf-11ea-9b9e-d32f4f966c9a.png)

And the component file in which I'm including it is as following:

`import React from "react";
// @material-ui/core components
import { makeStyles } from "@material-ui/core/styles";
// core components
import GridItem from "components/Grid/GridItem.js";
import GridContainer from "components/Grid/GridContainer.js";
import Button from "components/CustomButtons/Button.js";
import Card from "components/Card/Card.js";
import CardHeader from "components/Card/CardHeader.js";
import CardBody from "components/Card/CardBody.js";
import CardFooter from "components/Card/CardFooter.js";

import { Annotorious } from '@recogito/annotorious';

import { apiURL } from '../../../config';
// import an from './annotorious';

const styles = {
  cardCategoryWhite: {
    color: "rgba(255,255,255,.62)",
    margin: "0",
    fontSize: "14px",
    marginTop: "0",
    marginBottom: "0"
  },
  cardTitleWhite: {
    color: "#FFFFFF",
    marginTop: "0px",
    minHeight: "auto",
    fontWeight: "300",
    fontFamily: "'Roboto', 'Helvetica', 'Arial', sans-serif",
    marginBottom: "3px",
    textDecoration: "none"
  }
};

const useStyles = makeStyles(styles);

const ImageCard = (props) => {
  const classes = useStyles();
  
  const anno = new Annotorious({ image: 'annotoriousLabels' });
  
  return (
    <div>
      <GridContainer>
        <GridItem xs={12} sm={12} md={12}>
          <Card>
            <CardHeader color="primary">
              <h4 className={classes.cardTitleWhite}>Picture</h4>
              <p className={classes.cardCategoryWhite}>Please label the picture below.</p>
            </CardHeader>
            <CardBody>
              <img 
              className = "annotatable"
              id = "annotoriousLabels"
              src = {apiURL + '/' + props.photo.url} 
              alt = "To be labelled..."
              width = '100%'
              height = '100%'
              />
            </CardBody>
            <CardFooter>
              <Button color="success">Save Changes</Button>
            </CardFooter>
          </Card>
        </GridItem>
      </GridContainer>
    </div>
  );
}

export default ImageCard;
`

**Comment by rsimon** [comment]
Hi, thanks for reporting. I can reproduce this on a clean project with `create-react-app` and it looks like this is because the `@recogito/annotorious` currently publishes the source code rather than the compiled distribution. (After building a new distribution package locally, the error was gone.)

I will try to push an updated release to `npm` which exposes the built dist by end of tomorrow or early next week. (In the meantime, as a workaround, I think it should be possible to import right from the current [annotorious.min.js](https://recogito.github.io/annotorious/annotorious.min.js) file?)

P.S. I'll try to figure out a solution where I can publish both the `dist` __and__ the `src`. Because I'll need to import source in the Annotorious OpenSeadragon project imports from it myself. If anyone has an idea how to do that - do let me know :-)

**Comment by rsimon** [comment]
Quick Q to @falafeljan: I guess even if I publish the distribution, by setting

```json
{
  "main": "dist/annotorious.min.js",
}
```

in my `package.json`, I can still import functions from the source folder in a project later, right? I.e.

```js
import { RectFragment } from '@recogito/annotorious/src';
```

**Comment by Usman55555** [comment]
I've tried directly importing annotorious.min.js file in script tag but it produces syntax error... and sorry I don't know about ReactFragment

**Comment by rsimon** [comment]
Script tag won't work this way. You'd need to download the file to your project source folder and then do something like

```js
import { Annotorious } from './annotorious.min.js';
```

The RectFragment thing was only for the Q to Jan :-)

**Comment by Usman55555** [comment]
Sir, I tried that way too...
import { Annotorious } from './annotorious.min.js';
 
but it produces these errors when importing them...

./src/views/Task/ImageCard/annotorious.min.js
  Line 1:1:       Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:112:     'define' is not defined                                                no-undef
  Line 1:123:     'define' is not defined                                                no-undef
  Line 1:284:     Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:1015:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:1696:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:2713:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:3183:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:3472:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:3496:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:3655:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:3700:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:3741:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:3804:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:3943:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:4340:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:4450:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:4539:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:5427:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:6417:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:6491:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:7311:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:7396:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:7757:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:8798:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:9926:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:10473:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:10567:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:11207:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:11299:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:11384:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:11439:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:12431:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:13678:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:14208:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:14350:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:14767:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:15016:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:15099:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:15551:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:16087:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:16140:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:16181:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:16767:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:17478:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:17598:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:17699:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:18030:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:18227:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:18435:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:18876:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:19132:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:19215:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:19303:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:19435:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:19941:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:20010:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:20042:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:20351:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:20371:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:20638:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:20805:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:20828:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:20905:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:23522:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:23674:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:24135:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:24287:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:26047:   'Atomics' is not defined                                               no-undef
  Line 1:29010:   'SharedArrayBuffer' is not defined                                     no-undef
  Line 1:29099:   'SharedArrayBuffer' is not defined                                     no-undef
  Line 1:31528:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:31865:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:31931:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:32030:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:32463:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:33753:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:34345:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:34626:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:36080:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:36864:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:37007:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:37068:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:37969:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:38841:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:39478:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:39504:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:39565:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:39700:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:40795:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:41809:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:41848:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:41925:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:42031:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:42561:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:42814:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:43443:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:43971:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:44174:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:45136:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:48440:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:48545:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:48882:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:49345:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:49627:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:50076:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:50361:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:50426:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:50460:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:51388:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:52805:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:52983:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:53131:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:53147:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:53379:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:53417:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:53553:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:54195:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:56456:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:57131:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:57175:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:57627:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:59580:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:59732:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:61878:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:65226:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:67271:   'msCrypto' is not defined                                              no-undef
  Line 1:67301:   'msCrypto' is not defined                                              no-undef
  Line 1:67447:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:68024:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:69805:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:70665:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:73039:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:81428:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:82152:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:82312:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:82425:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:82706:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:82927:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:83072:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:83274:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:84492:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:85241:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:85411:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:87656:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:88172:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:88445:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:89984:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:90151:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:90579:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:92001:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:95000:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:96106:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:96358:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:96432:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:96513:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:97001:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:97980:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:98621:   Unexpected use of 'event'                                              no-restricted-globals
  Line 1:99312:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:100371:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:100494:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:100655:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:101481:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:102008:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:104229:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:104278:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:104456:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:106452:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:106514:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:107083:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:108082:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:108223:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:108425:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:108495:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:108715:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:108823:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:108952:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:109149:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:109920:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:111041:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:111198:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:111319:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:111427:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:111569:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:111663:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:112069:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:112300:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:112646:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:112998:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:114293:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:114574:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:114700:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:115064:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:115764:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:117234:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:117831:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:118564:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:119732:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:119823:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:119893:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:120016:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:120169:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:120323:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:120764:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:121319:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:121581:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:121687:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:121757:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:122471:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:122633:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:123351:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:123630:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:124050:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:124869:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:125928:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:126051:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:126362:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:126502:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:126874:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:126953:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:127225:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:127291:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:128664:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:128787:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:128932:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:129083:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:129210:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:129874:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:129992:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:130202:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:130851:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:131349:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:131494:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:131620:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:132267:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:132400:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:132774:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:133209:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:134268:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:134391:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:134552:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:135100:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:135491:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:135664:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:135791:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:136630:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:137975:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:140166:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:140474:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:141359:  Expected an assignment or function call and instead saw an expression  no-unused-expressions

Search for the keywords to learn more about each error.

**Comment by rsimon** [comment]
Hm, looks like this indeed doesn't work, although it might be specific to `create-react-app`. What I could verify now though:

If you import via the `<script>` tag, Annotorious is available as a global variable (i.e. as `Annotorious` or `window.Annotorious`), so  you could still use it like that directly.

Be aware though that you need to supply an `img` DOM element. Handing it a JSX component won't work.

Cheers,
R

**Comment by rsimon** [comment]
Another additional comment: apart from the import problem, I don‘t think your above code can work. You are initializing Annotorious before the image exists. Which means Annotorious will unsuccessfully search for a DOM element with id `annotoriousLabels`.

Make sure you are handing it a reference to real (not virtual) DOM element, or an id of an element that exists in the DOM already.

**Comment by snvfk1n** [comment]
hi! a little late to the party. 

@rsimon: yes, you should be able to refer to the source files of the package via `import { ... } from '@recogito/annotorious/src`. the `main` field of the package manifest only resolves the _default_ import when no path is suffixed.

if you aim to expose the react source, i'd recommend exporting the styles separately as a CSS ubndle instead of relying on webpack to bundle them within source react components (e.g., `import './styles.css'`). this should allow folks to roll their own methods for loading the styles (e.g., `import '@recogito/annotorious/dist/style.css'` or directly via `<link>` tags).

do you have any idea why annotorious fails with `create-react-app` (CRA)?

@Usman55555: 
> ./src/views/Task/ImageCard/annotorious.min.js
Line 1:1: Expected an assignment or function call and instead saw an expression no-unused-expressions
Line 1:112: 'define' is not defined no-undef
Line 1:123: 'define' is not defined no-undef
Line 1:284: Expected an assignment or function call and instead saw an expression no-unused-expressions

this looks like JS linter warnings to me instead of proper parsing errors; so nothing wrong here per se. i think rainer explained it well in the above comment (use the global `window.Annotorious` instead of ES6 imports from the pre-built bundle).

**Comment by Usman55555** [comment]
No sir... it doesn't work by "import { Annotorious } from '@recogito/annotorious/src"... it also gives same error... and also by <script> tag and then window.Annotorious is undefined...

![image](https://user-images.githubusercontent.com/58660671/83382798-536e1c80-a3fd-11ea-9b17-1b9c38bd1ec1.png)

**Comment by rsimon** [comment]
The `<script>` tag import needs to go into your host page, probably `public/index.html`.

Here's what works in my case:

```html
  <head>
    <meta charset="utf-8" />
    ...
    <title>React App</title>
    <script src="https://recogito.github.io/annotorious/annotorious.min.js"></script>
  </head>
```
and then in `src/App.js`:

```js
import React from 'react';

function App() {

  console.log(window.Annotorious);

  return (
    <div className="App">
      Hello World
    </div>
  );
}

export default App;
```

Here's what happens:

- Annotorious is imported into the __host page__ as a global import, making the module available under `window.Annotorious`
- In your React app, you can get access, __with no additional import necessary__ because it's already globally available 

Two things to note, as I said:

- this is just a workaround until I can fix `npm install` to work properly in the next release
- you will need to make sure you  image already exists in the DOM when using `Annotorious.init`, you can't hand it a JSX component

**Comment by Usman55555** [comment]
Hi, sir...

I'm very very happy, that it works now... I'm very very grateful for your help.... thank you very much sir...
should I close this issue?

**Comment by rsimon** [comment]
Fantastic, good to hear it works. Yes, feel free to close the issue.

**Comment by Usman55555** [comment]
Sir, one more thing...

it is not loading the json... it is sending a lot of requests instead... I also need this ...
![image](https://user-images.githubusercontent.com/58660671/83432150-e33db600-a451-11ea-9e9b-6d3945ddeeff.png)

and I also need one more thing... Is there a way that I send predefined comments through some function.... instead of a user writing them

**Comment by rsimon** [comment]
Your annotation URL is invalid - see logs. You are handing an object to the .loadAnnotations method, which expects a URL. 

Please make sure to check [the API docs](https://github.com/recogito/annotorious/wiki/API-Reference). You might be looking for `.setAnnotations` instead.

Your second question: yes I think you are looking for `applyTemplate` (and maybe headless mode).

**Comment by Usman55555** [comment]
THANK YOU very much sir...

the url problem I solved by requesting the backend... and that's what I needed... and appyTemplate is what I needed... now this library is perfect for me...

thanks... for your time to help me...
