### ISSUE TITLE
Please add "rights" property

### ISSUE THREAD

**Issue by EmKarr** [annotorious/annotorious#244]
Dear Rainer,

considering ongoing efforts to implement stuff like Open Educational Ressources, where it is desireable to clearly state the licence under which material such as annotations are released, would it be possible to also include the "rights" values as defined by W3C (property "rights", fields "type" and "id")? This would improve very much automated import of annotations into other systems and their re-use.

Thank you so much for your tireless efforts for improving Annotorious,
Michael

**Comment by rsimon** [comment]
Hi Michael,

actually, that's already possible. Alas, it's not documented ;-)

Or, to be more precise: there's no specific feature for `rights`. But a mechanism that allows editor plugins to add arbitrary fields to the top-level of the annotation object. The method is called `onSetProperty`, and is handed to the `args` property that widgets receive when they are rendered.

This way you could, for example, implement a widget that offers a license chooser for the annotation. Is this what you are looking for? If annotations would be more globally licensed (i.e.: always CC-BY on everything), then you could currently do this in two ways:
- By simply modifying the annotation outside of Annotorious before it gets stored (i.e. the `rights` field would get set in the `onCreateAnnotation` handler
- By creating an "empty" widget, with no GUI element, that does nothing except use `onSetProperty` to inject the rights data.
