### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by raphael10-collab** [annotorious/annotorious#246]
`styles.css` : 

    @import '~@recogito/annotorious/dist/annotorious.min.css'

And 
    import { Annotorious } from '@recogito/annotorious'
    import './styles.css'

The lines causing the error message: `require is not defined`  :

    var anno = Annotorious.init({
      image: 'my-image'
    })

**Comment by rsimon** [comment]
Can you say a little bit about your setup, build process, bundler used etc.? Anything here that might apply to your case?

https://bobbyhadz.com/blog/javascript-referenceerror-require-is-not-defined

**Comment by raphael10-collab** [comment]
In `package.json` there is no "type": "module"

No use of `.mjs` extension

Partial content of the file (preload file-Electron environment):

    import { ipcRenderer, webFrame } from 'electron';
    
    import AutoComplete from './models/auto-complete';
    import { getTheme } from '~/utils/themes';
    import { ERROR_PROTOCOL, WEBUI_BASE_URL } from '~/constants/files';
    import { injectChromeWebstoreInstallButton } from './chrome-webstore';
    
    const tabId = ipcRenderer.sendSync('get-webcontents-id');
    
    export const windowId: number = ipcRenderer.sendSync('get-window-id');
    
    const goBack = () => {
      ipcRenderer.invoke(`web-contents-call`, {
        webContentsId: tabId,
        method: 'goBack',
      });
    };
    
    const goForward = () => {
      ipcRenderer.invoke(`web-contents-call`, {
        webContentsId: tabId,
        method: 'goForward',
      });
    };
    
    // https://annotator.apache.org/docs/getting-started/
    
    import { describeTextQuote } from '@apache-annotator/dom'
    import { createTextQuoteSelectorMatcher, highlightText } from '@apache-annotator/dom';
    
    import { Recogito } from '@recogito/recogito-js';
    import '@recogito/recogito-js/dist/recogito.min.css';
    
    // https://recogito.github.io/annotorious/api-docs/annotorious/
    
    import { Annotorious } from '@recogito/annotorious'
    // https://stackoverflow.com/questions/55138351/refused-to-apply-style-from-http-localhost1234-node-modules-primeicons-prime
    import './styles.css'
    
    //var anno = Annotorious.init({
      //image: 'my-image'
    //})


The lines causing the error message: `require is not defined` :

    var anno = Annotorious.init({
      image: 'my-image'
    })



I've tried to put the code into a `React component` : 
    
    import { Annotorious } from '@recogito/annotorious'
    import './styles.css'
    
    
    var anno = Annotorious.init({
      image: 'my-image'
    })

And now I get a different error : `Uncaught TypeError: annotorious_1.Annotorious.init is not a function` : 

![image](https://user-images.githubusercontent.com/70313067/187871281-7a728261-ac71-4c63-98cb-f64c55c0fc05.png)

**Comment by rsimon** [comment]
Not sure if this is causing the problem but you are initializing in the wrong way. See

https://recogito.github.io/annotorious/getting-started/

"Using npm" section.

**Comment by rsimon** [comment]
For React, also see here: https://recogito.github.io/guides/annotorious-in-react/

**Comment by raphael10-collab** [comment]
Taking the code from `Using NPM` : 
![image](https://user-images.githubusercontent.com/70313067/187874463-10fe1b7d-20dd-4413-b5cb-b2adfcdccde5.png)


I get `Cannot read property 'nodeType' of null` : 

![image](https://user-images.githubusercontent.com/70313067/187873977-6316c9f4-2c49-491b-a882-b4c77c749626.png)

**Comment by rsimon** [comment]
Are you using this on React now? Or another environment? If React, please follow the React guide. The error message means you're not handing an image to Annotorious.

**Comment by raphael10-collab** [comment]
Now it seems fine Thank you for your kind help
