### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by fadhiloffical** [annotorious/annotorious#247]
Hy,

I just used the plugin, but it's not working the documentation is not enough for a first-time user.

Attaching the code and error below

![Screenshot (3)](https://user-images.githubusercontent.com/52857924/187843910-f2b8e575-f50e-415c-819e-1be610941919.png)
![Screenshot (4)](https://user-images.githubusercontent.com/52857924/187843919-e3001206-573e-4614-a4e0-87cdbbd913ae.png)

**Comment by rsimon** [comment]
For using Annotorious in React, please follow the React guide here:

https://recogito.github.io/guides/annotorious-in-react/
