### ISSUE TITLE
Developing custom plugin

### ISSUE THREAD

**Issue by hammad-umar** [annotorious/annotorious#248]
Hi, I am developing a custom plugin. In which we have 2 radio buttons "static" and "dynamic". When I click on one of these options the radio button does not checked and the state is also not changing on adding or updating. State depends on first click and not changing when updating. Please take a look at a code.

https://stackblitz.com/edit/react-32p1yt?file=src%2FApp.js,src%2Fplugin%2Fplugin.js

**Comment by rsimon** [comment]
It works in principle. But you have two mistakes. First: the updates need to replace the __body__, not the value.

```js
// This won't update the body
args.onUpdateBody(currentRadioButtonValue, { /...

// That's the correct version
args.onUpdateBody(currentRadioButtonBody, { /...
```

Second: you are not actually setting the checked status of the button anywhere :-) You'll need the following two lines:

```js
// This sets the visible checked status based on the value of the body
staticRadioButtonEl.checked = currentRadioButtonValue === 'static';
dynamicRadioButtonEl.checked = currentRadioButtonValue === 'dynamic';
````

**Comment by hammad-umar** [comment]
Thanks for your help sir, it works! 


Regards, 
Hammad Umar
