### ISSUE TITLE
Annotation box does not appear in online demo on first visit

### ISSUE THREAD

**Issue by dosstx** [annotorious/annotorious#25]
When I view the online demo for the first time, I don't see any annotation boxes. Here's what I see in Edge and Chrome when I visit the demo link:

![image](https://user-images.githubusercontent.com/6342102/83570942-82af8700-a4ec-11ea-817a-86d603e429c4.png)
 
However, when I refresh the page, the annotation box does appear.

Not sure if it's an issue on my end.

**Comment by rsimon** [comment]
Thanks for reporting - I can reproduce it on my end, too. Doesn't happen consistently for me, but does happen. Looks like it's some sort of timing issue where the page & JavaScript is loaded already (and Annotorious starts to init). But the image isn't fully loaded yet.

I'll investigate!

**Comment by rsimon** [comment]
Update (and mostly a note to self): looked into this and the SVG elements are rendered into the DOM properly, but the SVG `viewBox` element is set to a value of `0 0 0 0`. The value is set [here](https://github.com/recogito/annotorious/blob/master/src/annotations/AnnotationLayer.js#L21), which shows that the image `naturalWidth` and `naturalHeight`, at that point in time are still zero.

Q: how to prevent this best. Defer creation of the layer until the image has been confirmed loading? Or handle inside the layer?
