### ISSUE TITLE
What algorithm does Annotorious use to select a label when clicking inside a label ?

### ISSUE THREAD

**Issue by vidya-talapady-percipient-ai** [annotorious/annotorious#253]
What algorithm does Annotorious use to select a label when clicking inside a label ?
There could be intersecting labels too. Can you please let me know the algorithm you use to find out which label to select when clicking inside of labels when there could be intersecting labels too.

Thanks in advance.

**Comment by rsimon** [comment]
Annotorious always picks the smallest label. This ensures that there are no obstructions (except in extreme edge cases).

**Comment by vidya-talapady-percipient-ai** [comment]
Could you also paste the code where Annotorious is doing this ? Basically the code for selecting a label on click.

**Comment by rsimon** [comment]
It works differently in Annotorious standard vs. Annotorious OpenSeadragon. In Annotorious standard, all of the SVG shapes are simply sorted by size, which means the smallest shape is always stacked on top. This way, mouse hover will always pick the top-most shape automatically; mouse clicks will [select the current hover](https://github.com/recogito/annotorious/blob/main/src/AnnotationLayer.js#L156-L166). Sorting happens [here in the code](https://github.com/recogito/annotorious/blob/main/src/AnnotationLayer.js#L344) (among other places). But it's not as centralized as an "algorithm" as you might hope. If you want to rebuild it, I'm afraid you'll need to read it ;-) 

P.S.: in Annotorious OSD, shapes are kept in a 2D index. Picking of the smallest shape [happens here](https://github.com/recogito/annotorious-openseadragon/blob/main/src/AnnotationStore.js#L147).

**Comment by rsimon** [comment]
FWIW [Annotorious v3](https://github.com/recogito/annotorious-3) will unify this behavior. Everything will work via the 2D spatial tree. (Also because Annotorious v3 will be WebGL, and no longer SVG. Thus DOM mouse hovers, like in the current version, are no longer possible.)

**Comment by vidya-talapady-percipient-ai** [comment]
Ok. Thanks.
