### ISSUE TITLE
Large numbers of plotted cells will be slow

### ISSUE THREAD

**Issue by zengnanhua** [annotorious/annotorious#254]

**Comment by zengnanhua** [comment]
![image](https://user-images.githubusercontent.com/22017107/199904283-26a73fb4-b643-4703-b81a-cc3af65bc5f9.png)

**Comment by rsimon** [comment]
Annotorious v2.x will work smoothly up until about 800-1.500 shapes, depending on the user's computer. Shape complexity has an impact. If, for example, you have polygons with many corners, you may get significant speed gains by simplifying polygon geometry before loading into Annotorious. (E.g. using something like [simplify.js](https://mourner.github.io/simplify-js/))

For bigger datasets: I'm currently working on [Annotorious v3](https://github.com/recogito/annotorious-3), which uses WebGL rendering. First tests suggest that this will handle up to 100.000 shapes in the browser.
