### ISSUE TITLE
Tooltips for Annotorious labels

### ISSUE THREAD

**Issue by Vidyadayini** [annotorious/annotorious#257]
How do I add tooltips to  annotorious labels created in headless mode with disableEditor: true set ?

Is there a demo somewhere ?

**Comment by rsimon** [comment]
See the hover tooltip plugin here:
https://github.com/recogito/recogito-client-plugins/blob/main/plugins/annotorious-hover-tooltip/src/index.js

This plugin is, unfortunately, undocumented. But the code shows how it works. I.e. you can track mouse position and use the built-in `onMouseEnterAnnotation` and 
`onMouseLeaveAnnotation` events to show/hide the tooltip.

**Comment by rsimon** [comment]
PS: for general support questions, please use the Gitter chat here rather than the issue tracker:
https://gitter.im/recogito/annotorious
