### ISSUE TITLE
drawOnSingleClick not working for rectangles

### ISSUE THREAD

**Issue by Vidyadayini** [annotorious/annotorious#262]
I have not seen drawOnSingleClick work yet. I always had to click and drag for rectangles.
I also tested this on https://codesandbox.io/s/wieoo?file=/src/App.js

**Comment by rsimon** [comment]
Ah - indeed. Looks like this is working for polygons, but not rectangles. Thanks for reporting. Marking this as a bug.

**Comment by rsimon** [comment]
Won't get fixed since v2 is now deprecated and v3 is organized differently.
