### ISSUE TITLE
Negative annotation coordinates

### ISSUE THREAD

**Issue by prithivin** [annotorious/annotorious#264]
When I annotate an image, I get negative values for selector coordinates. Can I please know why it is producing negative coordinates?

This is a sample coordinate:
xywh=pixel:-88.78811645507812,111.60940551757812,45.19615936279297,47.07933044433594

**Comment by rsimon** [comment]
Do you have an online demo where this can be reproduced? Or at least some minimal information about what your setup looks like?

**Comment by prithivin** [comment]
I am using Annotorious on my React web application. The application will be used to capture the screen and label various features in the frames. We will upload these frames along with annotations to our database. Then we compare the frames from this reference video with other videos to build some analytics. 
<img width="629" alt="Capture1" src="https://user-images.githubusercontent.com/95672879/205432952-6feaae02-4d09-4410-bb11-100f44020277.PNG">
<img width="667" alt="Capture2" src="https://user-images.githubusercontent.com/95672879/205432954-e777d5e8-2730-4b6c-b372-375b1549de28.PNG">
<img width="639" alt="Capture3" src="https://user-images.githubusercontent.com/95672879/205432956-81928086-9054-4435-abc6-b40388f5f54c.PNG">

To be specific I am displaying the image on canvas and providing a reference of the image to annotorious.
I have attached screenshots of the application for reference. Please let me know if you need further information.

Thanks and Regards,
Prithivin

**Comment by rsimon** [comment]
Hi,

> to be specific I am displaying the image on canvas and providing a reference of the image to annotorious.

Can you post the JSX/markup for this? Can you check in your browser console if there is a mis-alignment between the image and the SVG annotation canvas that Annotorious renders?

From your description, I assume you are handing a CANVAS elememnt to Annotorious, not an image? Do you have a version of the app online so I can check?

**Comment by prithivin** [comment]
Hi,

The application is not deployed on our server yet. The screenshots attached were captured from running the application on localhost.

Here is the JSX code:
``
const ScreenAnnotator = (props) => {

    // Ref to the image DOM element
    const imgEl = useRef();

    // Ref to file uploader
    const uploader = useRef(null);

    // The current Annotorious instance
    const [anno, setAnno] = useState();

    // Current drawing tool name
    const [tool, setTool] = useState('rect');

    // ImageList
    const [imageList, setImageList] = useState([]);
    const [index, setIndex] = useState(0);

    // AnnotationList
    const [annotationDict, setAnnotationDict] = useState({});

    // File uploader machine
    const [current, triggerUploader] = useMachine(fileUploaderMachine);

    const [error, setError] = useState(null);
    const [basicAlert, setBasicAlert] = useState(null);
    const [mediaform, setMediaform] = useState(null);
    // Init Annotorious when the component
    // mounts, and keep the current 'anno'
    // instance in the application state
    useEffect(() => {

        let annotorious = null;

        if (imgEl.current) {
            // Init
            annotorious = new Annotorious({
                image: imgEl.current
            });

            // Attach event handlers here
            annotorious.on('createAnnotation', annotation => {
                console.log('created', annotation);
                setAnnotationDict((dict) => {
                    let temp = {};
                    if (imageList[index]['timestamp'] in dict) {
                        temp = dict;
                        temp[imageList[index]['timestamp']].push(annotation);
                    }
                    else {
                        temp = dict;
                        dict[imageList[index]['timestamp']] = [annotation];
                    }
                    return temp;
                })
            });

            annotorious.on('updateAnnotation', (annotation, previous) => {
                console.log('updated', annotation, previous);
                setAnnotationDict((dict) => {
                    let temp = dict;
                    let timestamp = imageList[index]['timestamp']
                    for (let i = 0; i < temp[timestamp].length; i++) {
                        if (temp[timestamp][i]['id'] === previous['id']) {
                            temp[timestamp][i] = annotation;
                            break;
                        }
                        else {
                            continue;
                        }
                    }
                    return temp;
                });
            });

            annotorious.on('deleteAnnotation', annotation => {
                console.log('deleted', annotation);
                setAnnotationDict((dict) => {
                    let temp = dict;
                    let timestamp = imageList[index]['timestamp'];
                    let newArray = temp[timestamp].filter((obj, index) => (obj.id !== annotation.id));
                    temp[timestamp] = newArray;
                    return temp;
                });
            });
        }

        // Keep current Annotorious instance in state
        setAnno(annotorious);

        // Cleanup: destroy current instance
        if (annotorious !== null) {
            return () => annotorious.destroy();
        }
    }, [index, imageList]);
        return (
            <div>
                <center>
                    <p><b>Annotate Frame of Reference and its features</b></p>
                    {(basicAlert !== null) && (<BasicAlert alert={basicAlert} close={() => { setBasicAlert(null) }} />)}
                    <ErrorHandler error={error} />
                    <center>
                        <Box className="avatar-studio-questionnairebox" sx={{ justifyContent: "space-evenly", display: "inline-flex" }}>
                            <Paper elevation={4}>
                                <Box className="videobox">
                                    <img
                                        ref={imgEl}
                                        src={imageList[index]['url']}
                                        alt={"Image " + { index }}
                                    />
                                </Box>
                            </Paper>
                        </Box>
                    </center>
                    <FileUploader id="uploader" ref={uploader} mediaForm={mediaform} onUploadCallback={handleUploadSuccess} onErrorCallback={handleError} onUploadFailure={handleUploadFailure} />
                    <Box className="buttonbox" sx={{ justifyContent: "space-evenly", display: "inline-flex" }}>
                        <Box className="buttons">
                            {(!current.matches('uploaded')) ?
                                (<Button variant="contained" fullWidth={true} onClick={upload}>Upload</Button>) :
                                (<Button variant="contained" fullWidth={true} onClick={upload} disabled>Upload</Button>)}
                        </Box>
                    </Box>
                    <div style={{ width: "60vw", height: "12vh" }}>
                        <ScreenCarousel show={5} style={{ height: "100%" }}>
                            {
                                imageList.map((item, index) =>
                                    <Card sx={{ width: '10vw', height: '10vh', maxWidth: '10vw', mx: "1vw", my: "1vh", maxHeight: "10vh" }} onClick={() => { selectImage(index) }}>
                                        <img src={item.url} style={{ height: "100%", width: "100%" }} />
                                    </Card>
                                )
                            }
                        </ScreenCarousel>
                    </div>
                </center>
            </div>
        );
    }
}
``

Please let me know if you need further info.

Thanks and Regards,
Prithivin

**Comment by rsimon** [comment]
Looks all sensible. But hard to tell without being able to inspect the actual DOM in the browser console. I'm noticing you are changing the Annotorious instance when the index changes, but not when imgRef.current changes. Perhaps that's causing situations where the annotation canvas still has the size of the previous image?

**Comment by prithivin** [comment]
Hi,

I have fixed the issue. The error was due the size of the Box element that I used to wrap the image element. Thank you for your time.

Regards,
Prithivin.

**Comment by rsimon** [comment]
Great - good to hear it's working now!
