### ISSUE TITLE
clickAnnotation event doesn't fire if readOnly and disableEditor are true

### ISSUE THREAD

**Issue by kennysong** [annotorious/annotorious#270]
When `readOnly` and `disableEditor` are set to true, it seems like the `clickAnnotation` event doesn't fire if an annotation is already selected. 

The event does fires properly if those config variables are set to false. 

Here's a minimum example that reproduces this behavior: https://codepen.io/helloksong/pen/ExpoOWY

**Comment by lxow456** [comment]
Hi, I have encountered similar problems. Do you know what causes this? And have you solved this problem?

**Comment by kennysong** [comment]
No workaround yet, I just found a way to not use that event in our codebase.

**Comment by rsimon** [comment]
Closing as `won't fix` in Annotorious v2.x. Does work in v3.
