### ISSUE TITLE
Allow disabling delete hotkey in headless mode

### ISSUE THREAD

**Issue by blms** [annotorious/annotorious#273]
Hi @rsimon! I am using `annotorious-openseadragon` in a project, [`annotorious-tahqiq`](https://github.com/Princeton-CDH/annotorious-tahqiq).

I'm wondering if it would be possible to have an option to disable the delete hotkey when in headless mode. I see in #227 you prevent that event from firing when focus is in the comment field, but I am using headless mode and have my own set of text editor components. Of course, the delete key comes up when editing text, and it's causing accidental deletions of annotations. (Another interesting note: this was actually discovered by a Windows user pressing backspace, not delete. I wonder if backspace uses keycode 46 on Windows machines or certain browsers?)

It would be nice, if possible, to disable this hotkey in an option somewhere. Happy to open a PR if you have a preferred method for passing options like that to Annotorious.

Otherwise, if you have an idea for a workaround, please let me know!

**Comment by rsimon** [comment]
Hi @blms,

As a quick fix, I could imagine a `disableDeleteKey` init property that's false by default. I could patch that in quickly.

Cheers,
R

**Comment by blms** [comment]
That would be perfect, @rsimon, thank you!

**Comment by rsimon** [comment]
Hi Ben,

Should work now, if you build the latest version from source. (Let me know if you need help with that - although I strongly assume you won't ;-) 

Cheers,
Rainer

**Comment by blms** [comment]
Hey Rainer! Thanks so much for the quick work. I realized after trying this out that this logic is duplicated in `annotorious-openseadragon`, so I should have created the issue there 🤦 

Regardless, it's working perfectly when I make the same changes in that repo, so I'll open up a PR there. Thanks again!

Ben

**Comment by rsimon** [comment]
Yikes, of course. I should have checked the tahqiq project site! Anyways: the fix is of course identical for the OpenSeadragon version as you say. Thanks for the PR - merged!
