### ISSUE TITLE
Line tool

### ISSUE THREAD

**Issue by Sumitkumar1331** [annotorious/annotorious#276]
Is there any support for line tool? If not, can someone tell how to use line tool with openseadragon for annotation.

**Comment by rsimon** [comment]
Hi, there is only half-finished support for a line tool in the [Selector Pack](https://github.com/recogito/annotorious-selector-pack). But you would need to build from source, and I think you might actually have tweaks to the code to enable the tool. In other words: less-than-beta I'm afraid :-(

**Comment by martingluckman** [comment]
would really love to see line support added
