### ISSUE TITLE
TypeError: (e2 || []).map is not a function

### ISSUE THREAD

**Issue by abrahamarslan** [annotorious/annotorious#277]
This is the object logged on console that I'm trying to use with 

`annotation.setAnnotations(annotationObject)`

`{
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "type": "Annotation",
    "body": [
        {
            "type": "TextualBody",
            "value": "lolllzzz",
            "purpose": "commenting"
        }
    ],
    "target": {
        "source": "https://www.programmingbasic.com/_nuxt/img/thumbnail.5f0e517.webp",
        "selector": {
            "type": "FragmentSelector",
            "conformsTo": "http://www.w3.org/TR/media-frags/",
            "value": "xywh=pixel:241,347,306,31"
        }
    },
    "id": "#a310017a-728c-4c88-89cb-e7dce4dceea2"
}`

I keep getting this error 
![image](https://user-images.githubusercontent.com/14885767/220414589-87a53a39-33ff-434e-943b-1fd05745113e.png)

Have spent 2 days on this.

Not sure what is wrong here. 
Can someone help, please?

**Comment by rsimon** [comment]
`setAnnotations` expects a list of annotations, not a single annotation. Could this be the problem?
