### ISSUE TITLE
Using Annotorious Seadragon in Angular

### ISSUE THREAD

**Issue by Myrmex** [annotorious/annotorious#278]
I am trying to use Annotorious with its [plugin](https://recogito.github.io/annotorious/getting-started/osd-plugin/) for [OpenSeadragon](http://openseadragon.github.io/) in Angular 15.

When running my demo app, I get errors when creating the OpenSeadragon viewer, so probably I'm just missing some basic setup.
As it seems this is a [recurring issue](https://github.com/openseadragon/openseadragon/issues/1858), I'm trying to contribute here with some guidance to use this plugin with Angular, detailing the steps I followed up to this point. Eventually, I can provide my full sample code in a GitHub repository.

The main error just seems to point so some undefined object:

```txt
core.mjs:8506 ERROR TypeError: Cannot read properties of undefined (reading 'disableEditor')
    at new jc (annotorious.min.js:24:109315)
    at SdImgAnnotatorDirective.ngAfterViewInit (sd-img-annotator.directive.ts:127:17)
    at callHook (core.mjs:2488:22)
    at callHooks (core.mjs:2457:17)
    at executeInitAndCheckHooks (core.mjs:2408:9)
    at refreshView (core.mjs:10490:21)
    at refreshComponent (core.mjs:11480:13)
    at refreshChildComponents (core.mjs:10210:9)
    at refreshView (core.mjs:10469:13)
    at refreshEmbeddedViews (core.mjs:11434:17)
```

Additionally, I get a number of 404 as apparently the plugin is trying to load some UI image resources like `GET http://localhost:4200/images/zoomin_rest.png 404 (Not Found)` etc.

## Procedure

To start simple, I'd like to create an essential directive, whose only purpose is using Annotorious Seadragon to annotate an image and get an event whenever an annotation is changed. In my sample project I'm using a legacy simple image as the source, following the configuration in the OpenSeadragon [sample page](http://openseadragon.github.io/examples/tilesource-image/) for this scenario. 
Also, as I learn from [this page](http://openseadragon.github.io/docs/), performance reasons suggest to run Seadragon outside Angular zones. So, here is the procedure:

(1) create an Angular app and install the required **packages**:

```bash
npm i @recogito/annotorious @recogito/annotorious-openseadragon
npm i openseadragon
npm i @types/openseadragon --save-dev
```

Also add a `types.ts` file to your `src` folder with this content:

```ts
declare module "@recogito/annotorious";
```

and then import it where required.

(2) add the required Annotorious **CSS** to `angular.json` under `projects/architect/build/options/styles`:

```json
"styles": [
  "node_modules/@recogito/annotorious/dist/annotorious.min.css",
  "src/styles.css"
]
```

>According to the documentation, this is required at least when using OSD in fullscreen mode.

(3) add a **directive** like this:

```ts
// ...
import { Annotorious } from '@recogito/annotorious';
import * as OpenSeadragon from 'openseadragon';

@Directive({
  selector: '[sdImgAnnotator]',
})
export class SdImgAnnotatorDirective {
  private _tool: string;
  private _ann?: any;

  /**
   * The source image to annotate.
   */
  @Input()
  public source: string;

  /**
   * The initial configuration for the annotator.
   */
  @Input()
  public config?: AnnotoriousConfig;

  /**
   * The current drawing tool. The default available tools are rect and polygon,
   * but more can be available from plugins.
   */
  @Input()
  public get tool(): string {
    return this._tool;
  }
  public set tool(value: string) {
    if (this._tool === value) {
      return;
    }
    this._tool = value;
    this._ann?.setDrawingTool(this._tool);
  }

  /**
   * The optional initial annotations to show on the image.
   */
  @Input()
  public annotations?: any[];

  // ... events

  constructor(
    private _elementRef: ElementRef<HTMLImageElement>,
    private _ngZone: NgZone
  ) {
    this._tool = 'rect';
    this.source = '';
  }

  ngAfterViewInit() {
    const viewer = this._ngZone.runOutsideAngular(() => {
      OpenSeadragon({
        id: 'osd',  // hardcoded to make demo simpler
        tileSources: {
          type: 'image',
          url: this.source,
        },
      });
    });
    this._ann = new Annotorious(viewer, this.config || {});

    // initial annotations
    if (this.annotations?.length) {
      this._ann.setAnnotations(this.annotations);
    }
    // drawing tool
    if (this._tool !== 'rect') {
      this._ann.setDrawingTool(this._tool);
    }

    // events wiring...
  }
}
```

(4) add a sample image in the demo app `assets`, and a page using the directive like this:

```html
<div id="osd" sdImgAnnotator source="/assets/sample.jpg"></div>
```

Thank you!

**Comment by rsimon** [comment]
Thanks so much for the detailed writeup. I'd love to convert this to an example on the [Guides section](https://recogito.github.io/guides/) of the website at some point if I may!

Just to confirm: it's not working yet, correct? Are you reading `this._ann.disableEditor` anywhere in your code? It looks like there might be a timing issue involved, with `this._ann` not yet initialized.

As far as the missing images are concerned: yes, that as a bit of a confusing issue. You need to bring your own copies of the OpenSeadragon navigation icons (plus, minus, fullscreen, etc.) - or you use the `prefixUrl` config option to point OSD to the images on their own website (or CDN). E.g.:

```js
const viewer = OpenSeadragon({
  // ...
  prefixUrl: 'http://openseadragon.github.io/openseadragon/images/',
  // ...
});
```

**Comment by Myrmex** [comment]
Thank you! Feel free to use this sample code as you prefer, I'll be happy to be useful, and this is part of an open source, Academic project, so no problem at all. Anyway, I confirm you that at present it does *not* work. This `disableEditor` code is not mine, it's from the library, and I constantly get it as the first error whenever I call the `OpenSeadragon` function.. If it can be useful, I can prepare a repro GitHub repository extracting it from my code (just because there things are more complex). Meanwhile, I'll try your suggestion about the image issues, and let you know.

**Comment by rsimon** [comment]
Thanks - if there's anything you can share about the project, I'd be really interested to hear more about it!

About the bug: hm, it's really weird that this originates inside Annotorious. My suspicion is that it's somehow caused by race conditions and timing issues that happen when different frameworks - Angular vs. React (inside Annotorious) interact. I don't know what the cause is exactly, but have run into a similar case once:

https://github.com/recogito/recogito-react-pdf/blob/main/src/pdf/endless/AnnotatablePage.jsx#L134-L147

Maybe this helps?

**Comment by Myrmex** [comment]
Thanks, it seems that your first reply fixed the 404 errors about missing image resources. My demo code was updated accordingly.

As for the other issue, unfortunately it does not seem so straightfoward. I'm calling `OpenSeadragon` right in the after-view-init event, already wrapped in a `runOutsideAngular` call. If I try with a `setTimeout`, I would have to move inside it also all the following code, which depends on it; and in theory it should have no effect on Angular itself, as at this lifetime stage things are already initialized, so I'm not sure if there will be any benefit in letting it wait the "next turn". I have a single call to OSD, and this fails immediately; it's not the case that some later call fails. Anyway, I created a full repro repository to let everyone experiment: please find it [here](https://github.com/Myrmex/anntest). If you have any suggestion, I'll be happy to have a try.

Finally, the project I was referring to (Cadmus) currently has its introductory site [here](https://myrmex.github.io/overview/cadmus). I've already created a basic Angular wrapper for the non-OSD version of Annotorious and you can play with it at the "bricks" [demo site](https://cadmus-bricks.fusi-soft.com/#/img/annotator), under `Image/Annotator`. At present it's rather essential, but of course I'll welcome any suggestion. This component is supposed to be integrated into an annotation editor part inside the Cadmus framework, so that the annotations created there will be integrated with the rest of the data edited in it.

**Comment by rsimon** [comment]
Hm, in that demo it looks like you're importing Annotorious standard version, not the version for OpenSeadragon.

**Comment by Myrmex** [comment]
Thank you, you mean that I have to uninstall `@recogito/annotorious` and just use `@recogito/annotorious-openseadragon`? I was supposing that the "base" library was required, OSD being a plugin, that's why I included it. Anyway, I tried uninstalling it (`npm uninstall @recogito/annotorious`), but this does not seem to change the error. I still get this:

```txt
get buttons @ openseadragon.js:8076
core.mjs:8453 ERROR TypeError: Cannot read properties of undefined (reading 'disableEditor')
    at new jc (annotorious.min.js:24:109315)
    at SdImgAnnotatorDirective.ngAfterViewInit (sd-img-annotator.directive.ts:159:17)
    at callHook (core.mjs:2487:22)
    at callHooks (core.mjs:2456:17)
    at executeInitAndCheckHooks (core.mjs:2407:9)
    at refreshView (core.mjs:10437:21)
    at refreshComponent (core.mjs:11427:13)
    at refreshChildComponents (core.mjs:10157:9)
    at refreshView (core.mjs:10416:13)
    at detectChangesInternal (core.mjs:11571:9)
handleError @ core.mjs:8453
core.mjs:23530 Angular is running in development mode. Call enableProdMode() to enable production mode.
openseadragon.js:17711 Tile constructor needs 'cacheKey' variable: creation tile cache in Tile class is deprecated. TileSource.prototype.getTileHashKey will be used.
push.3504.$.Tile @ openseadragon.js:17711
zoomout_hover.png:1          Failed to load resource: net::ERR_CONNECTION_RESET
```

As you can see from the stack, my directive is just under the call to annotorious code, which fails somewhere finding this undefined object supposed to have a `disableEditor` function.

**Comment by natepelzel** [comment]
Hi! Hope you don't mind me interjecting here.  I recently implemented Annotorious/OpenSeadragon in Angular, and everything is working great.  I skimmed your example code, and the main thing I noticed that I did differently was importing the `Viewer` class directly from the openseadragon library and using that instead of the top-level `OpenSeadragon` function:

```ts
import { Viewer } from 'openseadragon';

// ...

this.#viewer = this.ngZone.runOutsideAngular(() => {
    return new Viewer({
      // config
    });
});
```

It looks like that's all the [OpenSeadragon function is doing anyway](https://github.com/openseadragon/openseadragon/blob/5f816246e41414de0df994ab3a78c750229cced8/src/openseadragon.js#L804-L806)


I was also able to write some supporting code that allowed me to use angular components as annotorious editor widgets. I'm happy to share if anyone is interested.

**Comment by natepelzel** [comment]
After a second look-through, looks like @rsimon  was right about your annotorious import.
you're doing:

```ts
import { Annotorious } from '@recogito/annotorious';
```

and I have:

```ts
// @ts-ignore
import * as Annotorious from '@recogito/annotorious-openseadragon';
```

**Comment by Myrmex** [comment]
Thank you! Of course I'm interested in your supporting code, it will surely be much better than my raw wrapping :), so please feel free to share if you can. As for your suggestions, they fixed the issue even though now I find another error:

```txt
TypeError: _recogito_annotorious_openseadragon__WEBPACK_IMPORTED_MODULE_0__ is not a constructor
    at SdImgAnnotatorDirective.ngAfterViewInit (sd-img-annotator.directive.ts:154:17)
```

I have other deadlines now so I can't have a better look, but I'll inspect this asap. Meanwhile, I've updated the [sample code](https://github.com/Myrmex/anntest) so you can directly test it to reproduce the above issue if you want.

**Comment by natepelzel** [comment]
[I sent over a PR](https://github.com/Myrmex/anntest/pull/1) with some changes that got it working locally for me.  Hope that helps!  I'll try and find some time to organize my code for the angular-based editor widgets and upload it so I can share.

**Comment by Myrmex** [comment]
Thank you very much, this fixed the issues! Eager to look at your code :)

**Comment by Myrmex** [comment]
I'm reopening this issue as I'm now getting a new error when using the above code in a different project.
Now, when I call `OSDAnnotorious()` I always get this error:

```txt
core.mjs:8416 ERROR TypeError: (_recogito_annotorious_openseadragon__WEBPACK_IMPORTED_MODULE_0___namespace_cache || _recogito_annotorious_openseadragon__WEBPACK_IMPORTED_MODULE_0___namespace_cache) is not a function
    at SdImgAnnotatorDirective.ngAfterViewInit (sd-img-annotator.directive.ts:131:31)
    ...
```

After this error, zooming works, but not the annotations. Maybe there is something connected to the way I load the image, as the only difference with the working example is that in the test project the image is just a static asset. Yet, the image is loaded and can be zoomed and panned.

## Repro Code

You can find the full code with the error at https://github.com/vedph/cadmus-bricks-shell. Just clone, compile libraries with `npm run build-lib`, and `ng serve`. Then open menu `Image/Seadragon image annotator`, pick an image, and see the error.

The OSD Annotorious directive is in project `@myrmidon/cadmus-sdimg-annotator`, and essentially is the same of the test project (which derived its code from this one). It is being tested under the app's page `SdImgGalleryPgComponent`, which links a gallery with the annotator.

As for this project, I followed the same directions of the working test project. I recap them here:

- the installed packages:

```bash
npm i @recogito/annotorious-openseadragon
npm i openseadragon
npm i @types/openseadragon --save-dev
```

- the style imported in `angular.json`:

```json
"styles": [
	// ...
	"node_modules/@recogito/annotorious/dist/annotorious.min.css",
]
```

- the imports:

```ts
// @ts-ignore
import * as OSDAnnotorious from '@recogito/annotorious-openseadragon';
import { Viewer } from 'openseadragon';
```

- the viewer creation:

```ts
const viewer = this._ngZone.runOutsideAngular(() => {
  return new Viewer({
    element: this.el.nativeElement,
    tileSources: {
      type: 'image',
      url: this.source,
    },
    prefixUrl: 'http://openseadragon.github.io/openseadragon/images/',
  });
});

// note this is without "new"
this._ann = OSDAnnotorious(viewer, cfg);
```

- the app has this in its `styles.css`:

```css
.openseadragon-container {
  min-height: 500px;
}
```

## What I Tried

- the annotator here is inside a material tab; I tried to take it out to exclude issues connected with component visibility, but the error persists.
- I've updated `@recogito/annotorious*` to 2.7.10 from 2.7.9 but the error persists.

**Comment by rsimon** [comment]
If anyone is still listening on this issue: the next major release of Annotorious is getting closer to release-ready. It's a complete re-write, and I believe that it will make integration with different frameworks __much__ easier.

As of now, v3 has practically no documentation, and it doesn't have feature parity with v2.7. (Most importantly, it's headless mode only for now.) But if anyone wants to look: I believe it will solve a lot of the tedious interoperability issues that you are facing.

As written above, I'm not an Angular person. Which means I can still not give any advice. But if you look at how integration is done for React and Svelte, you might find some inspiration on how to do it for Angular.

- v3 is now [a separate branch in this repository](https://github.com/annotorious/annotorious/tree/3.x). Minimal documentation is in the Readme.
- For reference & inspiration: the `@annotorious/react` bindings module [is here](https://github.com/annotorious/annotorious/tree/3.x/packages/annotorious-react).
- The `@annotorious/svelte` bindings [are here](https://github.com/annotorious/annotorious/tree/3.x/packages/annotorious-svelte)

**Comment by rsimon** [comment]
Closing this, since there will not be Angular support for Annotorious v2.x.

Meanwhile, Annotorious v3 is available. Anyone interested in contributing to a potential future `@annotorious/angular` package, drop a line on this issue: https://github.com/annotorious/annotorious/issues/296
