### ISSUE TITLE
Combining Web- with Image-Annotation Demo Broken

### ISSUE THREAD

**Issue by dennisgaebel** [annotorious/annotorious#28]
Nothing works for the demo: Combining Web- with Image-Annotation (http://annotorious.github.io/demos/okfn-plugout.html)

![Screenshot 2020-06-08 13 59 58](https://user-images.githubusercontent.com/13485205/84064275-5aaea080-a990-11ea-89e9-c9c6dd8dfc1c.png)
**Console Report on Chrome Version 81.0.4044.138  Mac Catalina 10.15.3**

**Comment by rsimon** [comment]
Sorry, the „old“ Annotorious you are referring to is no longer supported. This is the repository for a re-edition which is a complete rewrite and has (technically) nothing to do with it any more. 

Please refer to the [docs and examples for this project](https://github.com/recogito/annotorious) for installation instructions. 

I hope the re-edition in this repository is helpful to you. If you are looking for integration with the Annotator text annotation library specifically: I‘m afraid l‘m not planning to support this any more.

**Comment by dennisgaebel** [comment]
@rsimon doh! my bad. What about a demo that shows the example I posted above cause there isn't one ATM for the new work you have here https://recogito.github.io/annotorious/. Just a thought cause the current one only lets u annotate an image not text or anything like that. 🍻

**Comment by rsimon** [comment]
Hm, good point. Well, text annotation is something that Annotorious sister project [RecogitoJS](https://github.com/recogito/recogito-js) can handle. Like, previously, Annotator, they are separate things but could be used in combination.

Maybe that's a case for a new [Guide on the website](https://recogito.github.io/site/guides/). I'll put it on the list.

**Comment by dennisgaebel** [comment]
@rsimon Def worth the trouble. Also FWIW I had no clue about RecogitoJS. Where did I miss that? Might be another great idea to note this other project for text annotation here cause I will bet most have no clue it exists just like me

**Comment by dennisgaebel** [comment]
oh also would be good to put this URL https://recogito.github.io/site/annotorious somewhere in your README so others know it exists too cause it has some helpful info to guide people

**Comment by rsimon** [comment]
Yep, don't worry. That's all coming. The Annotorious website's basically up since yesterday ;-) RecogitoJS website is coming, too. But that's not even started yet :-)

**Comment by dennisgaebel** [comment]
@rsimon Awesome. Very cool! I have another Q for you that I might as well ask here vs. jamming up things and making another issue. We have clients that still support IE11, and both the text and image annotation demos don't work in IE11. What would it take to support IE11? Appreciate your time with me so far 🍻

**Comment by rsimon** [comment]
I think it’s mostly about debugging which JS features are causing the problems, and then adding the right polyfills. I did this for Edge recently,  but then didn’t go further back to IE. (In the case of Edge, it was only the `matches` and `closest` methods on the DOM elements.)

If you find out what‘s missing for IE, do let me know - or do send a pull request :-) If you add more polyfills [here](https://github.com/recogito/recogito-client-core/blob/master/src/utils/index.js#L56-L75) they‘ll be available to both Annotorious, the OpenSeadragon plugin and RecogitoJS.
