### ISSUE TITLE
Draw Rectangle and Get inside of small rectangle data

### ISSUE THREAD

**Issue by Karthik-code1010** [annotorious/annotorious#281]
![image](https://user-images.githubusercontent.com/97900968/231125884-4ec95924-034c-408b-8ec1-8b4ae58aa088.png)

I draw big rectangle inside small rectangle is there.  if I click big rectangle then I need to small rectangle info and highlight color. How to get?

**Comment by rsimon** [comment]
I'm not sure I understand your question. When clicking, Annotorious will always select the smallest rectangle. Do you mean you want to click the large rectangle, but in some way also select the small rectangles inside? Multi-selection is currently not possible in Annotorious, I'm afraid. But it will be possible in the next major release (version 3).

**Comment by Karthik-code1010** [comment]
I need Multi-selection, Its ok, thank you so mush.
