### ISSUE TITLE
Date and time in the comments

### ISSUE THREAD

**Issue by atilara** [annotorious/annotorious#284]
What would be the best way to store and show date and time in the comments of an annotation? Would I have to create a widget for it? 

I'm using NextJS and couldn't get the custom widgets to work out properly, the problems I had were discribed in this issue #202 

I tried adding the date and time as a string at the end of a comment but it's not really practical

**Comment by rsimon** [comment]
Sorry for the late reply. By now you might have figured it out yourself already (or given up ;-). Date and time are stored in the annotation and displayed automatically __if you have a user set__. See here:

https://annotorious.github.io/api-docs/annotorious/#setauthinfo
