### ISSUE TITLE
OpenSeadragon + Annotorious, Zoom Out cause specifically shape rect not able to draw when click on the canvas

### ISSUE THREAD

**Issue by rainyday321** [annotorious/annotorious#285]
Hi Guys, I recently encounter an issue with openseadragon + Annotorious, when i zoomOut and click on canvas in drawing mode, ```setDrawingEnabled(true); setDrawingTool('rect')```. I  unable to draw annotation anymore, even if reselect the rect shape, it only happen to 'rect' but freehand doesnt have this kind of issue and zoomIn does not have issue. This is my simplify version of code below:
```
<script>
function handleZoom (type , viewer) {
  const zoomRatio = type == 'zoomIn' ? 1.2 : 0.8
  viewer.viewport.zoomBy(zoomRatio , undefined , true)
} 
const viewer = OpenSeadragon({
  id : 'openseadragon',
  minZoomRatio : 0.25,
  maxZoomRator : 5,
  tileSource: {
    type : 'image',
    url : base64String
  },
   showHomeControl: false,
   showZoomControl: false
})
 const anno = Annotorious(viewer, {widgets : ['TAG']})

 const handleToolbarClick = (type) => {
   if (store.$state.selectorType === 'zoomIn' || store.$state.selectorType == 'zoomOut') {
    handleZoom(type , viewer)
   }
   else if (store.$state.selectorType == 'rect') {
     viewer.setMouseEnabled(false)
     viewer.setControlsEnabled(false)
     viewer.setDrawingEnabled(true)
     viewer.setDrawingTool('rect')
  }
 } 
</script>
<template>
  <EditorToolbar @change="handleToolbarClick"/>
</template>
```
Does anyone encouter this issues before?

**Comment by rainyday321** [comment]
forget to mention both annotorious and openseadragon is version 2.7.10

**Comment by rsimon** [comment]
Closing this as `won't fix` in Annotorious v2.x. Meanwhile, Annotorious v3 is available, which doesn't have this issue.
