### ISSUE TITLE
Pixel coordinates come through as floats in selector

### ISSUE THREAD

**Issue by mindok** [annotorious/annotorious#286]
Under certain circumstances, pixel coordinates come through as floats rather than integers.

This appears to happen when annotating large images (e.g. 4000 x 16000) that are scaled down (e.g. to 10-15%) to view (e.g. using width & height style attributes of the containing div).

An example value returned is: "xywh=pixel:470.0401916503906,11261.099609375,360.0351867675781,1240.12109375"

According to section 4.2.2 of https://www.w3.org/TR/media-frags/, integers are expected.

I'm happy to submit a PR to fix. I would be inclined to cast to integer at the top of `toPixelRectFragment` and `toPercentRectFragment` to avoid any premature rounding errors.

**Comment by rsimon** [comment]
Hi, ah - I actually wasn't even aware the spec mandated integer values. Hm, I know there are some implementations that actually use floating point numbers. (Including one of my own.) So I'd definitely have to keep that in there for pragmatic & backwards-compatibility reasons. Maybe that's something that could be tied to a new initialization parameter, `allowFloatingPointCoordinates` or something like that.

**Comment by mindok** [comment]
…or not worry about it! I only picked it up because I had a parse error server side - easy enough to fix and thought I’d raise it here in case you were particular about conforming to spec. I can understand integer for pixel coords, but I’m not sure the spec makes sense for percentage coords anyway tbh.
