### ISSUE TITLE
tag are exceeding the given div area, it should move to next line if it exceeding the div.

### ISSUE THREAD

**Issue by kallaguntaashok** [annotorious/annotorious#287]
![image](https://github.com/annotorious/annotorious/assets/26366259/183cc317-62ff-4559-a3db-23954dfea273)

tag are exceeding the given div area, it should move to next line if it exceeding the div, also I would like to check, is it possible to use dropdown in keyword area place

**Comment by rsimon** [comment]
Closing this as `won't fix`. The old popup from v2.x is no longer maintained.

Meanwhile, Annotorious v3 is available, and the recommended - much more flexible - approach is to build your own popups using the helper components (e.g. [for React](https://annotorious.dev/react/custom-popups/)).
