### ISSUE TITLE
When disableEditor: true Drawing can't be done followed

### ISSUE THREAD

**Issue by DiegoTejadaOrea** [annotorious/annotorious#288]
Hi, I'm currently working with Annotorious and Open Seadragon in version 2.10.7. When I set 'disableEditor: true', I am unable to continue drawing. However, if I set 'anno.setDrawingEnabled(true);', I have to draw twice in order for the drawing to appear on the image. I would like to be able to draw multiple rectangles without interruption (without the popup of the editor). Here is an example code:

```javascript
window.onload = function () {
      var viewer = OpenSeadragon({
        id: "openseadragon",
        prefixUrl: "openseadragon/images/",
        tileSources: {
          type: "image",
          url: "1280px-Hallstatt.jpg"
        },
        showRotationControl: true,
        showFlipControl: false,
        constrainDuringPan: true,
      });

      var anno = OpenSeadragon.Annotorious(viewer, {
        locale: 'auto',
        drawOnSingleClick: false,
        allowEmpty: true,
        crosshair: false,
        disableEditor: true,
      });

      var toolToggle = document.getElementById('current-tool');
      toolToggle.addEventListener('click', function () {
        if (toolToggle.innerHTML == 'TOOL: RECTANGLE') {
          toolToggle.innerHTML = 'TOOL: POLYGON';
          anno.setDrawingTool('polygon');
        } else {
          toolToggle.innerHTML = 'TOOL: RECTANGLE';
          anno.setDrawingTool('rect');
        }
      });

      var modeBtn = document.getElementById('mode');
      modeBtn.addEventListener('click', function () {
        if (modeBtn.innerHTML == 'MODE: VIEW') {
          modeBtn.innerHTML = 'MODE: ANNOTATE';
          anno.setDrawingEnabled(true);
        } else {
          modeBtn.innerHTML = 'MODE: VIEW';
          anno.setDrawingEnabled(false);
        }
      });
    }
```

https://github.com/annotorious/annotorious/assets/113596969/dabf2295-b36d-4027-b5b9-5d634894d921

**Comment by rsimon** [comment]
Sorry for the late reply. By now you might have figured out a workaround already (or given up ;-). You'd need to write your own logic for that. The trick is to simply listen to the annotation create events, and then programmatically switch drawing back on. (Default behavior is always that Annotorious will switch back to image nav mode. With the given workaround, you're preventing that.)
