### ISSUE TITLE
Annotations are not responsive

### ISSUE THREAD

**Issue by Deepakverma18** [annotorious/annotorious#290]
Hello everyone, I was trying to annotate on different screen size, so when I annotated and tried developer tool for responsiveness annotations were not properly aligned as annotated.
It's working fine when trying on original image i.e. without any styling but when giving some height width it's start giving wrong annotations positioning.

**Comment by rsimon** [comment]
Did you try the hints listed here:

https://annotorious.github.io/getting-started/

under "A Note on Styled Images"? This can help in some cases.

**Comment by Deepakverma18** [comment]
> Did you try the hints listed here:
> 
> https://annotorious.github.io/getting-started/
> 
> under "A Note on Styled Images"? This can help in some cases.

Yes, I have seen that that's why I have written it's working fine on original image. But if I want to style image like give some height and width to image then annotations are not aligned properly what is issue in this and how can we fix that.

**Comment by rsimon** [comment]
As the __Note on Styled Images__ says: it does not work if you apply width and height to the image. The only workaround is to wrap the image in a container, and apply width/height to the container instead.

**Comment by Deepakverma18** [comment]
Okay, Thanks will try

**Comment by Deepakverma18** [comment]
So, I tried by wrapping image inside div container and giving style on div but suppose if image size is greater than div container size than it will overflow container.
My usecase is that I have carausel user selects image and annotate, image can be of different size and these annotations are saved in database and fetched on another page. So on current page images of different size will lead to bad user experience as we are putting images inside container and styling on container.

**Comment by rsimon** [comment]
I don't know what your exact markup structure looks like. But normally you can give `position: relative` to the container and set  `width` and `height` of the image to 100%. That has worked in other cases.

**Comment by rsimon** [comment]
Closing due to >3 months inactivity.
