### ISSUE TITLE
Annotorious 3: write a basic 'Getting Started' guide

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious#298]
> __Important__ this issue is about Annotorious v3, which is currently [a separate branch in this repository](https://github.com/annotorious/annotorious/tree/3.x). 

Annotorious is about to get a new major release. Annotorious 3 is a complete re-write, and will fix many of the issues that people had with the previous version. At the moment, however, it is almost completely undocumented. If anyone wants to help with testing & documentation, that would be amazing.

__Task:__ make a test installation, test the minimal project setup, and document the "Getting Started" steps for Annotorious 3. Ideally as a markdown page in the `docs` folder. Ping me if you want to help!

**Comment by JamMaster1999** [comment]
Hello I would be happy to help if that is something you still need. @rsimon

**Comment by rsimon** [comment]
That would be great! ❤️

**Comment by JamMaster1999** [comment]
Ok great, can you tell me which brand is for Version 3.0? I'm quite confused about that haha. Is it the main branch? I assume you want the installation docs to be formatted the same as Version 2.0?

**Comment by rsimon** [comment]
Hi, yes, v3 is now the main branch. (The old version keeps living on in the [2.x](https://github.com/annotorious/annotorious/tree/2.x) branch)

In terms of formatting: don't bother about it too much. I'm likely going to re-design the site eventually. Any documentation will be fine as long as it's a Markdown document. My suggestion would be to simply fork this repo, and create a new `.md` page in the `docs/` folder. Eventually, all will go on the proper website. But for now, the `docs/` folder is going to be the starting point for the new documentation.

**Comment by JamMaster1999** [comment]
Sounds good. I am quite busy at work this week and its my birthday this weekend so I can start working on it later next week. I would also be happy to help with the website redesign when the time comes if you like my work. You can see my latest work here: [uflo.io](url)

**Comment by rsimon** [comment]
Happy birthday :-)

**Comment by rsimon** [comment]
This is now in progress, via the upcoming [project website](https://github.com/annotorious/annotorious-website). Preview version available at https://new.annotorious.com.
