### ISSUE TITLE
Annotorious 3: write a basic 'Getting Started' guide for React

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious#299]
> __Important__ this issue is about Annotorious v3, which is currently [a separate branch in this repository](https://github.com/annotorious/annotorious/tree/3.x). 

Annotorious is about to get a new major release. Annotorious 3 is a complete re-write, and will fix many of the issues that people had with the previous version. In particular, __it will simplify integration with different JavaScript frameworks__.

At the moment, however, Annotorious 3 is almost completely undocumented. If anyone wants to help with testing & documentation, that would be amazing.

__Task:__ make a test installation, set up a minimal React starter project, and document the "Getting Started" steps. Ideally as a markdown page in the `docs` folder. Since there is no documentation yet, you will have to dig into the code a little. You can use the test example as a starting point:

https://github.com/annotorious/annotorious/tree/3.x/packages/annotorious-react/test

**Comment by BrunoWinck** [comment]
I can try to work on this one

**Comment by rsimon** [comment]
That would be fantastic, thanks!

**Comment by rsimon** [comment]
By the way: a small conversation about the new React binding module has developed here:
https://github.com/annotorious/annotorious/issues/202#issuecomment-1740647465

It includes some basic pointers on where & how to get started.

**Comment by akash0708** [comment]
Hello, are you guys participating in Hacktoberfest 2023?

**Comment by rsimon** [comment]
Yes, participating in Hacktoberfest 2023 👍

**Comment by rsimon** [comment]
I'm starting this here:
https://github.com/annotorious/annotorious/blob/main/docs/react/image-annotator.md

**Comment by rsimon** [comment]
Now in progress via the new [project website](https://github.com/annotorious/annotorious-website) (sneak preview at https://new.annotorious.com).
