### ISSUE TITLE
Error: <svg> attribute viewbox: Expected number, ...

### ISSUE THREAD

**Issue by dosstx** [annotorious/annotorious#30]
I am using VueJS to create a single page app. I get the following console error (Chrome and Edge, haven't tried other browsers):

![image](https://user-images.githubusercontent.com/6342102/85393799-3536a080-b513-11ea-89f0-b34cbe340a8f.png)

Here's my code:
script section: 
`mounted() {
      const anno = new Annotorious({
        image: this.photo.id
      })
      // Attach listeners to handle annotation events
      anno.on('createAnnotation', function(annotation) {
        console.log('Created!', annotation)
      })`

template section:
`<img :src="photo.url" :id="photo.id" :alt="photo.title" />`

I should mention that it does work, it's just that I get that console error. It's possible that the DOM hasn't been fully rendered. Here's the debug info:

![image](https://user-images.githubusercontent.com/6342102/85393974-7f1f8680-b513-11ea-8d30-9438af462997.png)

**Comment by dosstx** [comment]
I solved it. It was the way I was handling Vue 's lifecycle hooks.

**Comment by rsimon** [comment]
Hi, yes I was about to say that it's almost certainly due to the image not actually being loaded when you instantiate Annotorious. (The reason it works is, probably, because Annotorious automatically attaches an .onload listener on unloaded images and defers the init internally.) 

Since you got it working: it would be __fantastic__ if you could share some notes or example code for using Annotorious with VueJS. I'd happy if I could include that as a [guide on the website](https://recogito.github.io/guides/) - obviously, all with proper attribution and everything. (No need to provide polished text or anything. I can handle editing etc.) Do let me know if you'd be open to doing that.

**Comment by dosstx** [comment]
@rsimon I will definitely submit something for you as a thanks for making this wonderful library. I am actually using VueJS with Firebase and your Firebase guide was timely. VueJS + Firebase is such a wonderful pairing.

**Comment by gbrits** [comment]
Here's my simple Vue implementation if it helps others:

`annotorious-tool.vue`
```
<template>
    <div>
        <img id="plan" src="img.png" style="width: 100%; max-width: 1024px; border: 1px solid #ccc" />
    </div>
</template>

<script>
    import {
        Annotorious
    } from '@recogito/annotorious';
    import '@recogito/annotorious/dist/annotorious.min.css';
    export default {
        data() {
            return {
                anno: null
            }
        },
        methods: {
            initAnno() {
                this.anno = new Annotorious({
                    image: document.getElementById("plan")
                });

                this.anno.on('createAnnotation', function (annotation) {
                    console.log('Created annotation', annotation);
                });

                this.anno.on('createSelection', function (selection) {
                    console.log('Created selection', selection);
                });

                this.anno.on('deleteAnnotation', function (annotation) {
                    console.log('Delete annotation', selection);
                });

                this.anno.on('mouseEnterAnnotation', function (annotation, element) {
                    console.log('Mouse ENTERED annotation', annotation);
                });

                this.anno.on('selectAnnotation', function (annotation, element) {
                    console.log('Select annotation', annotation);
                });

                this.anno.on('cancelSelected', function (selection) {
                    console.log('UNSELECTED');
                });

                this.anno.on('clickAnnotation', function (annotation, element) {
                    console.log('Clicked annotation', annotation);
                });
            }
        },
        mounted() {
            this.initAnno();
        },
    }

</script>
```

**Comment by rsimon** [comment]
Thanks that's excellent 🙏 I'll add that to the project website as a guide if I may!

**Comment by rsimon** [comment]
Vue example now on the website [here](https://recogito.github.io/guides/annotorious-in-vue/).
