### ISSUE TITLE
Annotorious 3: migration from Svelte v3 to v4

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious#300]
> __Important__ this issue is about Annotorious v3, which is currently [a separate branch in this repository](https://github.com/annotorious/annotorious/tree/3.x). 

Annotorious 3 is still using Svelte v3 (currently v3.59.2). I think it would not take much to migrate to v4. (There might not even be a single change in the code needed!)

This - hopefully - needs only:
-  upgrading of the dependencies
-  a proper test run (`npm install`, `npm test`, `npm run build`, `npm start` and manual testing in the different packages)
- a quick feedback report with some screenshots ideally

**Comment by Tholkappiar** [comment]
Hello maintainers ! I updated the **Svelte to the latest version (Svelte  4.2.1 )** and also **svelte-preprocess , vite-plugin-svelte** because of the Compatibility Issues while updating the Svelte to the latest version .

Here are the Screenshots of **Test Cases** updating the Svelte , svelte-preprocess and vite-plugin-svelte and also the **Files which are changed** by me  : 

![Screenshot (77)](https://github.com/annotorious/annotorious/assets/114584730/abafa3ed-2649-405b-bda7-f50acf57cc1a)
![Screenshot (76)](https://github.com/annotorious/annotorious/assets/114584730/1af0e7a1-1acb-42bc-9de8-2c228ddd68f1)

I have done My changes . I wanted to let you know that I am open to making any necessary changes or improvements according to your suggestions. Please feel free to provide any feedback you may have.

Thank you for your time and consideration. I look forward to hearing from you soon.

Best regards,
Tholkappiar

**Comment by rsimon** [comment]
Wow - this is fantastic, thanks so much! Did `npm run build` also run through? 

Either way: can you make a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork), so I can review & merge those changes? (I'll also apply the `hacktoberfest-accepted` in that case, so your contribution counts towards Hacktoberfest.)

**Comment by Tholkappiar** [comment]
Hiii , yeah the test are good , but yeah the build and when i start the things inside the individual things i some error , need to fix the things , it need some time for that .

These are the issues , I have to go through the things for ref and documentation coz I am a beginner on this actually , here are the ss : 

When i start the server into the individual folder like annotorious folder inside the packages : 

![Screenshot (78)](https://github.com/annotorious/annotorious/assets/114584730/c6cf5af7-d1f4-4315-b448-1ddf63ec473e)

this is build the project from the root repo : 

![Screenshot (79)](https://github.com/annotorious/annotorious/assets/114584730/ac887f40-db2a-4dbd-8d83-8c9d2cb03bc0)

I think coz I have updated the dependencies , maybe some syntax issues ! got to look into this ! Any ideas or Solutions are really appreciable according to this . Thank you for the valuable time and response !

Best regards,
Tholkappiar

**Comment by rsimon** [comment]
No worries - thanks for taking the time to look into this!

Hm, those errors do look weird. Nothing I can explain off the top of my head. But the "Unexpected Token" error (first screenshot) definitely looks like the build can't handle TypeScript syntax. Which would mean something is not working with `svelte-preprocess`. (That's the plugin that would normally do TS compilation, if I understand correctly.)

The other errors (second screenshot) look like follow-up errors. Packages like `@annotorious/openseadragon` or `@annotorious/react` depend on `@annotorious/annotorious` being built first. But because of the first error, that doesn't happen. And then the next build steps will fail. I.e. I believe the TypeScript/svelte-preprocess issue is the only real error here. Everything else just fails as a consequence of that.

**Comment by rsimon** [comment]
Argh - sorry, I just noticed a bug that I introduced. It looks like Svelte 3 didn't care, so this never crashed. But Svelte 4 may! The problem is the following: .svelte files that use TypeScript must have the following in their script tag:

```
<script lang="ts">
  // ...
</script>
```

I just realized that I broke some files. Instead of `lang="ts"` I had `type="ts"` - which is wrong. I can also see that this is the case for the file shown in your error!

Once you fix everything to `lang="ts"`, the build will probably work!

**Comment by Tholkappiar** [comment]
Hey Thanks you very much ! Those errors get resolved 👍....
Here are the new things which came up after that and also **i fixed some** ,


I got this error on the **import statements** , then i searched for the **export thing** which is in the `C:\Users\Thols\Desktop\Sample\annotorious\packages\annotorious-openseadragon\src\Annotorious.ts`
and then changed the import 
![Screenshot (80)](https://github.com/annotorious/annotorious/assets/114584730/8077bbbd-573d-4586-8cc2-198315b954a7)
changed the import from  from `'@annotorious/openseadragon';` to `import { createOSDAnnotator } from '../../../annotorious-openseadragon/src/Annotorious';` then the issue get resolved then i have only the below issues 

 The error message indicates that there's an issue with the argument  passing to `annotationLayer.$set({ tool: t })`. Could you help me here below ! and also **please make sure and reply that i have done the right thing above ! ( that import things )**

![Screenshot (81)](https://github.com/annotorious/annotorious/assets/114584730/143550a2-ce90-4621-a4ce-6025dd8d1daf)
![Screenshot (82)](https://github.com/annotorious/annotorious/assets/114584730/e843cde1-e2b4-452f-bf32-85dd07fbaa2c)

Best regards,
Tholkappiar

**Comment by rsimon** [comment]
For the first issue. Hm, no, that's not right. Other things are likely going to break if you don't import from the `@annotorious/openseadragon` package. It's weird though that this might break as a consequence of changing the package versions. Can you try deleting all the various `node_modules` folders and package.lock files, and then re-running a clean `npm install` + `npm run build`, from the root of the repository?

**Comment by rsimon** [comment]
I can see what the problem is with the second thing (`annotationLayer.$set({ tool: t })`). It some weird TypeScript issue I couldn't get rid of. (I certainly don't understand it...) This is, I believe, a rare case where using `@ts-ignore` to let the TS compiler skip over it is in order. See here for the fix:

https://github.com/annotorious/annotorious/blob/3.x/packages/annotorious-openseadragon/src/Annotorious.ts#L143-L148
