### ISSUE TITLE
Annotorious 3: write a basic 'Getting Started' guide for Svelte

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious#303]
> __Important__ this issue is about Annotorious v3, which is currently [a separate branch in this repository](https://github.com/annotorious/annotorious/tree/3.x). 

Annotorious is about to get a new major release. Annotorious 3 is a complete re-write, and will fix many of the issues that people had with the previous version. In particular, __it will simplify integration with different JavaScript frameworks__.

At the moment, however, Annotorious 3 is almost completely undocumented. If anyone wants to help with testing & documentation, that would be amazing.

__Task:__ make a test installation, set up a minimal Svelte starter project, and document the "Getting Started" steps. Ideally as a markdown page in the `docs` folder. Since there is no documentation yet, you will have to dig into the code a little. The Svelte integration package is here:

https://github.com/annotorious/annotorious/tree/3.x/packages/annotorious-svelte

**Comment by KennySmash** [comment]
Hey rsimon, its been some time since I've stopped around. 
really glad to see v3 is progressing great.  
I'd be happy to give this and the vue docs a go with the aim of completing them end of feb

**Comment by rsimon** [comment]
That would be excellent, thank so much! FWIW: there's no Vue integration yet. I'm hoping that someone would make first steps towards this :-) If you want, feel free to fork the repo, create an `annotorious-vue` module - and start hacking :-)

**Comment by KennySmash** [comment]
I'll have to take some time to familiarise myself with the v3 architecture but the fact that I've done it for v2 already should help a lot

**Comment by rsimon** [comment]
I'll try to prepare some basic v3 documentation (for vanilla JS and React) soon-ish. This should also help, hopefully.

**Comment by rsimon** [comment]
Also closing this, since it's underway as part of the new website. See e.g.:
https://new.annotorious.com/svelte/openseadragon
