### ISSUE TITLE
use as esm module

### ISSUE THREAD

**Issue by atomotic** [annotorious/annotorious#308]
Can annotorious3 be usable as an esm module, without a build system ([#nobuild](https://world.hey.com/dhh/you-can-t-get-faster-than-no-build-7a44131c)) ?
I've started playing with it https://github.com/atomotic/annotorious3-osd-test but I'm missing some pieces, outcome here https://atomotic.github.io/annotorious3-osd-test/

**Comment by rsimon** [comment]
Yes, that should work just fine. 

The issue (sorry for that) is unrelated. You need to add the following init option to OpenSeadragon:

```js
crossOriginPolicy: 'Anonymous'
```

The reason is that Annotorious samples pixels on the canvas to determine whether it should use a light or dark overlay theme. This will be an optional feature in the future, but is currently hard-wired.

**Comment by atomotic** [comment]
Thanks! I've added `crossOriginPolicy` and used almost the same [test page](https://github.com/annotorious/annotorious/blob/3.x/packages/annotorious-openseadragon/test/index.html) from annotorious-openseadragon package, however the annotation drawer is not visibile.

On another note, I'd like to share my intended use case for Anno3: I'm working on revamping  https://iiif.link, a simple tool to get a permalink for a IIIF image region. Now it supports only IIIF presentation v2 manifests, and the region is selected with zoom+pan.
Wanted to rewrite and use annotorious for region selection: basically a single annotation on a canvas that get a permalink. I have a wip here https://dev.iiif.link/ (the save functionality has not been implemented yet)

**Comment by rsimon** [comment]
It looks like you didn't import the Annotorious stylesheet: `import '@annotorious/openseadragon/annotorious-openseadragon.css`.

That use case sounds great, BTW!

**Comment by atomotic** [comment]
ouch! thanks, I hadn't noticed it at all. works now: https://atomotic.github.io/annotorious3-osd-test/

**Comment by rsimon** [comment]
You might want to remove the dummy formatter though ;-) 

Anyways, good to  see it's working!
