### ISSUE TITLE
(UX) When adding tag, don't require pressing Enter to save tag

### ISSUE THREAD

**Issue by dosstx** [annotorious/annotorious#31]
In Microsoft Edge, I can add a tag , however, the tag is not saved unless you press Enter on the keyboard. Can we make it so if the user also clicks elsewhere in the annotation UI the tag will also be saved? Sometimes I will forget to press Enter when adding tags.

**Comment by rsimon** [comment]
Ah, indeed - actually a "know issue", as it were. But one that didn't have a ticket on the issue tracker yet. Yes, definitely possible - I'm putting it on the prio list.

**Comment by rsimon** [comment]
Relevant code for this is issue is in [recogito-client-core](https://github.com/recogito/recogito-client-core). Issue was just fixed in this commit:

https://github.com/recogito/recogito-client-core/commit/4373abf54b48ba22992db934afb58067e43c5472
