### ISSUE TITLE
I can't set up the basic 

### ISSUE THREAD

**Issue by the-yaz** [annotorious/annotorious#310]
I did install annotorious from the [githab ](https://github.com/annotorious/annotorious/releases/tag/v2.7.12)and created a html file and copy the code on [documentation](https://annotorious.github.io/getting-started/), but nothing happened it just show the image without annotorious , I don't know what I'm missing.
here is my code 
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="annotorious.min.css">
      </head>
      
      <body>
        <div id="content">
          <img id="hallstatt" src="640px-Hallstatt.jpg">
        </div>
        <script>
          (function() {
            var anno = Annotorious.init({
              image: 'hallstatt' // image element or ID
            });
      
            anno.loadAnnotations('annotations.w3c.json');
      
            // Add event handlers using .on  
            anno.on('createAnnotation', function(annotation) {
              // Do something
            });
          })()
        </script>
      
        <script type="text/javascript" src="annotorious.min.js"></script>
        <script type="text/javascript" src="annotorious.umd.js.map"></script>
        <script type="text/javascript" src="recogito-polyfills.js"></script>
      </body>
</html>
```
and you can see here that i have all the files in the same directory: 
```
Directory of C:\Users\YCH\Desktop\test_annotation

03/11/2023  12:42    <DIR>          .
03/11/2023  12:42    <DIR>          ..
03/11/2023  12:41             7 368 640px-Hallstatt.jpg
03/11/2023  14:18            10 311 annotorious.min.css
03/11/2023  12:52           286 326 annotorious.min.js
03/11/2023  12:36         1 055 483 annotorious.umd.js.map
03/11/2023  14:16               937 index.html
03/11/2023  12:36           161 729 recogito-polyfills.js
```

**Comment by rsimon** [comment]
Hi, is the error console showing anything?

My suspicion is that you are running the page simply by double-clicking the HTML file. Browsers, by design, will refuse to load external JSON content when a page is served from file://. Your example likely breaks at this line:

```
anno.loadAnnotations('annotations.w3c.json');
```

If your remove that line, you should get a working (but empty) annotation layer.

**Comment by the-yaz** [comment]
thank you so much ,you were right the json file was the problem , but when i run the project with live server from visual code it works even with `anno.loadAnnotations('annotations.w3c.json');` . thank you again for your help
