### ISSUE TITLE
getter and setter methods for widget do not appear to be working for me in annotorious-osd 2.712

### ISSUE THREAD

**Issue by ohsofoxy273** [annotorious/annotorious#314]
The getter and setter methods for "widget" do not appear to be working for me.

I am using @recogito/annotorious-openseadragon 2.7.12. 

In my typescript file, I am importing the openseadragon-annotorious.min.js as:` import Annotorious from '@recogito/annotorious-openseadragon';`

I initialize OSD:
```
const viewer = OpenSeadragon({
    ...
  });
```
Then create an annotationsManager:
`const annotationsManager = Annotorious(viewer, {});`

The class OSDAnnotorious has getters and setters for widgets:
```
get widgets() {
    return this._app.current.widgets;
  }

  set widgets(widgets) {
    this._app.current.widgets = widgets;
  }
```
 Other methods are available and working fine, eg. "on", "loadAnnotations" etc. They are also viewable when console logging the annotationsManager._app.current

`annotationsManager.widgets` prints _undefined_. 

This code -
```
annotationsManager.widgets = [
    { widget: 'COMMENT' },
    { widget: 'TAG' },
  ];
```

does not update the widgets, however, I can update the widgets by directly accessing the object with 
`annotationManager._app.current.widgets = widgets`
  
my setWidgets function demonstrates this:
```
function setWidgets(annotationManager: Annotorious): void {
  const widgets = [
    { widget: 'COMMENT' },
    { widget: 'TAG' },
  ];

  console.log('Before setting widgets:', annotationManager.widgets);

  annotationManager.widgets = widgets;

  console.log('After setting widgets:', annotationManager.widgets);

  console.log(annotationManager._app.current.widgets = widgets)

  console.log('After setting widgets directly:', annotationManager.widgets);
}
```
 I'm not sure if I'm doing something silly here, or the library isn't working as intended.

**Comment by rsimon** [comment]
Widgets are actually a React state internally. That means the change happens async, with a little delay. (You can try waiting a little via a `setTimeout` to test this.) Whether you use `.widgets` directly or `.anno._app.current.widgets` should actually make a difference.

**Comment by ohsofoxy273** [comment]
Thanks, the page is getting pretty javascript heavy and I have the option of converting it to React if needed. Would you think using .anno._app.current.widgets to set the widget would also have this async delay or be buggy? I'd lean toward not using it because _app is a "protected" property, but if it works, I can live with it.

**Comment by rsimon** [comment]
I think there's no difference. Both properties  should work exactly the same way, with the same delay. The reason you're seeing a difference might be because the console.log in between causes enough delay for the React state update to complete.

**Comment by ohsofoxy273** [comment]
You are correct, they both work. It just doesn't work fast enough for the console.log, but it works for the app just fine. Closing. Thanks.
