### ISSUE TITLE
annotorious CSS Module not found

### ISSUE THREAD

**Issue by xvin-zr** [annotorious/annotorious#315]
When I'm using annotorious 3 in both React and Next.js, the CSS module can't be imported. But in `node_modules`, this CSS file does exist. 

<img width="1014" alt="image" src="https://github.com/annotorious/annotorious/assets/88776909/c3681529-6c8a-4063-9bb3-f202816e64ab">

<img width="753" alt="image" src="https://github.com/annotorious/annotorious/assets/88776909/55fccd76-cd67-401e-b0ae-ff21f8368ed8">

**Comment by rsimon** [comment]
The file path is mapped in the package config. You need to import without the 'dist', from `@annotorious/annotorious/annotorious.css`.

**Comment by rsimon** [comment]
PS: if you are using the React package, there should normally be no need for the `@annotorious/annotorious` package. You can import the CSS from `@annotorious/react/annotorious-react.css`

**Comment by rsimon** [comment]
BTW: thanks for trying out Annotorious v3. It's still in alpha mode - let me know how it goes ;-)

**Comment by xvin-zr** [comment]
It works. Thanks a lot. 😆

**Comment by rsimon** [comment]
👍  Just a quick heads up: I recently made changes to the way the drawing tools work. If you use `drawingMode: "drag"` as an init argument, not everything may work with the latest published package. (`drawingMode: "click"` should work just fine.) Either way, do shout out if anything seems broken & I can look into it.
