### ISSUE TITLE
Should all the props of the `target` except the `annotation` & `selector` get lost?

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [annotorious/annotorious#324]
## Issue Description
When the `W3CAnnotation` gets parsed into the `Annotation`, the `target` parsing is implemented exclusively in the `parseW3CImageAnnotation`. And for some reason I would like to understand, the created `target` has only 2 properties assigned: `annotation` & `selector`. But `target.styleClass`, `target.accessibility`, and `target.state` are getting lost :(
https://github.com/annotorious/annotorious/blob/4a36371ea227973d72aaf93ca79980a314b30597/packages/annotorious/src/model/w3c/W3CImageFormatAdapter.ts#L52-L55
It leads to an issue if the dev wants to parse the W3C anno and then serialize it back. Serialized anno will be only a partial copy of the one the dev passed to the `addAnnotation`.  

## Possible Solutions
Create a reusable function that will look similar to the `parseW3CBodies`, where the significant properties are transformed, but the rest of them are just forwarded as-is
https://github.com/annotorious/annotorious/blob/4a36371ea227973d72aaf93ca79980a314b30597/packages/annotorious-core/src/model/W3CAnnotation.ts#L85-L86

**Comment by rsimon** [comment]
Yes, true. Any custom properties in the `target` are currently discarded. I don't see anything that cause problems with changing this though. I guess the simplest solution would be to change the code to the following?

```js
target: { 
   ...rest.target,
   annotation: annotationId, 
   selector 
 } 
```

**Comment by oleksandr-danylchenko** [comment]
>  I don't see anything that cause problems with changing this though.

Cool 👍🏻 

Then I would like to create `parseW3CTarget`/`parseW3CTarget` that can be reused both for the `Annotorious` and `TextAnnotator` adapters. Their signature can look like:
```ts
export const parseW3CTarget = <A extends AnnotationTarget, T extends W3CAnnotationTarget>(
  target: T | T[],
  annotationId: string
  formatSelector: (selector: T['selector']) => A['selector']
): A => {
  //...Implementation
};
```
The `formatSelector` function is a mandatory arg because the selector parsing/serialization is the thing that is different between the `Annotorious` & `TextAnnotation` adapters and that logic should be injected from them. But the handling of the "properties that conform to the internal model" and "custom props" can be done in the `parseW3CTarget`. 

---

UPD: Adding that function felt pretty awkward and cumbersome. It required a ton of fidgeting to extract the `selector` from the "parsedTarget" to properly create an error. So I'll roll it back and try another time with something simpler

**Comment by oleksandr-danylchenko** [comment]
Oh... Wait a minute... Why are the `created`, `creator`, `updatedBy`, and `updated` specified on the `AnnotationTarget` and not the `Annotation` itself?...
According to the spec, only the parent annotation can have those, but not the target 🤔 
https://www.w3.org/TR/annotation-model/#lifecycle-information

**Comment by oleksandr-danylchenko** [comment]
Possibly found a caveat in the existing w3c adapter, see - https://github.com/annotorious/annotorious/issues/325#issuecomment-1855701381

**Comment by rsimon** [comment]
I made the (small) change discussed above:

```
target: { 
   ...rest.target,
   annotation: annotationId, 
   selector 
 } 
```

I'll close this issue in favor of #325 - which is about the `created`/`updated` etc. properties currently being at the wrong place in the serialized W3C model. I'll keep this high on the list, but will move it to the `3.0.0-rc.5` milestone. (I'll release RC4 later today.)
