### ISSUE TITLE
OpenSeadragon required as a peer dependency also for ImageAnnotator?

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious#329]
When using the `@annotorious/react` package, it looks like OpenSeadragon is required as a (peer? dev?) dependency. This should not be necessary, since most people will want to use the `<ImageAnnotator>` for standard images.

**Comment by ghost** [comment]
I too couldn't get the annotorious library to install via npm due to the peer dependency issue.  Any suggestions on which plugin would be great for drawing (annotating) on OSD viewer? There's the osd-select-plugin, but not sure which one is better.

**Comment by rsimon** [comment]
Hi @ShashanKV98,

I think you might be confusing things. This issue is about using Annotorious __without__ OpenSeadragon. (In this case, you shouldn't need to install `openseadragon` as a dependency. But it looks like the `@annotorious/react` package currently complains if you don't).

If your goal is to create annotations on OpenSeadragon, you will have to include the `openseadragon` package in your project. Can you post example code and/or error messages you are getting?

**Comment by ghost** [comment]
![image](https://github.com/annotorious/annotorious/assets/23161642/67af53d2-9cb6-497f-8f10-637acd14218a)

Sure, I attached a snapshot of the error message I got by running `npm install @recogito/annotorious-openseadragon`. I already have a OSD 4.1 version installed. 

On a side note, I also found annotorious-openseadragon repo on Github (I think annotorious for OSD), but looks like it doesn't have an npm package.

**Comment by rsimon** [comment]
Ok, various misunderstandings here :-) 

- This issue here is about the upcoming next release of Annotorious (3.0), specifically the React version.
- You are referring to the current (2.7.x) - which is based in the GitHub repo you mention, and is the npm package you get when installing `@recogito/annotorious-openseadragon`
- The version you are using is in fact compatible with OSD 3 to 4.1. In your case, it's safe to follow the instructions in the error message and install with the `--force` option. 

I'll make a note to fix the dependency declaration, so that the error message goes away with the next 2.7.x maintenance release.

**Comment by ghost** [comment]
Ah, sorry about the confusion. Guess I stayed a little late today than I'm used to! 
I did have a small question. I'm actually using OpenSeadragon with React and having a React version for annotorious 3.0 is exciting! I was wondering if `@recogito/annotorious-openseadragon` package would also be upgraded and have a react version of its own?

**Comment by rsimon** [comment]
Yes, the next release will change a few things in terms of how the whole project is organized. In fact, the `@annotorious/react` package will include React wrappers for both the standard and the OpenSeadragon version of Annotorious!

It's (near) ready in principle, but there's no documentation yet. I'll try to write some + set up a minimal CodeSandbox example over the next few days.

**Comment by ghost** [comment]
Awesome, thanks!

**Comment by rsimon** [comment]
Meanwhile: here's a CodeSandbox I just made, with the absolute minimum you need to get Annotorious v3 working with OpenSeadragon in React: https://codesandbox.io/p/sandbox/nifty-allen-xd65vx

**Comment by ghost** [comment]
Thank you for sharing! I also had a few questions about some customizations with this library. I'm gonna open a new issue.

**Comment by rsimon** [comment]
The original issue may not be resolvable... the "fix" is that both `openseadragon` and `@annotorious/openseadragon` are now declared [as an optional peer dependency in the package.json](https://github.com/annotorious/annotorious/blob/77deaaba085e54ec04b6bc40f9e10a9ce137160b/packages/annotorious-react/package.json#L41-L48). This will work in some bundlers (Vite) but perhaps not in others (Webpack?).

Nonetheless, I think this is as far as I can go right now. The alternative would be to build the OpenSeadragon-specific code into a sub-module, so that people could either 

```js
import { ImageAnnotator } from '@annotorious/react';
```

or 

```js
import { OpenSeadragonAnnotator } from '@annotorious/react/openseadragon;
```

I've seen [other projects do this](https://github.com/samvera-labs/clover-iiif). But it really complicates the build, and forces specific settings in `tsconfig.json` that not everyone may use. Also (I believe): the @annotorious/react/openseadragon sub-bundle won't be able to use the `<Annotorious>` context defined in @annotorious/react - which would be a showstopper.
