### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by dosstx** [annotorious/annotorious#33]
Get the following error in console:

```
annotorious.min.js?73e3:1 Uncaught TypeError: Cannot read property 'removeChild' of null
    at l.eval (annotorious.min.js?73e3:1)
    at eval (annotorious.min.js?73e3:1)
    at o.emit (annotorious.min.js?73e3:1)
    at HTMLDocument.eval (annotorious.min.js?73e3:1)
```

This happens when I do the following:

1.) Add annotation 
2.) delete annotation
3.) Click on the image (do not draw bounding box, just do a click

![image](https://user-images.githubusercontent.com/6342102/85948428-83ceab00-b916-11ea-82bf-f46eb7d8580b.png)

**Comment by rsimon** [comment]
Thanks for reporting. This is with the latest release version, right? I think this might already be fixed in the master branch. But I'll double check.

**Comment by rsimon** [comment]
Oops - that bug still existed in the master branch. Fixed now. Thx again for spotting!
