### ISSUE TITLE
Customizations with the @annotorious/react

### ISSUE THREAD

**Issue by ghost** [annotorious/annotorious#330]
Firstly, it's nice to have a package that handles both the annotations and the viewer in react. I had a few things I wanted to ask and hopefully get some directions on how to integrate them. 

1. The library has a Rectangle as its default shape. I see there's "annotorious-v2-selector-pack" library which has got other shapes too. How can I select the shape (tool) with this package using the library and perhaps even create our own shapes? 

2. Is there also a way to "erase" the created shapes? 

3. It would be great to have an even greater control over the shapes (like the css).

The docs are probably a better place for some of these. In any case, appreciate the time and effort put into this library.

**Comment by rsimon** [comment]
Some answers below: 

- v2.x extensions will __no longer be compatible with v3__. Out of the box, Annotorious 3 has rectangle and polygon tools, like the old version. In addition, there's [a new selector pack in the works](https://github.com/annotorious/annotorious-v3-extensions/tree/main/annotorious-selector-pack) which currently adds a circle/ellipse tool.
- Internally, Annotorious is written in Svelte. You could gather some inspiration [here](https://github.com/annotorious/annotorious-v3-extensions/blob/main/annotorious-selector-pack/src/ellipse/RubberbandEllipse.svelte) and [here](https://github.com/annotorious/annotorious-v3-extensions/blob/main/annotorious-selector-pack/src/ellipse/EllipseEditor.svelte) on how to write new drawing tools and shape editors, respectively.
- In React you can generally change the tool with the `<ImageAnnotator tool={tool} />` property. But  documentation is still missing. See [here for a real-world code example](https://github.com/rsimon/immarkus/blob/main/src/pages/annotate/WorkspaceSection/AnnotatableImage.tsx#L58-L81).  (This also uses the selector pack plugin, BTW.)
- There is currently no "controlled mode" for Annotorious React. You can get a reference to the `anno` object using the [useAnnotator hook](https://github.com/annotorious/annotorious/blob/3.x/packages/annotorious-react/src/Annotorious.tsx#L111-L114).
- The `anno` object offers large the same API methods like v2. You can use `anno.removeAnnotation(id)` to remove an annotation.
- You can control the annotation style via the `<ImageAnnotator style={...} />` property. The style property can either take an object of type [DrawingStyle](https://github.com/annotorious/annotorious/blob/3.x/packages/annotorious-core/src/model/DrawingStyle.ts), or a __function__ that takes an annotation as argument and returns a DrawingStyle. Note that, currently.
