### ISSUE TITLE
Horizontal and Vertical bounding box toggles 

### ISSUE THREAD

**Issue by maryghermann** [annotorious/annotorious#333]
I am using annotorious with typescript + react and was wondering if there is a way to add horizontal and vertical toggles to the bounding boxes, here is a before and after highlight the desired outcome 

Current: 
<img width="470" alt="image" src="https://github.com/annotorious/annotorious/assets/104372395/db731863-65f8-469e-964d-bcbdbd8c7d8d">

Desired:
<img width="458" alt="image" src="https://github.com/annotorious/annotorious/assets/104372395/7a6a5c4e-fe69-4295-92a4-59cdc0867832">

Ideally, these extra toggles would allow an annotator to move the bounding box only vertically/only horizontally

**Comment by rsimon** [comment]
Hi, 

that's actually available now - as an undocumented feature... Use the `enableEdgeControls` init property as shown here:
https://github.com/annotorious/annotorious/blob/37485ad258f1e7aa84f5a8d6d7a6870d449c67a5/public/index.html#L63

(P.S.: FWIW, the [upcoming v3 release of Annotorious](https://codesandbox.io/p/sandbox/fervent-thunder-xkpxvc) will have draggable edges by default, although without dot markers.)

**Comment by maryghermann** [comment]
That worked like a charm! Thanks so much for the insight there. Looking forward to the v3 release (and if openseadragon ever adds typescript and react support I will be very excited)

**Comment by rsimon** [comment]
Not sure if you mean OpenSeadragon itself or the Annotorious OpenSeadragon version. But Annotorious v3 has full TS and React support, both for normal images and OpenSeadragon ([see here for a minimal example](https://codesandbox.io/p/sandbox/nifty-allen-xd65vx)). (For OSD itself: I don't think they plan on publishing a React package. But there are TS typings available.)

**Comment by maryghermann** [comment]
That is great news about Annotorious OS supporting TS + React in v3, that'll make implementation a lot easier hopefully. I attempted recently and the added challenge of OSD not having typescript + react support made it very difficult. Thanks for linking the example as well 😄
