### ISSUE TITLE
customizing editor

### ISSUE THREAD

**Issue by SuhaibMaraqa** [annotorious/annotorious#341]
I read the documentation about customizing the editor and add the widgets, Is there a way to replace the whole editor with my own editor, like I want to write the new editor's code and just pass it's id to annotorious object to replace it with the current editor?

PS: my editor will only have a code related to my project it will just change the annotation color

Also I followed the react documentation for customizing the editor and many links are not working like this one : https://github.com/annotorious/annotorious-v2-plugins/tree/main/packages/widget-react-helloworld

Also, How to include recogito-helloworld-widget.js ? 

```
<Script src="https://cdn.jsdelivr.net/npm/@recogito/annotorious@2.7.12/dist/annotorious.min.js" />
<Script src="recogito-helloworld-widget.js" />
```

here is the code, annotorious is good but the widget return 404

**Comment by rsimon** [comment]
To replace the editor with your own, you can use [headless mode](https://annotorious.github.io/guides/headless-mode/) and interact with Annotorious through the [API methods](https://annotorious.github.io/api-docs/annotorious/).

**Comment by SuhaibMaraqa** [comment]
but how can give the editor's positioning to my own editor ?

**Comment by rsimon** [comment]
Sorry, Annotorious doesn't have any features to help with that. But you can grab a reference to the SVG DOM element of the annotation. (I believe the select event might  actually provide it as a second argument.) And then orient your popup on that. You can take a look at how the built in popup does it here: https://github.com/recogito/recogito-client-core/blob/main/src/editor/setPosition.js
