### ISSUE TITLE
Read only mode removes the mask

### ISSUE THREAD

**Issue by JamMaster1999** [annotorious/annotorious#349]
Hello and thank you for your work on annotorius. It's AWESOME! Can't wait for V3. 
I do have one small suggestion for improvement that I think is really simple to fix but would be greatly appreciated. 
Right now I have setup the library to look like this
![image](https://github.com/annotorious/annotorious/assets/46285145/aed1db45-9834-4ca3-8678-98f9a649a9f1)
But when I turn on the readOnly mode it looks like this: 
![image](https://github.com/annotorious/annotorious/assets/46285145/bbd79268-11d4-414e-a1ab-82ba946c3cb8)
IS there anyway you would be willing to add the selection mask back so everything around it gets opaque and it becomes super clear where the user should be paying attention to? I believe this is a simple change as you just have to add the `<path fill-rule="evenodd" d="...." class="a9s-selection-mask"></path>` back in when in read only mode. 

Thank you again!

**Comment by rsimon** [comment]
Thanks!

Unfortunately, it's no as easy a change. The mask is currently a sub-part of the editing tool. Which means there's extra plumbing needed to make it available separately. It's not just a matter of turning it on at least. I'm happy to take a PR around this, but will likely not have time to look into this myself.

**Comment by JamMaster1999** [comment]
@rsimon Thanks for the swift reply. Ok no worries. I have two other ways that do not require extra plumbing. Can you tell me if either of these would work at scale? 
1. Store the path in a variable mapped to the id of the annotation and update it whenever there is a change to the annotation position. Then in read-only mode, when a annotation is selected, add the path again and remove it once annotation is unselected. 
2. Come up with a third mode that combines disableEditor and readOnly. The disableEditor already contains the mask all we need to do is just add back in the annotation without any editing capabilities.

**Comment by rsimon** [comment]
Hi, 

I'm not sure about your 2nd option, TBH. This might be going down a rabbit hole of dealing with various plumbing aspects inside Annotorious. (Even I don't remember all the pathways and dirty shortcuts I might have made back then ;-) 

The first option sounds definitely feasible though. In read-only mode, there's probably not even a need to listen to annotation changes. You can just listen to the select event, which will give you the annotation & the annotation's SVG element. Grab the `points` from the SVG polygon, and create a mask element on the fly, using [this piece of code](https://github.com/annotorious/annotorious/blob/2.x/src/tools/polygon/PolygonMask.js) as a guide.

If I remember correctly, the `cancelSelected` event is always fired when the selection is closed (or changed), this would be the point where you can delete your mask element again.

FWIW: there's no mask element in Annotorious v3 yet. I'll keep it mind to add it over there, too. (Selection, editing and read-only mode work in a different way there. I.e. it would actually be easier to build a mask that works both with and without the editing tools.)
