### ISSUE TITLE
Unable to highlight shape when headless = true?

### ISSUE THREAD

**Issue by RodolfoPena** [annotorious/annotorious#35]
Hello, 
There is any way to highlight a shape when **'headless:true'**? I'm trying to use **anno.selectAnnotation(annotation)**, but this only work when headless is false.  I want to highlight a shape but hiding the editor. Thanks in advance.

**Comment by rsimon** [comment]
Yes, good point. Indeed `selectAnnotation` doesn‘t properly set the select state in headless mode. I‘ll look into it.

**Comment by rsimon** [comment]
Just added this to the master branch: selecting an annotation now adds a `selected` CSS class to the SVG shape. (The default stylesheet applies a yellow stroke color.) This now works both in normal and headless mode.
