### ISSUE TITLE
"Getting Started" for Annotorious 3.0.0-rc.17 does not work

### ISSUE THREAD

**Issue by austincollinpena** [annotorious/annotorious#350]
When referencing this code: 

```typescript
import { Annotorious } from "@annotorious/annotorious";
```

I get the error:

`TS2305: Module "@annotorious/annotorious" has no exported member Annotorious`

Which makes sense to me, because I don't see an exported "Annotorious"

**Comment by rsimon** [comment]
Hi, 

yikes. Yes, sorry - there were a lot of changes & docs haven't kept up. That's likely going to remain until the offical 3.0.0 goes out. For now: Annotorious has been replaced by `createImageAnnotator` for the standard version, or `createOSDAnnotator` for the OpenSeadragon version, respectively. See also:

- [Image annotator test page](https://github.com/annotorious/annotorious/blob/main/packages/annotorious/test/index.html)
- [OSD annotator test page](https://github.com/annotorious/annotorious/blob/main/packages/annotorious-openseadragon/test/index.html)

**Comment by austincollinpena** [comment]
Thank you!
