### ISSUE TITLE
An example of how to integrate .setAuthInfo() ?

### ISSUE THREAD

**Issue by dosstx** [annotorious/annotorious#38]
Not an issue, but can someone provide an example of how they are using the `.setAuthInfo` method? Where is a good place to put it? Within the `createAnnotation` event?

**Comment by rsimon** [comment]
Hi,

good point - I should probably improve the docs around this...

In general, you only need to set this once, when you initialize Annotorious.

```js
var anno = Annotorious.init({ image: 'my-image' });

anno.setAuthInfo({
  id: 'http://www.example.com/users/myUser',
  displayName: 'MyUserName'
});
``` 

That's it. No need to do anything in the event handlers. The auth info data is now set 'globally'. You'd only need to call `setAuthInfo` or `clearAuthInfo` again if the user login status changes in your host application.

**Comment by dosstx** [comment]
@rsimon Thank you for that info. I actually figured it out right before I saw your message. So now that I understand how that works, it makes total sense on how to use the other methods. Thanks again!

**Comment by rsimon** [comment]
Added a bit more info to the website now: https://github.com/recogito/project-website-source/commit/d212fad1afdbb7daa2da02efc782558ee065d5af
