### ISSUE TITLE
OpenSeadragon: filtering does not work after drawing an annotation

### ISSUE THREAD

**Issue by oncoml** [annotorious/annotorious#381]
Hi all, thank you for making and maintaining this awesome library.

I'm combining Annotorious-OpenSeadragon with the filtering library OpenSeadragonFiltering [https://github.com/usnistgov/OpenSeadragonFiltering](url). The filter works well by itself and the annotation works well by itself. Once an annotation is drawn and created, however, the filter stops functioning. Deleting the annotation element does not help. 

Filtering creates a canvas element that shares the same parent as the annotation svg. 

My short-term solution is to copy the viewer into another object and let Filtering apply on it. It is hacky. I'm curious to what is happening. Perhaps it's something simple that I'm missing. Besides creating <g> elements, what else does annotating do to the parent element?

I also posted the same message to the Filtering page, just to get more feedback.

Thanks in advance.

**Comment by rsimon** [comment]
Hm, I need to double-check. I don't think Annotorious interacts in any way with the original OpenSeadragon canvas. Are you using Annotorious v2.7 or already the v3? The v3 version does append a second canvas element for rendering the overlays. Depending on how the Filter plugin grabs its handle to the OSD canvas, perhaps the 2nd canvas causes confusion. Is behavior any different if you add the Filter plugin before Annotorious vs. the other way round?

**Comment by oncoml** [comment]
Thanks Rainer. I believe I'm using v3. I will try to v2.7.

Filtering first and drawing the annotation works. Post that, however, additional filtering or deleting filters fail.

**Comment by rsimon** [comment]
Do you think it would be possible to have an example online I could look at? It might help to see the DOM structure, init code and log errors if any.

**Comment by oncoml** [comment]
I appreciate your willingness to help. I figured it out (partly anyway) - I have a function that takes in tags inputed in the sidebar of the app and updates the widget's vocabulary (anno.widgets[0].vocabulary). That, for some odd reason, seems to block any further filtering from happening. Not sure why yet, maybe I'll revisit it later.

Thanks again!

**Comment by rsimon** [comment]
Ok, let me know if anything else shows up. FWIW: if you are using `anno.widgets` that means you are using v2.7 (which is currently the version I'd recommend). But if the widget you are using `anno.widgets[0].vocabulary` is the built-in tagging widget: I don't think that you could change the vocabulary just like that. I.e. that call might likely break something in the application flow more generally. Is there any log output in the browser console?
