### ISSUE TITLE
`AnnotoriousPlugin` component doesn't reapply the `plugin` on its change

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [annotorious/annotorious#382]
## Required Behavior
When the plugin you want to apply to the annotator instance depends on dynamic arguments - it'll have the next design: 
```ts
const createWebtextsPlugin = (pageId) => (anno) => {
        ...
	const _addAnnotation = store.addAnnotation.bind(store);
	store.addAnnotation = (annotation, origin) => {
		const webtextsAnnotation = ...; // Some transforms that depend on the `pageId`
		return _addAnnotation(webtextsAnnotation, origin);
	};
        ...
} 
```
And on each change of the `pageId` the `createWebtextsPlugin will return the new function that should applied to the annotator instance:
```tsx
const webtextsPlugin = useMemo(() => createWebtextsPlugin(pageFamilyId), [pageFamilyId]);
```

## Issue

Unfortunately, such an approach won't work for the current A9S setup and you'll experience a few issues:
1. The `AnnotoriousPlugin` won't react to the `webtextsPlugin` changes❗
That's  because it omits the `plugin` from the `useEffect` deps list: https://github.com/annotorious/annotorious/blob/adc3f3b793de47731119efc1a35b8c03af2beb8c/packages/annotorious-react/src/AnnotoriousPlugin.tsx#L18-L27
So even if a user changes a page they looking at - annotations will still be transformed in the context of the previous one 🤷🏻‍♂️ 
2. Even after you add the `plugin` to the deps list - the monkey patching of the store will immediately backfire. And that's because on subsequent runs, the `const _addAnnotation = store.addAnnotation.bind(store);` will be the previously mutated `addAnnotation` method instance. So you'll experience a weird double processing of the annotation: ![image](https://github.com/annotorious/annotorious/assets/68850090/aa0cd48a-3097-46f4-a61d-233715855a26)

## Possible Solutions
1. Add the `plugin` to the deps list for the `AnnotoriousPlugin` to re-apply it on change
2. Specify in the examples that after mutating the store, it should be returned to the default state in the `unmount` callback:
```ts
export const createWebtextsPlugin =
	(pageId) =>
	(anno) => {
		const store = anno.state.store;

		const _addAnnotation = store.addAnnotation.bind(store);
		store.addAnnotation = (annotation, origin) => {
			...
			return _addAnnotation(webtextsAnnotation, origin);
		};

		const _bulkAddAnnotation = store.bulkAddAnnotation.bind(store);
		store.bulkAddAnnotation = (...) => {
			...
			return _bulkAddAnnotation(webtextsAnnotations, replace, origin);
		};

		const _updateAnnotation = store.updateAnnotation.bind(store);
		store.updateAnnotation = (annotation, origin) =>
			_updateAnnotation(toWebtexts(annotation), origin);

		const _updateTarget = store.updateTarget.bind(store);
		store.updateTarget = (target, origin) =>
			_updateTarget(toWebtextsTarget(target), origin);

		return {
			unmount() {
				store.addAnnotation = _addAnnotation;
				store.bulkAddAnnotation = _bulkAddAnnotation;
				store.updateAnnotation = _updateAnnotation;
				store.updateTarget = _updateTarget;
			}
		};
	};
```
I believe that it should be the dev's responsibility to handle the re-applied plugin behavior. Because we cannot know whether they may need to use the previously mutated `_addAnnotation`

**Comment by oleksandr-danylchenko** [comment]
Oh-oh... I think this issue appeared in the 1st place because _I was using the `Annotorious` + `TextAnnotator` components in a wrong way... 👁️👁️👁️_ 

I was trying to use the same annotator instance across _mutliple pages at the same time_. I thought that I can use `filter` to display only relevant annotations on a certain page, but I didn't consider that `filter` doens't remove the annos from the positions `recalculation`! So each page change my customly made ranges were getting needlesly revived on irrelevant content and destroyed 🤯 
And I haven't mentioned the jittering that was happening on a page change when the filter was trying to remove the old highligths and display the new ones not quickly enough...
Morevover, that approach didn't allow me to use a static plugin, leading to all sorts of magic I described above...

So... The _solution_ I found was to force the re-render of the `Annotorious`! It destroy the `annotator` instance and allows each page work with the annotator from scratch! No more monkey patching of the already monkey patched methods or redundant revivals 🎉

**Comment by rsimon** [comment]
Ah - sorry. Need to find some time later to read through this in detail. Just briefly (if this is of interest at all!). If you need to work with multiple anno instances in parallel - register common selection or lifecycle handlers, delete/update annotations regardless on which annotator they live etc. - there's a utility that can handle most of the plumbing for you:
https://github.com/annotorious/annotorious/tree/main/packages/annotorious-react-manifold

But as I said: not sure if this is even a use case for you.

**Comment by oleksandr-danylchenko** [comment]
I was just wondering "why does the A9S have 2 React implementations?" 😅 
But turns out the manifold should be used for handle multiple annotator instances instead...

**Comment by oleksandr-danylchenko** [comment]
Fortunately, I think that having just a single annotator instance per page should be enought. And it makes the code more straightforward anyway 😅
