### ISSUE TITLE
Want to know why updates go into formatter twice after annotation dragging

### ISSUE THREAD

**Issue by w5c17** [annotorious/annotorious#390]
Hello, I would like to try each comment to have its own line width and line color,I try this on formatter and the code is as follows
![企业微信截图_17121144366615](https://github.com/annotorious/annotorious/assets/47955766/b8c84abd-b3d2-4ba1-88c1-de6ff3c07c9e)
The above code worked when I just toggled annotations, but something happened when I tried to drag annotations。
The following is the output of my console. I did the following operations and drew two straight lines with different colors and widths. When I dragged the first line, I found that the annotations in the formatters were printed in the console for two times The second annotation,
![企业微信截图_17121147423680](https://github.com/annotorious/annotorious/assets/47955766/3c3b248c-f54c-48e9-9fc2-26f05fd42586)
In addition, I found that even if I changed the width of the line, it was still very difficult to select, but I should have clicked on the line, can you tell me how to solve it? Thank you for your answer

**Comment by rsimon** [comment]
Closing this as `won't fix` (v2.x). Meanwhile, Annotorious v3 is available, which has a new styling framework implementation.
