### ISSUE TITLE
 I want the editor to support drop-down options, and I want the author to adopt them

### ISSUE THREAD

**Issue by oldwu-newbee** [annotorious/annotorious#394]
![select](https://github.com/annotorious/annotorious/assets/41003476/ed9c2ab3-ae28-4f94-a587-b2497ec42332)

**Comment by rsimon** [comment]
Hi, not sure what you are asking :-) Autosuggest is supported in Annotorious v2.7. (You have to hit the arrow-down key to display all available options.) If you want a HTML `<select>` style dropdown instead, I'm afraid that is not included.

(FWIW: the upcoming 3.0 version of Annotorious will work in a different way, and support building your own React or Svelte popup editors more easily.)

**Comment by Whao510** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Whao510** [comment]
Thank you for your quick reply. What I want to say is, can the editor be customized? I want to change the tag to <select></select>. I also want to know when Annotorious 3 will be released with proper usage guidelines

**Comment by Whao510** [comment]
Thank you for your quick reply. What I want to say is, can the editor be customized? I want to change the tag to <select></select>. I also want to know when Annotorious 3 will be released with proper usage guidelines

**Comment by Whao510** [comment]
I have learned that Annotorious3 can customize the edit box, and I want to integrate Annotorious3 into vue in the future, but I did not find the relevant documents about annotorious-vue. I really like the plug-in you created, which has been of great help to me

**Comment by rsimon** [comment]
Closing this as `won't fix`. The editor from v2.x is no longer maintained. Meanwhile, Annotorious v3 is available and the new, more flexible, approach is to use the helper components to build custom poups. [See here for the React helper](https://annotorious.dev/react/custom-popups/).
