### ISSUE TITLE
Editor positioning problem, eager to know how the editor positioning is dynamically positioned next to the box

### ISSUE THREAD

**Issue by oldwu-newbee** [annotorious/annotorious#395]
![uu](https://github.com/annotorious/annotorious/assets/41003476/c56d5c8f-95f6-4290-a621-2c37983a511a)

**Comment by oldwu-newbee** [comment]
Because I want to make a drop-down box that meets the requirements by clicking clickAnnotation event, I hope the author can help me in time, thank you very much

**Comment by rsimon** [comment]
Extending the editor is problematic in Annotorious v2. Did you see the documentation here?
https://annotorious.github.io/guides/editor-widgets/

This might help to get you started.

Another option, if you want to build your own editor entirely: Each annotation is an SVG shape. You can listen to the [selectAnnotation](https://annotorious.github.io/api-docs/osd-plugin/#selectannotation-1) event. The event will give you a reference to the SVG element as a second argument. You could use this to get the position using `element.getBoundingClientRect()` for the position.

**Comment by rsimon** [comment]
Closing this, since Annotorious v3 is now available and has a new, more flexible, approach for building custom popups, through the helper components. [See here for the React helper](https://annotorious.dev/react/custom-popups/).
