### ISSUE TITLE
An error occurs in anno.addAnnotation(annotation);

### ISSUE THREAD

**Issue by uda-backup** [annotorious/annotorious#396]
annotation = {
    "id": "uploads/b24705053f71a5bbc87631550d3467be_1.webp",
    "src": "uploads/b24705053f71a5bbc87631550d3467be_1.webp",
    "text": "aaaaa",
    "shapes": [
        {
            "type": "rect",
            "geometry": {
                "x": 0.16083333333333333,
                "y": 0.13333333333333333,
                "width": 0.24583333333333332,
                "height": 0.12380952380952381
            }
        }
    ]
}
anno.addAnnotation(annotation);
When I try to
Error adding annotation: TypeError: Cannot read properties of undefined (reading 'type')
This error will appear.
The version is 2.7.13

**Comment by rsimon** [comment]
Please see here for the annotation format:
https://annotorious.github.io/getting-started/web-annotation/

Can I ask where you found the information about the format you were trying to use? I believe that might be from Annotorious v1 which, I think, got deprecated 7 years ago. Are there examples still floating around on the web?

**Comment by uda-backup** [comment]
thank you!

This is my first time using it, so I was listening to chatGTP while creating it, and chatGTP suggested this format.

I didn't do much research on the web.

**Comment by rsimon** [comment]
:-D Got it. Yes, never trust ChatGPT too much ;-)
