### ISSUE TITLE
No way to remove an annotation that has no body

### ISSUE THREAD

**Issue by jimsafley** [annotorious/annotorious#399]
I'm on 2.7.13, using the standard version API.

I have an annotation that has no `body`. After using `setAnnotations()` to render the annotation to the image, the UI provides no way to remove the annotation from the image. Clicking on the box opens the editor popup, but there is no delete option, and clicking "Cancel" or "OK" doesn't remove the drawing box.

For example (note that `body` is an empty array):

```json
[
  {
    "@context":"http:\/\/www.w3.org\/ns\/anno.jsonld",
    "type":"Annotation",
    "body":[],
    "target":{
      "source":"http:\/\/localhost\/image.jpg",
      "selector":{
        "type":"FragmentSelector",
        "conformsTo":"http:\/\/www.w3.org\/TR\/media-frags\/",
        "value":"xywh=pixel:352,159,107,77"
      }
    },
    "id":"#2c0ba819-c91b-4272-a113-a192d4c8b927"
  }
]
```

**Comment by rsimon** [comment]
Closing this as `won't fix` in v2.7. Meanwhile [v3 is available](https://annotorious.dev/), which has a re-designed API.
