### ISSUE TITLE
Issues when displaying annotations with SVG <path> selector

### ISSUE THREAD

**Issue by yangli0516** [annotorious/annotorious#400]
I was trying to use the OpenSeadragon and the Annotorious plugin to display the Non-Rectangular Polygon annotation from [this IIIF cookbook recipe](https://iiif.io/api/cookbook/recipe/0261-non-rectangular-commenting/)
 
The SVG selector from the annotation is:

```html
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'><g><path d='M270.000000,1900.000000 L1530.000000,1900.000000 L1530.000000,1610.000000 L1315.000000,1300.000000 L1200.000000,986.000000 L904.000000,661.000000 L600.000000,986.000000 L500.000000,1300.000000 L270,1630 L270.000000,1900.000000' /></g></svg>
```

If I feed the selector as is to Annotorious, I get the following error:

```
EmbeddedSVG.js:22 
 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at t (EmbeddedSVG.js:22:11)
    at Uh (EmbeddedSVG.js:34:3)
    at It (EmbeddedSVG.js:54:14)
    at Object.Wh [as SvgSelector] (EmbeddedSVG.js:62:17)
    at hs (index.js:31:39)
    at lx.addAnnotation (OSDAnnotationLayer.js:376:19)
    at OSDAnnotationLayer.js:526:46
    at Array.forEach (<anonymous>)
    at OSDAnnotationLayer.js:526:19
```

After I removed the XML namespace from the `<svg>` element:

```html
<svg><g><path d='M270.000000,1900.000000 L1530.000000,1900.000000 L1530.000000,1610.000000 L1315.000000,1300.000000 L1200.000000,986.000000 L904.000000,661.000000 L600.000000,986.000000 L500.000000,1300.000000 L270,1630 L270.000000,1900.000000' /></g></svg>
```

The annotation outline showed. However, the console showed the following error:

```
Uncaught Unsupported SVG shape type: g
```

I then removed the `<g>` element from the selector as it is OK for a single `<path>` in this case:

```
<svg><path d='M270.000000,1900.000000 L1530.000000,1900.000000 L1530.000000,1610.000000 L1315.000000,1300.000000 L1200.000000,986.000000 L904.000000,661.000000 L600.000000,986.000000 L500.000000,1300.000000 L270,1630 L270.000000,1900.000000' /></svg>
```

This time the outline displayed correctly and there's no error from the console. However, events from the annotation such as `clickAnnotation` and `selectAnnotation` were not fired up.

I understand that Annotorious expects the selector in a certain form, and we can do conversion on the selectors to make them work with Annotorious. And I would be really grateful if I can get some clue about the cause of the event firing issue.

**Comment by rsimon** [comment]
I don't know what the rest of your annotation looks like. The click issue sounds like it could be related with the annotation not having an ID? Anyways: [see here](https://annotorious.github.io/getting-started/web-annotation/) for the annotation format that Annotorious requires.

**Comment by yangli0516** [comment]
Hi @rsimon ,

The annotation does have an ID. The annotation data passed to Annotorious is as follow:

```json
[
    {
        "@context": "http://www.w3.org/ns/anno.jsonld",
        "id": "https://iiif.io/api/cookbook/recipe/0261-non-rectangular-commenting/annotation/p0002-svg",
        "type": "Annotation",
        "body": [
            {
                "type": "TextualBody",
                "value": "Gänseliesel-Brunnen",
                "language": "de",
                "format": "text/plain"
            }
        ],
        "target": {
            "source": "https://iiif.io/api/cookbook/recipe/0261-non-rectangular-commenting/canvas/p1",
            "selector": {
                "type": "SvgSelector",
                "value": "<svg><path d='M270.000000,1900.000000 L1530.000000,1900.000000 L1530.000000,1610.000000 L1315.000000,1300.000000 L1200.000000,986.000000 L904.000000,661.000000 L600.000000,986.000000 L500.000000,1300.000000 L270,1630 L270.000000,1900.000000' /></svg>"
            }
        }
    }
]
```

This has been working well for other shapes such as circle and polygon. Only having this issue with SVG `path`.

**Comment by rsimon** [comment]
Just a quick Q: are you using Annotorious 2.7 or 3? Paths are not yet supported in v3.

**Comment by yangli0516** [comment]
> Just a quick Q: are you using Annotorious 2.7 or 3? Paths are not yet supported in v3.

I am using 2.7

**Comment by yangli0516** [comment]
Have found out that Annotorious expects the x and y coordinates separated by space such as:

```
M270.000000 1900.000000
```

In the recipe they use comma as separators:

```
M270.000000,1900.000000
```

Anyway I now have a way to convert the separators to white space to make it work with Annotorious. Will close this issue now.
