### ISSUE TITLE
How to customize more drawing tools?

### ISSUE THREAD

**Issue by oldwu-newbee** [annotorious/annotorious#406]
How can fabricjs be used when annotorious-openseadragon is used, since the project also uses screenshot, measurement capabilities? Can you help me?

**Comment by rsimon** [comment]
Sorry, there is no easy way to use FabricJS with Annotorious. You would have to build your own drawing tools, which means you would first need to study how the current ones are built. (See [here for the code](https://github.com/annotorious/annotorious/tree/2.x/src/tools).)

However, FabricJS would not help you with Screenshot or measurement. For this, I'd recommend [html2canvas](https://html2canvas.hertzen.com/) and [OSDMeasure](https://github.com/verrochi92/OSDMeasure).

**Comment by oldwu-newbee** [comment]
Isn't there any way to get osd annotorious to work with fabric? anno is fine for now, but trying to bring fabricjs into the mix has messed up the layers.

**Comment by oldwu-newbee** [comment]
this._fabricCanvas = new fabric.Canvas(this.viewer.drawer.canvas);Obviously, that's not a good idea

**Comment by rsimon** [comment]
I don't know what you mean exactly. No - Annotorious is a different drawing library than FabricJS. I'm sure there would be a way to somehow build a drawing tool for Annotorious that interally works with FabricJS. But if you expect an easy solution, that's simply not possible.

**Comment by oldwu-newbee** [comment]
My idea is how to make annotorious and fabric draw on the same canvas, but I can't do it at present. I wonder if you have a good solution, which means the scalability is very large, because 80% of the work has been completed with your annotorious. Unfortunately, Now we need to draw a standard square to capture the coordinates somewhere in the picture, and double lines to map the size of the cells

**Comment by rsimon** [comment]
Sorry, there is no easy solution. It would require significant effort to integrate both libraries, and make them talk to each other in terms of data model, event handling, etc. I'm not saying it can't be done. But it will take much more than a short explanation and a few lines of code.

I'm not aware that anyone has ever tried to integrate Annotorious and FabricJS, and I have not foreseen such an integration in Annotorious' core code. You'd be entering unexplored territory.

I'm always happy to provide free support & answer questions here. But what you are asking would require at least several hours of prototyping, to understand how to even do it; changes to Annotorious itself; or an alternative solution, based on more  detailed requirements.

I am a bit short on time over the next weeks. But I do offer commercial support in principle. If you want to purchase professional support, do drop me a line at hello@rainersimon.io.

**Comment by rsimon** [comment]
Closing this since Annotorious v2.x is officially deprecated, and [Annotorious v3 is now available](https://annotorious.dev/).

To extend Annotorious 3 with additional tool plugins, see this project as an example:
https://github.com/annotorious/annotorious-v3-extensions/tree/main/annotorious-selector-pack
