### ISSUE TITLE
config.disableDeleteKey missing from documentation

### ISSUE THREAD

**Issue by UnivocalHoneyBadger** [annotorious/annotorious#407]
`config.disableDeleteKey` is a perfectly valid configuration property, but it is not listed in the documentation for Annotorious.

Original issue for recogito-js is [here](https://github.com/recogito/recogito-js/issues/106).

**Comment by rsimon** [comment]
Closing this as `won't fix` because v2.7 is officially deprecated, and [v3 is available](https://annotorious.dev/), which has a re-designed API.
