### ISSUE TITLE
allow JSON to be loaded into loadAnnotations 

### ISSUE THREAD

**Issue by dnoneill** [annotorious/annotorious#41]
Allowing a JSON to also be a parameter to loadAnnotations instead of the URL for the annotation.

**Comment by rsimon** [comment]
To set a JSON object directly, you can use the `setAnnotations` method. 

(My intention behind the API design was to separate the sync/async loading methods I guess. I still sort of like it. But happy to hear alternative views :-)

**Comment by dnoneill** [comment]
@rsimon I figured that out and it worked for my application which is why I closed the issue. It was already there :).
