### ISSUE TITLE
Change annotation color based on "label" and .bodies

### ISSUE THREAD

**Issue by samiujan** [annotorious/annotorious#414]
I am using @annotorious/react: 3.0.0 and it's quite easy to use, thanks for creating such a great tool

I have a couple of questions (my React is not that good)

1. I have a palette of buttons with "class labels" e.g. "cat", "dog" and i want to click on the "dog" label and be able to draw a polygon in an image around a shape - this was easy to do via both declarative and the method - but I want to draw a red polygon if I click the "dog" button a green polygon when I click the "cat" button

if I use a dynamic style method, I can set a different style but it applies to all annotations created by the image annotator instance - is there a way to use different colors for different labels, without creating a new annotator instance?

2. If I create an annotation with or without the `W3CImageFormat` adapter, the `body/bodies[]` attribute is always empty - thankfully I can find the SVG coordinates in the `target.selector `object but is this by design? Or am I missing something? 

Thanks (would love to contribute to the docs, as I learn more about the tool)

**Comment by rsimon** [comment]
Thanks for the kind feedback! 

This is, currently, a bit more complicated than it needs to be. I think the API will make it easier in the future. But here's the gist:

- Everything that influences the style of the annotation, naturally needs to be stored in the annotation somehow.
- The annotation `bodies` are there to carry any kind of annotation payload. You could simply add a body that stores whether the annotation carries a `dog` or a `cat` labels.
- The style function can then take this information and change the style accordingly. 

The tricky bit (which might become easier in the future) is that you'll need to inject those bodies into your annotations. My recommendation would be to listen to the `anno.on('createAnnotation', (annotation) => ...)` event. In the event handler, you could do something like:

```
anno.updateAnnotation({
  ...annotation,
  body: {
    purpose: 'labeling',
    value: 'cat'
  }
});
```

I haven't tested that right now. Might need a bit of tweaking. But at least that's the basic idea. Let me know if it works.

**Comment by samiujan** [comment]
thank you - that's very helpful - i didn't call the updateAnnotation method afterwards - I am trying it out and will update on the progress tomorrow

**Comment by samiujan** [comment]
thanks very much - it worked :)

Just trying to understand the event lifecycle - I have created the ImageAnnotator like this

```
useEffect(() => {
  const anno = createImageAnnotator('imgToAnnotate', {
        drawingMode: 'click',
        style: annotationStyle,
      });
  anno.setDrawingTool('polygon');
  
  anno.on('createAnnotation', (annotation) => {
        annotation.body = {
          type: 'TextualBody',
          purpose: 'tagging',
          value: labelNameClicked,
        };
        anno.updateAnnotation( { ...annotation });
      });
}, []);

const annotationStyle = (annotation: Annotation) => {
    let fill = '#000000';
    let stroke = '#000000';
    if (annotation.body && annotation.body.value === 'dog') {
      fill = '#ff0000';
      stroke = '#ff0000';
    }

    if (annotation.body && annotation.body.value === 'cat') {
      fill = '#00ff00';
      stroke = '#00ff00';
    }

    const computedStyle = {
      fill, // Fill color in hex format
      fillOpacity: 0.25, // Fill opacity (0 to 1)
      stroke, // Stroke color in hex format
      strokeOpacity: 0.9, // Stroke opacity (0 to 1)
      strokeWidth: 10, // Stroke width in pixels
    };
    return computedStyle;
  };
```

It seems like the lifeCycle goes like this...

1. Start annotation (click on canvas)
2. Click, click, click
3. Double-click to complete annotation
 - This fires off `styleAnnotation` function, which creates the annotation using default colors (white)
 - It is followed by the `anno.on('createAnnotation', (annotation)` event where I set the colors and call `updateAnnotation`
 - this fires the `styleAnnotation` function again 
5. Click outside the annotation polygon and `updateAnnotation` gets executed

I hope the above made sense.. ideally I would want the colors to be already `#00ff00` or `#ff0000` when I double click the first time or even when I am drawing it out.. but I guess that's not implemented at the moment

Thanks @rsimon !

**Comment by samiujan** [comment]
i'll ask a quick question and then close the thread

is it possible to change the color (executing updateAnnotation?) when you double-click to close the polygon, rather than when you click outside the polygon?

**Comment by rsimon** [comment]
Hi,

calling `updateAnnotation` is supposed to also trigger a re-render. I think the implementation just isn't finished there just yet. (I haven't really spent much time on the image version of Annotorious, since all my current client projects are with the OpenSeadragon version. But I'll get to it eventually ;-)

One of the things I would also like to add is the ability to configure some kind of default body (or bodies), so that a new annotation would instantly get created with e.g. a `cat` or `dog` label. This wasn't available in Annotorious 2, but I remember it would have been useful at some times. (It was actually possible in Annotorious 1, I believe, but that was 10 years ago :-)

**Comment by samiujan** [comment]
Sorry for the late reply and thank you, that's very helpful

It would be an interesting thing to explore - the code is quite clean and readable and I'll investigate
