### ISSUE TITLE
Annotorious and React.StrictMode: Cannot read properties of undefined (reading '$$')

### ISSUE THREAD

**Issue by ChunxuYang** [annotorious/annotorious#416]
I'm using @annotorious/react version 3.0.0-rc.29.

When I'm trying to start the dev server, there's an error shown: 

TypeError: Cannot read properties of undefined (reading '$$')
    at ne (chunk-VGFQLGNG.js?v=5623a142:4897:25)
    at new Cw (chunk-VGFQLGNG.js?v=5623a142:29273:14)
    at DE (chunk-VGFQLGNG.js?v=5623a142:30615:36)
    at @annotorious_react.js?v=5623a142:5287:18
    at commitHookEffectListMount (react-dom_client.js?v=5623a142:16915:34)
    at commitPassiveMountOnFiber (react-dom_client.js?v=5623a142:18156:19)
    at commitPassiveMountEffects_complete (react-dom_client.js?v=5623a142:18129:17)
    at commitPassiveMountEffects_begin (react-dom_client.js?v=5623a142:18119:15)
    at commitPassiveMountEffects (react-dom_client.js?v=5623a142:18109:11)
    at flushPassiveEffectsImpl (react-dom_client.js?v=5623a142:19490:11)

Here is my react component:

```{tsx}
import "@annotorious/react/annotorious-react.css";

import { useEffect, useState } from "react";

import {
  AnnotoriousOpenSeadragonAnnotator,
  OpenSeadragonAnnotator,
  OpenSeadragonViewer,
  useAnnotator,
} from "@annotorious/react";

import { Button } from "./ui/button";

const duomo = {
  Image: {
    xmlns: "http://schemas.microsoft.com/deepzoom/2008",
    Url: "//openseadragon.github.io/example-images/duomo/duomo_files/",
    Format: "jpg",
    Overlap: "2",
    TileSize: "256",
    Size: {
      Width: "13920",
      Height: "10200",
    },
  },
};

export default function OldViewer() {
  const [mode, setMode] = useState<"move" | "draw">("move");
  const anno = useAnnotator<AnnotoriousOpenSeadragonAnnotator>();
  useEffect(() => {
    if (anno) {
      anno.setDrawingEnabled(mode === "draw");
    }
  }, [mode, anno]);

  return (
    <div>
      <div className="absolute top-0 left-0 z-40">
        <Button
          onClick={() => {
            setMode((prev) => (prev === "draw" ? "move" : "draw"));
          }}
        >
          {mode}
        </Button>
      </div>
      <OpenSeadragonAnnotator>
        <OpenSeadragonViewer
          options={{
            tileSources: duomo,
            showNavigationControl: false,
            mouseNavEnabled: false,
            gestureSettingsMouse: {
              clickToZoom: false,
              dblClickToZoom: false,
              dragToPan: false,
              scrollToZoom: false,
            },
          }}
        ></OpenSeadragonViewer>
      </OpenSeadragonAnnotator>
    </div>
  );
}

```

**Comment by ChunxuYang** [comment]
Here is a code sandbox for your reference:
[https://codesandbox.io/p/sandbox/openseadragon-annotorious-react-7pd836](https://codesandbox.io/p/sandbox/openseadragon-annotorious-react-7pd836)

**Comment by rsimon** [comment]
Thanks for reporting. This is weird, I'll investigate. It seems that Annotorious has problems in `<React.StrictMode>`. Without it, it's working.

However, there are several issues with your code (at least on the CodeSandbox):
- Most importantly, you are missing the `<Annotorious>` context provider, which needs to wrap your app. (See [here](https://github.com/annotorious/annotorious/tree/main?tab=readme-ov-file#using-in-react).)
- Your OpenSeadragon element has 0 size. You need to apply a `width` and `height`.
- You are not importing your own CSS stylesheet file into your app.
- On the CodeSandbox, you are not importing the Annotorious CSS stylesheet (`import '@annotorious/react/annotorious-react.css';`)

**Comment by ChunxuYang** [comment]
@rsimon Thanks for your reply! Yes there may be something with StrictMode. I've updated the codesandbox for the issues.

**Comment by ghost** [comment]
I had the same error with the latest version. Version 3.0.0-rc.23 seems to work for me in Strict Mode.

**Comment by rsimon** [comment]
I just published a fix which should resolve this problem. It's a weird timing issue which I, frankly, don't quite understand. Therefore this still needs some testing. But will go live with the next RC release.
