### ISSUE TITLE
Generalize the `SelectionState` type to allow custom selection implementations

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [annotorious/annotorious#419]
## Context
Currently, the `SelectionState` and the `Selection` modules, in general, are designed to work exclusively with pointer-based user interactions. https://github.com/annotorious/annotorious/blob/9188ea1d73911209dcd367734e7f45f5382950e3/packages/annotorious-core/src/state/Selection.ts#L5-L10

## Issue
This is acceptable for the visual images editor, but it's limiting for the descending `@recogito/text-annotator-js`. The latter should support both the mouse and the keyboard selection simultaneously. 

When I tried adding a custom `TextSelection` module and its specific type with the `KeyboardEvent` support I stumbled into _type mismatches_ with the rest of the parent A9S infrastructure.

That's because the parent `AnnotatorState` is tightly coupled with the pointer-based `SelectionState`: https://github.com/annotorious/annotorious/blob/9188ea1d73911209dcd367734e7f45f5382950e3/packages/annotorious-core/src/model/Annotator.ts#L69-L79
And I couldn't pass my custom text selection into other A9S methods like `createLifecycleObserver`: 
https://github.com/annotorious/annotorious/blob/9188ea1d73911209dcd367734e7f45f5382950e3/packages/annotorious-core/src/lifecycle/Lifecycle.ts#L9-L10

## Suggested Changes
The `Selection` module in the `@a9s/core` may become a generic container and API requirements for the concrete selection implementations. The latter will be provided by the `ImageAnnotator`, or the `TextAnnotator`. 

That would make it similar to the [`baseRenderer`](https://github.com/recogito/text-annotator-js/blob/main/packages/text-annotator/src/highlight/baseRenderer.ts) we use in `text-annotator-js`.

The current `createSelectionState` implementation may be moved under the `ImageAnnotatorSelectionState.ts`.

**Comment by rsimon** [comment]
Would it be sufficient to make the event a basic `Event` type? Or type the SelectionState with `<T extends Event>`? 

In general: I'd love to hear more about your use case. So far, I really only used the `pointerEvent` to get a screen coordinate for placing an editor popup. I guess a keyboard event wouldn't have such an option? Also, I'd be generally interested to improve the accessibility of both Annotorious and the Text Annotator, but don't really know how keyboard selection would work in either case. (For text, I assume, you still start with a pointer event, and then use `SHIFT` + arrow key to extend the selection?)

**Comment by oleksandr-danylchenko** [comment]
> I'd love to hear more about your use case

In my project, we have a requirement to support the selection and highlighting the motion-impaired users. They should be able to start and finish the selection using _only the keyboard_. For that purpose, such users utilize the [caret browsing](https://www.makeuseof.com/what-is-caret-browsing/), which allows them to place the selection caret anywhere on the page. Then a user can _start selecting_ back & forth with the `Shift + ←/→`. 

> I really only used the `pointerEvent` to get a screen coordinate for placing an editor popup

Currently, in text-annotator it's also used to determine whether the popup should appear and whether the selection is "finished" ([source](https://github.com/recogito/text-annotator-js/blob/fbe29fdfde0c4bd3c7d6e8433ea779a72f0d6ee8/packages/text-annotator-react/src/TextAnnotatorPopup.tsx#L46-L56)).

> screen coordinate for placing an editor popup. I guess a keyboard event wouldn't have such an option?

Right, keyboard events know nothing about the selection position. But they still capture the selection `range`s that have dimensions we can place the popup around.

---

I investigated how other annotating solutions worked around that challenge and found a similar issue in the manifold repo - https://github.com/ManifoldScholar/manifold/issues/2326#issue-483067717. They added keyboard support in the following PR - https://github.com/ManifoldScholar/manifold/pull/3086. 
From the interesting bits I can point out how they handled the "selection completion" upon lifting the `Shift` key - https://github.com/ManifoldScholar/manifold/pull/3086/commits/2d0f9f218b6b01f06c870ee36c99f95664148558. 

---

P.S.
I've already started working on a prototype both in A9S in R6O that will utilize some shared `BaseSelection` and provide concrete implementations for the Image & Text annotators

**Comment by oleksandr-danylchenko** [comment]
> Would it be sufficient to make the event a basic Event type? Or type the SelectionState with <T extends Event>?

Hmm... I think it is worth giving a try 🤔 
As I was going around the idea that we might be interested in both the `pointer` & the `keyboard` events. But on the other hand, I see no use-case where a single event won't be enough to determine the selection "completed" state. In the case of the pointer - it's the `pointerup`. In case of the keyboard - lifting the `Shift` key or shortcut like `Ctrl + A`.

**Comment by rsimon** [comment]
Ah - well I wasn't aware of caret browsing! (Shame on me...) Thanks for pointing it out. That's definitely something I'd want to support. 

> Currently, in text-annotator it's also used to determine whether the popup should appear and whether the selection is "finished"

That's true. Although TBH I'm still struggling with the "finished" part. On touch devices, you can never really assume the selection to be "finished". (You can't remove the handles on pointer up, and ideally should leave the annotation modify-able while the popup is open.) But, then, mobile may simply need a separate approach.

**Comment by rsimon** [comment]
I have also read through the [discussion in the manifold repo](https://github.com/ManifoldScholar/manifold/issues/2326#issue-483067717) now - thanks for pointing it out! Totally agreed that we should be easily able to follow the same approach.

I wonder if there's anything we can do to enhance accessibility of the existing annotations, too. This may be significantly easier in the SPANs renderer, since that generates actual DOM elements. But there are still some tricky issues.
- They sit in their own layer, and are not "in sequence" with the text.
- Things like `aria-haspopup` could be easily added. However, not every application might actually supply a popup.
- I guess adding `tabIndex` would potentially allow users to navigate through annotations by `Tab`. (The annotation layer has `pointer-events` set to `none`. But that wouldn't affect keyboard events.) However, we'd probably have to add extra logic that allows users to navigate to the next off-screen annotation which may not yet be rendered?

**Comment by oleksandr-danylchenko** [comment]
> Although TBH I'm still struggling with the "finished" part

You're not single in that struggle. As you said, on mobile, there will be a "finished" state for the selection neither on handles movement nor pressing "Select All" in the context menu. 
The same issue even goes for the desktop users who use the `Ctrl + A` shortcut. There's no _simple_ way to detect that using the `keyup` event. And piggybacking the events can also break apps that redirect the selection from the whole page, only to the meaningful content. Like it's described in [this article](https://dev.to/chromiumdev/detecting-select-all-on-the-web-2alo).

So, the alternative idea is not to have a single "finished" state, but to show the popup when one of the following conditions is met:
1. The `event` is `pointerup` and the `selection` isn't empty.
2. The `event` is `keyup` and the `selection` isn't empty. We don't care about any specific event. Always show the popup if the keyboard event initiated the selection.

Example in the Slab editor behavior: 

https://github.com/annotorious/annotorious/assets/68850090/689334c0-d033-4eca-9ee6-2110d7819af9

**Comment by oleksandr-danylchenko** [comment]
But the drawback of not having some "selection in progress" concept when processing keyboard events is that the user can press any random button, and it'll get registered in the `Selection.event`: 

https://github.com/annotorious/annotorious/assets/68850090/3acd9606-0c06-403e-bac4-3f837cfcff0a

**Comment by oleksandr-danylchenko** [comment]
> 2\. The `event` is `keyup` and the `selection` isn't empty. We don't care about any specific event. Always show the popup if the keyboard event initiated the selection.

Unfortunately, such a strategy isn't suitable if the popup upon opening immediately focuses on its content. It hijacks the text selection functionality and the user cannot proceed further. 

I also tried restoring the selection range after the focus on a `button`:
```tsx
useEffect(() => {
  const { current: buttonEl } = buttonRef;
  if (!buttonEl) return;

  const selection = document.getSelection();
  if (!selection) return;

  const rangeBeforeFocus = selection.getRangeAt(0).cloneRange();

  setTimeout(() => {
    buttonEl.focus({ preventScroll: true });
    
    // Additional timeout is required for Firefox to restore the selection back
    setTimeout(() => {
      selection.removeAllRanges();
      selection.addRange(rangeBeforeFocus);
    });
  });
}, []);

return (
  <div className="popup">
    <button ref={buttonRef}>COMMENT</button>
    <button onClick={onClick}>Close</button>
  </div>
);
```
It _properly restores the selection view_ for the button, but I still cannot proceed with the selection using the `Shift` + arrows 🥲

https://github.com/annotorious/annotorious/assets/68850090/fd05cceb-3093-4399-8504-bab48ade6e1c

**Comment by rsimon** [comment]
But does the popup get focus automatically when rendered? Shouldn't be the case, right? Unless it includes e.g. an input field with `autofocus` set to true or something?

**Comment by oleksandr-danylchenko** [comment]
> But does the popup get focus automatically when rendered?

Currently, the focus on the popup content is handled by the consuming applications. In our case, this is the `text-annotator-react/test` that focuses on the internal `input` ([source](https://github.com/recogito/text-annotator-js/blob/fbe29fdfde0c4bd3c7d6e8433ea779a72f0d6ee8/packages/text-annotator-react/test/App.tsx#L25-L30)). For the real applications, the focus might shift to the popup container with some accessible `aria-label`.

In any case, we should make an example of how to leave the popup accessible by focusing it upon selection, and how to prevent breaking the keyboard selection UX...

So we might need to limit the user selection event updates only to the lifting of the shift key and detection of the `Ctrl + A` 🤔. Then we won't interrupt the selection and won't force the consumer to introduce exotic workarounds 🤔

**Comment by oleksandr-danylchenko** [comment]
> But does the popup get focus automatically when rendered?

After consulting with an a11y UX expert on our team, we decided that:
- the annotator popup should always appear when the user pauses their annotating process. That can be signified by lifting the `Shift` or pressing `Ctrl+A`.
- the appearance of the annotator popup must not block users from further text selection. For that, the focus should be preserved on the content container:

> Ideally, you could release shift, then press it again, and select some more text. This is true also for Mouse users in order to pass a new SC in WCAG 2.2: https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements This is for people who have trouble dragging. This makes tracking Shift (rather than something admittedly awkward like Control Alt/Option h) tricky. But if you could leave focus on the page, and just open the popup when mouse is released or when shift is lifted, and then leave it open through subsequent shift presses and shift clicks, and let users tab to the popup or click a close button or press escape to close the popup, that would work.

- there's no browser-compatible way to signify that there's a popup appeared after they paused their selection. But we can work around that by manually providing `aria-live` message upon popup opening:
> It might be better to use an aria-live polite message like "Press Tab to move to Highlights and Comments Dialog" - this will just work everywhere

**Comment by rsimon** [comment]
Agreed - that's how I think it should work. In our case, we also focus on an input field, right after the popup gets rendered. But that's not caused by `@recogito/text-annotator`. Therefore, I think, it's perfectly possible to support the interaction in the way you describe.

Additionally, I wonder what an a11y-compatible way to interact with existing annotations would be. I guess you could tab through the SPANs - with the limitations imposed by the lazy rendering, as I think I wrote in some other thread?

**Comment by oleksandr-danylchenko** [comment]
> Additionally, I wonder what an a11y-compatible way to interact with existing annotations would be

Currently, we are discovering the usage of the [`mark` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark) by injecting it into the content. It was introduced specifically to mark the presence of the highlights and it's properly announced in most of the browsers* (except the bugged Safari + VoiceOver that doesn't announce them properly in the QuickNav mode). Also, using `mark` helps to use highlight-specific shortcuts in the readers.
But there are still a few drawbacks. The main one is that `mark` should be present in the DOM, which will require some crazy mutations when the annotations are nested. And the second one is the inconsistent support across various browsers, especially when you wanna link the `mark` with the [`comment`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/comment_role).

**Comment by rsimon** [comment]
RecogitoJS, the predecessor to the text annotator, did exactly that & handle all the crazy DOM mutations, nesting, splitting to handle overlaps etc. I was thinking about eventually adding a renderer that works that way again. But it has lots of drawbacks as you would expect. Definitely a solution I'd want to avoid if I can.
