### ISSUE TITLE
New editor fields

### ISSUE THREAD

**Issue by dnoneill** [annotorious/annotorious#43]
I would like to add a some fields to the editor. This might be specific to me. I think it would be nice to be able to add a function that allows you to add a new text field and pass in parameters. Something like this:

anno.addFields([{'placeholder': 'Rights', 'field': 'rights'}, {'placeholder': 'Language', 'field': 'body.language'}])

Where placeholder is the text field placeholder and field is the field in the annotation. 
If this already exists please let me know.

**Comment by rsimon** [comment]
This doesn't exist yet. In principle, the editor is fully extensible/customizable. But at the moment, that requires a) creating your own fork, and b) implementing the extension as a React component.

I started to write a guide about this [here](https://recogito.github.io/guides/creating-custom-widgets/) but haven't finished this yet.

I'm planning to make this a lot simpler in the future, with an API somewhat along the lines of what you suggest. (It needs to be a bit more complex though, I think, to allow for arbitrary extensions. The idea is to provide a list of functions, one per field, which receive the annotation as an argument and Reuben a field object, similar in structure than the React components described in the guide.)

**Comment by rsimon** [comment]
PS: I'm happy to hear suggestions for a good API for this.

**Comment by rsimon** [comment]
Just a quick heads-up: there's activity on this now:
https://twitter.com/aboutgeo/status/1304355124421300230?s=20

Work on a plugin API for extending the editor (or completely replacing the existing widgets) is currently happening in [this branch of the recogito-client-core package](https://github.com/recogito/recogito-client-core/tree/editor-plugin-api).

An example plugin with some comments in [in this Gist](https://gist.github.com/rsimon/7acd0929b44ac52a5affcf289fd0aacd). Comments & feedback welcome!

**Comment by rsimon** [comment]
The API for extending the editor is now available in the latest release, and docs are here:

https://recogito.github.io/guides/extending-the-editor/

(Note that this is the first version. The exact API might change further down the line...)

@dnoneill, I'm aware this mechanism is more generic than what you asked for. A kind of standard key/value widget as a built-in component would be nice for the future.

**Comment by dnoneill** [comment]
@rsimon This is perfect for my needs. Thanks!

**Comment by dnoneill** [comment]
@rsimon Is there a way to pass variables into custom widgets? I want to pass the field into the widget. Is that possible?
Also, having played around with it it looks like it allows you to append custom bodies but not the annotation specifically. This is causing problems for me because I want to add a rights and language field. Those fields should go in the annotation not a seperate body field. Since I can't add a rights or language field for each comment it makes the most sense to have the fields go in the annotation and not the body fields. I have not seen anyway to do this. However if I could edit the whole annotation this API implementation is perfect for my needs.

{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno16",
  "type": "Annotation",
  "rights": "https://creativecommons.org/publicdomain/zero/1.0/",
  "body": {
    "id": "http://example.net/review1",
    "rights": "http://creativecommons.org/licenses/by-nc/4.0/"
  },
  "target": "http://example.com/product1"
}

**Comment by rsimon** [comment]
Yes, it's possible to pass configuration parameters at init time, like so:

```js
var myWidget = function(args) {
  // ...
}

var anno = Annotorious.init({
  image: 'hallstatt',
  widgets: [
    { widget: myWidget, foo: 'my-value', bar: true }
  ]
});
```

In this case, `foo` and `bar` will be passed into the `myWidget` function (as fields of the `args` variable) when `myWidget` gets called.

Concerning the `rights` field... hm, indeed. The `myWidget` function gets read access on the annotation, but can only modify the bodies. I hadn't thought of a use case like that, but agree it's needed. I'll think about a suitable API for this. (The way the widgets work right now has other, React-related, issues, too. So I'll need to change a few other things in the medium term as well, anyway.)

**Comment by dnoneill** [comment]
@rsimon I had tried doing the above on the widgets before and I tried one more time and it did not work. Args returned annotation, onAppendBody, onRemoveBody, onSaveAndClose, onUpdateBody and readOnly. I tried args.foo and I got undefined. 

Thanks for getting back to me so fast.

**Comment by rsimon** [comment]
Ouch - indeed. That's how it's __supposed__ to work, but I see now there was a bug :-) I fixed the bug in the master branch just now & will publish a new release later this week.

**Comment by dnoneill** [comment]
@rsimon Thanks!

**Comment by rsimon** [comment]
I just published new releases for Annotorious and the OpenSeadragon plugin which (among other things) should fix the issue:

https://github.com/recogito/annotorious/releases/tag/v2.1.3
https://github.com/recogito/annotorious-openseadragon/releases/tag/v2.1.1

**Comment by vinibiso** [comment]
@rsimon hi!
I know there is a way to create a new widget, but what does it have to have?
I knows it's a function, but im in the dark as to how to implement one.

**Comment by rsimon** [comment]
I admit it's pretty early days for the widget plugin API. Depending on what it is you want to do, you might run into unsupported territory... (We're still in the finding-things-out stage ;-)

Here's a minimal example though, hope this illustrates the basics:

https://recogito.github.io/guides/extending-the-editor/

**Comment by vinibiso** [comment]
Right! Thank u for aswering do quickly.
Im trying to add some select inputs to the annotation bodies.
And a plain string description, without the possibilitou of replying.

I tried creating a widget like:
An HTML div:

`   <div id="selectWidget">
        <select id="annotation_modal__competencia">
            <option value="0">Outro</option>
            <option value="1">C1</option>
            <option value="2">C2</option>
            <option value="3">C3</option>
            <option value="4">C4</option>
            <option value="5">C5</option>
        </select>
    </div>
`

and then returning it to the widget
`
        var selectWidgetDiv = document.getElementById("selectWidget");

        var selectWidget = function(args) {
            console.log(args);
            return selectWidgetDiv
        }

        var anno = Annotorious.init({
            image: 'redacao',
            locale: 'auto',
            widgets: [
                { widget: selectWidget }
            ]
        });
`

and the select appears insider, but then I don't know to go about adding it to the body when it saves.

I also tried using removing all widgets and making a custom modal that when the annotation is created it asks for addtional fields.

The problem that I ran into then was that, if there are no widgets, the annotation isn't created.
I tryed using the only the comment one, but i don't want the possibily of several comments.

sorry for taking time away from your work

**Comment by rsimon** [comment]
Ah, I see what you are trying to do. It won't (quite) work like that (but almost). I'm on mobile now, but will post a code snippet tomorrow morning when I'm back on the keyboard.

**Comment by vinibiso** [comment]
Thank u very much!

**Comment by rsimon** [comment]
What you are doing now is to create the widget elements in HTML markup, and then basically cut-and-paste them into the widget. The widget will re-render whenever the popup opens. I think your approach would have unwanted side effects. (I think the HTML markup might be gone after the widget opens, thus breaking when it opens the second time.)

## First Step

To be more robust: create the widget entirely in JS, inside the plugin function. This would look roughly like this:

```js
var plugin = function(args) {
  var elem = document.createElement('select');

  var option1 = document.createElement('option');
  option1.value = 0;
  option1.innerHTML('Outro');

  // ...repeat multiple time (or better: wrap this in a 'createOption(val, label)' function and use multiple times

 return element;
}
```

I *think* you should also be able to just create the element using `document.createElement('select');` and then create the rest simply via innerHTML, but would need to try whether this works...

```js
var elem = document.createElement('select');
elem.innerHTML = '<option value="0">Outro</option><option .... // and so on
```

# Step 2 Attach Handlers

Now that you have the widget elements, you need to attach listeners to them. This way you can catch the event that happens when the user changes the selection, and update the annotation accordingly. The wiget plugin interface provides you with callback functions for this. What you need to do is connect the event on your widget element to the appropriate callback function.

```js
# Inside the plugin function, right after creating the SELECT element

// Also see https://recogito.github.io/guides/extending-the-editor/ for comparison

// 1. Find a current selection body in the annotation, if any
var currentSelectionBody = args.annotation ? 
args.annotation.bodies.find(function(b) {
  return b.purpose == 'selecting';
}) : null;

// 2. Keep the value in a variable
var currentSelectionValue = currentSelectionBody ? currentSelectionBody.value : null;

// 3. Triggers callbacks on user action
var addSelection = function(evt) {
  if (currentSelectionBody) {
    args.onUpdateBody(currentColorBody, {
      type: 'TextualBody',
      purpose: 'selecting',
      value: evt.target.value;
    }); 
  } else { 
    args.onAppendBody({
      type: 'TextualBody',  
      purpose: 'selecting',
      value: evt.target.value;
    });
  }
}

// The 'elem' var is the reference to your SELECT element
elem.addEventListener('change', addSelection);
```

Ok, I scribbled that down pretty quickly and didn't test. So probably has some bugs and/or typos. But that's roughly the way to do it :-)

**Comment by vinibiso** [comment]
Oohh! I get it now!
It makes lot of sense to create the element thought JS.
And hook an even listener no the element that in turns update the body.

I ended up using headless mode, making a modal of might own and storing the data in a separate object where the keys are the ids of the selection. It's working fine but i'll probably end up customizing the widgets like you showed.

Thank u so much for the help @rsimon

**Comment by vinibiso** [comment]
Thank you @rsimon !
It worked like a charm after a few adjustments and test it's working.

```js
        var selectWidget = function(args) {
            var select = document.createElement('select');
            select.id = 'select_'+args.purpose;
            args.options.map((option) => {
                var opt = document.createElement('option');
                opt.value = option.value;
                opt.innerHTML = option.label;
                select.appendChild(opt)
            })

            var currentSelectionBody = args.annotation ? 
                args.annotation.bodies.find(function(b) {
                return b.purpose == args.purpose;
            }) : null;

            var currentSelectionValue = currentSelectionBody ? currentSelectionBody.value : null;

            // 3. Triggers callbacks on user action
            var addSelection = function(evt) {
                if (currentSelectionBody) {
                    args.onUpdateBody(currentSelectionBody, {
                        type: 'TextualBody',
                        purpose: args.purpose,
                        value: evt.target.value
                    }); 
                } else { 
                    args.onAppendBody({
                        type: 'TextualBody',  
                        purpose: args.purpose,
                        value: evt.target.value
                    });
                }
            }

            select.addEventListener('change', addSelection);
            if(currentSelectionBody != undefined) {
                select.value = currentSelectionBody.value;
            }

            select.className = 'select form-control'
            var container = document.createElement('div');
            container.className = "row m-2";
            var label = document.createElement('label');
            label.htmlFor = 'select_'+args.purpose;
            label.innerHTML =  args.label;
            container.appendChild(label);
            container.appendChild(select);

            return container
        }
```

I used a custom purpose to use it multiple times. It's working quite nicely. Much smoother than my "hacky" way of a custom modal aroud.

The only thing that I haven't done yet is a remove button on the editor.
I know that the commenting widget comes with a dropdown menu to remove it, but I'm sure how to put it on my editor.

Now im gonna try and see if I can find a way to do a custom style to the <g>.

I'm thinking, as soon as the annotation creates or updates, to find it inside the layer by its id and the add a class to the <g>.
Is that the way?

**Comment by rsimon** [comment]
The remove button on the Comment widget is simply a button that triggers the `args.onRemoveBody(currentSelectionBody)` callback.

Regarding the style: should the style change depending on the selection? Only in this case you'd need to add a class dynamically. Otherwise, you can just apply style rules to, for example,  `div.row option`. Maybe put the CSS class of the editor before that. (Probably won't make much difference, but perhaps gives you a more readable stylesheet because it's clear that you are targeting an element inside the editor popup.)

```css
.r6o-editor div.row option {
  // styles for your option element go here...
}
```

**Comment by rsimon** [comment]
Relates to https://github.com/recogito/recogito-client-core/issues/42

**Comment by rsimon** [comment]
Looks like all requests on this thread have been answered.
