### ISSUE TITLE
Help getting started with React Hooks -v3

### ISSUE THREAD

**Issue by jeqermigselv-cloud** [annotorious/annotorious#434]
Hello everyone! I'm having trouble getting React hooks to work. I've gone through the documentation and app test files, but I can't seem to get it right. Since V3 is headless, I'm trying to create a custom popup, but I'm unable to capture the triggered events.

According to the documentation, I've tried:
```
const { selected, pointerEvent } = useSelection();
```
However, this doesn't seem to trigger on selection.

I've also attempted to use the vanilla annotation tool with the following code:
```
const anno = useAnnotator<AnnotoriousImageAnnotator>();
```
But it doesn't instantiate, and I get an "object undefined" error.

Does anyone have any code snippets or advice that could help? Thanks!

**Comment by rsimon** [comment]
It sounds like you might be missing the outer `<Annotorious>` context wrapper.

Also note that the selection hook now returns `{ selected, event }` (not pointerEvent). There are likely some other breaking changes upcoming before the official v3 gets published. But I'm hoping to work on the docs later this month. 

Also, did you see the popup helper component?

**Comment by jeqermigselv-cloud** [comment]
Hey @rsimon 

I did wrap it in the `<Annotorious> ` context wrapper as per below, but it still doesn't log it properly.

I am wondering if I am missing something obvious x_x
```
'use client'
import React, { useEffect } from "react";
import Image from "next/image";
import { Annotorious, ImageAnnotator, useSelection } from '@annotorious/react';
import '@annotorious/react/annotorious-react.css';
import gallery1 from '@assets/images/pages/img-gallery-1.jpg'

export default function Page() {

    const { selected, pointerEvent } = useSelection();

    useEffect(() => {
        console.log(selected);
        console.log(pointerEvent);
    }, [selected, pointerEvent])

    return (<>
        <React.Fragment>
            <Annotorious>
                <ImageAnnotator  >
                    <Image src={gallery1} width={500} height={500} alt="Feedback" priority />
                </ImageAnnotator>
            </Annotorious>
        </React.Fragment>
    </>)
}
```

![image](https://github.com/user-attachments/assets/b51ba8c5-acb8-470a-9394-ff874f03ac3d)

**Comment by rsimon** [comment]
Ok, that works. It's an empty selection. But it's now `event` rather than `pointerEvent`. Docs are lagging behind a bit, sorry.

**Comment by jeqermigselv-cloud** [comment]
Sorry, that console log was from my initial page load. It still does not trigger on events after the initial page load.

I did notice the error below on compilation - and maybe that is correlated to the missing trigger events?

I am using Next.js 14.2.5.

```
⨯ ReferenceError: window is not defined
    at __webpack_require__ (/home/jeqermigselv/Desktop/app/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/home/jeqermigselv/Desktop/app/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/feedback/[UUID]/page.tsx:11:76)
    at (ssr)/./src/app/feedback/[UUID]/page.tsx (/home/jeqermigselv/Desktop/app/.next/server/app/feedback/[UUID]/page.js:162:1)
    at Object.__webpack_require__ [as require] (/home/jeqermigselv/Desktop/app/.next/server/webpack-runtime.js:33:42)
    at JSON.parse (<anonymous>)
```

**Comment by rsimon** [comment]
It will only trigger if the selection changes. Is it not doing that?

Also, you are running the code on the server. (NextJS or similar?) That can't work, obviously. The code needs to run in the client only - that's what your window error indicates.

**Comment by jeqermigselv-cloud** [comment]
Gotcha, the `window is not defined` was solved by moving the annotator to its own component and lazy loading the component and disabling SSR:
```
const Annotator = dynamic(() => import('./Annotator'), {
  ssr: false,
})
```
But it still is not triggering on events.

I have replicated the issue here, I would appreciate if anyone knew what I did wrong

[https://stackblitz.com/edit/stackblitz-starters-ku9yra?file=app%2Fpage.tsx](https://stackblitz.com/edit/stackblitz-starters-ku9yra?file=app%2Fpage.tsx)

**Comment by rsimon** [comment]
Annotorious hooks will only work inside the `<Annotorious>` context. If you move the context into your main app component, they should work. Right now, you are trying to use it in the same component that's creating the context.

**Comment by jeqermigselv-cloud** [comment]
Yes, it works now - thanks a lot, @rsimon !!

**Comment by rsimon** [comment]
👍 Both SSR and not putting the context wrapper at the root are common gotchas. I'm just keeping this issue open as a reminder to add this to the docs.

**Comment by jeqermigselv-cloud** [comment]
Hi again!

Since you opened it again :D and has been very helpful already, then I am curious about what you meant with the below?
> Also, did you see the popup helper component?

Are you referring to the snippets here > https://github.com/annotorious/annotorious/issues/297 > https://github.com/annotorious/annotorious/blob/e2f378e75d41bdc7ae6fb0797923d8ce5f0a36f4/packages/annotorious-react/src/openseadragon/OpenSeadragonPopup.tsx?

**Comment by rsimon** [comment]
No, I meant [this component](https://github.com/annotorious/annotorious/blob/main/packages/annotorious-react/src/AnnotoriousPopup.tsx), which would give you a wrapper for your own popup elements. It might still be a bit buggy, but should handle the basic popup lifecycle & positioning for you.

(The [OpenSeadragon](https://github.com/annotorious/annotorious/blob/main/packages/annotorious-react/src/openseadragon/OpenSeadragonPopup.tsx) version is stable. But I think you're using the ImageAnnotator?)

**Comment by rsimon** [comment]
Closing this as documented here: https://annotorious.dev/react/hooks-reference/
