### ISSUE TITLE
Default type arg for hooks that return ImageAnnotations?

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious#438]
@oleksandr-danylchenko: I've just been [documenting the React hooks for the new website](https://annotorious.dev/react/hooks-reference/), and came across this:

https://github.com/annotorious/annotorious/blob/9bf0a618fb1b8dda1f457c3c6aae30de234140de/packages/annotorious-react/src/Annotorious.tsx#L123

I guess there's no harm in supplying a default type argument to all these hooks? E.g.

```ts
const useAnnotations = <T extends Annotation = ImageAnnotation>() 
```

I'm inclined to do this, since they'll mostly be returning image annotations (and downstream libraries can always supply their own types). I just wanted to quickly sound out what you think, since you've been working with this a lot!

**Comment by oleksandr-danylchenko** [comment]
Personally, I would have kept the `Annotorious` provider and its hooks generic and non-consumer-specific. Therefore providing the `Annotation` as a default type. 
Then the consumers like the `ImageAnnotator` will provide their specific types, using the hooks. As in my view the `Annotorious.tsx` provider still sits one abstraction layer higher than the `ImageAnnotator.tsx`.

**Comment by oleksandr-danylchenko** [comment]
> I've just been [documenting the React hooks for the new website](https://annotorious.dev/react/hooks-reference/), and came across this:

I also wanted to point out that the site looks magnificent, great work! 🔥

**Comment by rsimon** [comment]
> Personally, I would have kept the Annotorious provider and its hooks generic and non-consumer-specific. Therefore providing the Annotation as a default type.

I would agree if these hooks were in some kind of core package. But given the way things are currently organized, it's the `@annotorious/react` package that library consumers use directly. If we used `Annotation` as the default type, every user would have to explicitly provide the `ImageAnnotation` type themselves.

```ts
const annotations = useAnnotations<ImageAnnotation>();

// vs. 

const annotations = useAnnotations();
```

The first option would feel kind of redundant, if I were using Annotorious in the "basic" way (= to build an image annotation app, not to extend the library).

What I agree we should definitely __NOT__ do is this:

```
const useAnnotations = <T extends ImageAnnotation>();
```

The base type should always be Annotation, to facilitate text annotations and other extensions. But if we leave `ImageAnnotation` as the default type, IMO the experience for the average developer is a bit better, while at the same time there would nothing that keeps other libraries from overriding the type with anything that extends Annotation.

**Comment by oleksandr-danylchenko** [comment]
On the second though... It makes sense to apply the default type in the scope of the `@annotorious/react` to improve the DX and simplify declarations there. Also, it doesn't impact the use of the `text-annotator` because we've already been providing `TextAnnotation` generic everywhere.

Also... It still leaves the "improvement area" for the `text-annotator` DX, where we can re-export the `Annotorious` hooks with pre-supplied `TextAnnotation` type, making lives easier there too.

**Comment by rsimon** [comment]
Exactly - the `text-annotator` could re-export its own copy of the hooks, with the re-supplied `TextAnnotation` type, as you say.

I'll make that change then. Looks like Annotorious v3.0.1 is almost on the way ;-)
