### ISSUE TITLE
Setting panel class

### ISSUE THREAD

**Issue by technbuzz** [annotorious/annotorious#446]
Is there a way to add panel class to root element for specifying pointer style or other layout styles?

**Comment by rsimon** [comment]
Which version of Annotorious are you using? (v2.7 or 3.0? Standard images or OpenSeadragon?) For the time being, you'd have to grab a handle to the wrapper element directly, and add css classes yourself. For the image version, it's available as a property of the annotator: `anno.element`. For the React version, there's a [containerClassName](https://github.com/annotorious/annotorious/blob/main/packages/annotorious-react/src/ImageAnnotator.tsx#L10) prop.

**Comment by technbuzz** [comment]
I am using the version 3.0. It's my bad I see the anno instance does have this property. 
Usually we set the panel class in config object but it works.

Thanks for all the work. I would definitely support to keep the project up.
