### ISSUE TITLE
Really full featured and precise polygon tool

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious#45]
The current poly drawing tool is really just a minimum viable product. We need a full featured tool that:

- is touch compatible
- works on click-and-drag as well as click (then move and click again)
- supports adding/removing points
- provides a good crosshair cursor on all platforms

**Comment by AIVinci** [comment]
Hi @rsimon, any updates on this ?

**Comment by sriramreddyM** [comment]
anything about adding/removing points in polygon tool?

**Comment by rsimon** [comment]
Still not yet, I'm afraid. But it *is* still on the list. (And creeping up the priority ladder, since most other essential features + bugs have been addressed.)

**Comment by rsimon** [comment]
In case anyone is still waiting for this: this is now moving up the priority list. Should be there before end July at the latest.

**Comment by rsimon** [comment]
See also #151

**Comment by rsimon** [comment]
Just a quick update that work is now underway on this here:
- https://github.com/recogito/recogito-client-plugins/issues/15
