### ISSUE TITLE
how to set some default properties when starting to draw

### ISSUE THREAD

**Issue by Zddu** [annotorious/annotorious#461]
I want to set some default values in properties when drawing a rectangle every [time.Is](http://time.is/) there a way to do it？thanks！

**Comment by rsimon** [comment]
Can you be more specific? What is it that you are trying to achieve? What properties or behavior would you like to set? 

Also: please provide the version (2 or 3), package (vanilla, React) and image type (standard, OpenSeadragon) you are using.
