### ISSUE TITLE
updateAnnotation event fires many times

### ISSUE THREAD

**Issue by SuhaibMaraqa** [annotorious/annotorious#462]
I am working with "@annotorious/react": "^3.0.11", When I move the annotation the updateAnnotation event get triggered, but it get fired way too many times: 

<img width="708" alt="Screenshot 2024-10-28 at 10 13 35 AM" src="https://github.com/user-attachments/assets/d7a57e47-a3b1-4460-bc36-ee40995cb7b7">

I need the event to call an API to update the annotation with the new bounds, and with this the api will get called 100 times.

```
const AnnotatableImage: FC<IProps> = ({ drawingEnabled, url, setDrawingEnabled }) => {
 const anno = useAnnotator();

  anno?.on('updateAnnotation', (updated, previous) => {
    console.log('Annotation was updated.');
  });

 const style = (annotation: ImageAnnotation, state: AnnotationState) => {
    const color = annotation.bodies.find(body => body.purpose === 'color')?.value;

    return {
      fill: color,
      stroke: color,
      strokeWidth: 4,
      fillOpacity: 0.25,
    } as DrawingStyle;
  };

  return (
    <OpenSeadragonAnnotator
      style={style as DrawingStyle}
      tool='rectangle'
      drawingEnabled={drawingEnabled}
      drawingMode='click'
      userSelectAction={UserSelectAction.EDIT}
    >
      <OpenSeadragonViewer
        ref={osdViewerRef}
        className='h-3/4'
        options={{
          prefixUrl: '//openseadragon.github.io/openseadragon/images/',
          showNavigationControl: true,
          animationTime: 0.15,
          blendTime: 0.1,
          gestureSettingsMouse: {
            clickToZoom: false,
            scrollToZoom: true,
            dblClickToZoom: false,
          },
          showNavigator: false,
          sequenceMode: true,
          showSequenceControl: false,
          showReferenceStrip: false,
          showZoomControl: false,
          showFullPageControl: false,
          showHomeControl: false,
          constrainDuringPan: true,
          visibilityRatio: 0.8,
          defaultZoomLevel: 0.675,
          maxZoomPixelRatio: 10,
          autoHideControls: false,
          preserveViewport: true,
          tileSources: {
            type: 'image',
            url: url,
          },
        }}
      />

      <OpenSeadragonAnnotationPopup
        popup={props => (
          <AnnotationPopup
            annotation={props.annotation}
            onCreateBody={body => props.onCreateBody(body)}
            onUpdateBody={(current, next) => props.onUpdateBody(current, next)}
          />
        )}
      />
    </OpenSeadragonAnnotator>
  );
}
```

**Comment by rsimon** [comment]
You need to add the handler in an effect, when the component mounts. What you're doing in your code is to mount a new event listener every time your component re-renders.

The event doesn't fire multiple times. You have multiple listeners registered.

**Comment by SuhaibMaraqa** [comment]
Thank you @rsimon, I have another issue explained in the video below:

https://github.com/user-attachments/assets/6832a418-908c-4aec-b551-e4cb87738ef3

when positioning an annotation below the popup, the user can't move it again, is there an option for the popup or something to solve this issue ?

**Comment by rsimon** [comment]
Sorry, there are no customization options for the popup at the moment. But some might come in the future. (I'm using floating-ui underneath the hood.)

Personally, however, I'd recommend against using popups if the plan is to enter lots of data. A sidebar often provides better use of space in this case.
