### ISSUE TITLE
W3CAdapter for OpenSeadragonAnnotator in React does not seem to apply

### ISSUE THREAD

**Issue by TomDijkema** [annotorious/annotorious#468]
**Which version of Annotorious are you using?**
Please provide:
- package: `@annotorious/react`
- version number: 3.0.11

**Issue behavior**
Hi Simon, lately the W3C-Adapter has not been working for my local Annotorious setup in React, using the latest version.
I followed the updated docs and imported the W3CImageFormat from '@annotorious/react' and applied it to the OpenSeadragonAnnotator, example:

```
OpenSeadragonAnnotator adapter={W3CImageFormat('https://iiif.bodleian.ox.ac.uk/iiif/image/af315e66-6a85-445b-9e26-012f729fc49c')}
          drawingEnabled={annotoriousMode === 'draw'}
          drawingMode='click'
          tool="rectangle"
>
           <OpenSeadragonViewer options={osdOptions}
                  className="h-100 bgc-grey-light"
            />

            <OpenSeadragonAnnotationPopup popup={() => (
                  <ImagePopup annotations={annotations}
                            SubmitAnnotation={SubmitAnnotation}
                  />
             )}
             />
</OpenSeadragonAnnotator>
```
The adapter does not seem to apply as all of the annotations created on the canvas keep their original format according to the internal Annotorious data model.

Any idea what could be the issue?

Best,

Tom

**Comment by rsimon** [comment]
The adapter will only affect the "outer" API, i.e. the lifecycle events listed [here](https://annotorious.dev/api-reference/events/). 

Are you using the internal state, perhaps? (`anno.state.store` etc.?) The internal state will always work with the internal data model. The crosswalk is only applied "at the edges", so to speak.

**Comment by TomDijkema** [comment]
Ah ok, tested it with the outer API and yes, it indeed returns a W3CAnnotation.
Thanks then I will have to change the workflow a bit by saving the selected annotation in a state variable, instead of retrieving it from the annotoriousSelection hook.

So the hooks like the annotoriousSelection hook are part of the internal API and always return the annotations according to the internal data model, good to know :+1: .

**Comment by TomDijkema** [comment]
No bug present, intentional behaviour

**Comment by rsimon** [comment]
Yes, that's the behavior at the moment. I guess the hooks _could_ use the crosswalk. But it would potentially introduce a lot of extra crosswalking overhead. Up for discussion, for the future :-)
