### ISSUE TITLE
`arrow` prop of `ImageAnnotationPopup` not being respected

### ISSUE THREAD

**Issue by piedrahitapablo** [annotorious/annotorious#481]
**Which version of Annotorious are you using?**
Please provide:
- package: @annotorious/react
- version number: ^3.0.11

**Issue behavior**
The `ImageAnnotationPopup` receives an `arrow` prop that is boolean. I assume this is to hide/show the arrow svg on top of the annotation popup, but the prop is not being used. See [here](https://github.com/annotorious/annotorious/blob/main/packages/annotorious-react/src/ImageAnnotationPopup.tsx#L45). I'm not sure if this is the expected behavior or the prop is intended for another use.

Thanks!

**Comment by rsimon** [comment]
Yikes - indeed, thanks for spotting. Fixed!
