### ISSUE TITLE
<circle> attribute r: Expected length, "Infinity". <rect> attribute x: Expected length, "-Infinity".

### ISSUE THREAD

**Issue by SaqifHaque** [annotorious/annotorious#484]
Uploading Screen Recording 2024-12-06 at 14.39.41 (online-video-cutter.com) (1).mp4…

**Which version of Annotorious are you using?**

- package (`@annotorious/annotorious`)
- 3.0.19

**Issue behavior**
when i create a mutiple rectangle in a modal and close it 
it triggers this error and i dun get any annotations using get annotations function

**Screenshots**
<img width="1408" alt="Screenshot 2024-12-06 at 14 45 46" src="https://github.com/user-attachments/assets/511bdd25-d363-43d1-ae8a-04ba0f4751f3">

**Comment by rsimon** [comment]
Hi, the screenshot failed to upload. Can you re-upload? Or paste the console error message? 

Given that you are using a modal, this sounds like it might be a timing issue.

**Comment by SaqifHaque** [comment]
let me check what might be the issue 
its no uploading

**Comment by SaqifHaque** [comment]
i have uploaded the picture

**Comment by SaqifHaque** [comment]
This Issue happens when i try to close the modal without deselecting the shape and i have tried autoSave and setSelected while closing the modal doesn't seem to be working

**Comment by SaqifHaque** [comment]
also There is another issue on initial load when i select the shape the selected css doesn't work 
when i close the modal and reopen again then the css changes for selected works

**Comment by SaqifHaque** [comment]
the problem was fixed it seemed to be a timing issue but on initial load i can edit the annotorious syntax but the selection border doesn't show
