### ISSUE TITLE
Annotation Selection Border Not Displayed During Annotation Selection

### ISSUE THREAD

**Issue by SaqifHaque** [annotorious/annotorious#490]
**Which version of Annotorious are you using?**
Please provide:
- package `@annotorious/annotorious`
- 3.0.19

**Issue behavior**
on initial load the pointer events doesn't seem to work for some reason. When i select the annotation the border doesn't show. 
it only shows when i try to change screen breakpoint or when i trigger display none and display show. What might be the issue?

**Screenshots**

**Comment by rsimon** [comment]
I cannot reproduce this behavior under normal conditions. Can you provide a minimal reproducible test case on codesandbox or similar?

**Comment by SaqifHaque** [comment]
i have fixed it. 
sorry for the inconvenience i think some other css in my environment was causing the issue.
