### ISSUE TITLE
Footer class conflicts with Bootstrap

### ISSUE THREAD

**Issue by oztexan** [annotorious/annotorious#50]
Great tool, just timeboxed adding to our app.  Unfortunately the pop up editor uses a class called "footer" which conflicts with a Bootstrap class of the same name.  I edited code in min.js just as work around.  Might be worth changing footer to annofooter or some such to improve Bootstrap interop.

**Comment by rsimon** [comment]
Thanks for reporting! Indeed, some classes are prefixed (`a9s` or `r6o` where things are imported from the Recogito base library). But we need to be more consistent... I'll add this for the next release.

**Comment by rsimon** [comment]
All CSS classes are now properly prefixed (either with `a9s-` for Annotorious-specific elements or `r6o-` for everything imported from Recogito core).
