### ISSUE TITLE
Div wrapper remains on destroy

### ISSUE THREAD

**Issue by allilocherNEA** [annotorious/annotorious#51]
Destroying annotation layer does not remove the wrapper div that is created. 

See original html:
![image](https://user-images.githubusercontent.com/69905286/90637896-94a2eb00-e1fa-11ea-9a75-a17185a2ca5e.png)

and the inspected html after calling anno.destroy()
![image](https://user-images.githubusercontent.com/69905286/90637971-aedcc900-e1fa-11ea-9976-f72b9f4325b5.png)

**Comment by rsimon** [comment]
Thanks for reporting! This should now be fixed in the master branch. (An updated release is likely coming this weekend, if I can find the time.)
