### ISSUE TITLE
Bug after polygon drawing

### ISSUE THREAD

**Issue by ufuk23** [annotorious/annotorious#53]
There is a bug after the polygon drawing while clicking the cancel button on the editor panel. I draw a polygon then the editor panel appears and when I click the cancel button the editor panel disappears but the polygon does not. The polygon still appears even if clicking the cancel button. The same steps work while drawing a rectangle, but it doesn't work by drawing a polygon.

Could you fix this bug, please?

(tested with chrome browser)

**Comment by rsimon** [comment]
Thanks for reporting. This bug is already fixed in the master branch (which is newer than the latest release). I can hopefully publish a new release, including this fix, to npm this weekend or the next.

Meanwhile, if you need the fix before: you can already build your own min.js file from the master branch source.

**Comment by ufuk23** [comment]
I will be appreciated for that. Actually I need the fix for "annotorious-openseadragon" branch and I reported the same issue for "annotorious-openseadragon" as well. I am not familiar with npm. I install the npm and build the project but I have no source file yet. After the build, the source files I have are still obfuscated like min.js files.

**Comment by rsimon** [comment]
The code is shared between Annotorious and AnnotoriousOSD, the next releases will both include the fix.

The npm build process won't give you unobfuscated files. After running `npm run build` the bundled release will be in the `/dist` folder. What are you trying to achieve with an "unobfuscated" file? If you want to make a change to the source code, you can just do that, and rebuild. Or am I missing something?

**Comment by ufuk23** [comment]
Ok I see the src files and dist files. What I am trying to do is 

- when the mouse is over the polygon/rectangle I want to show the editor popup like previous versions of annotorius
- I need to draw a line just like the polygon drawing

But I don't know which file I should change and how to do it. There are some files such as "OSDAnnotationLayer.js", "index.js", "SVCConst.js" in the src folder. I could draw a line by changing the "annotorious-openseadragon.js" which is unminified, I replaced the dblclick events to click events and could draw a line instead of the polygon. Now I want 3 features for drawing line, polygon and rectangle, and now it is hard to do it for me :)

**Comment by rsimon** [comment]
Ok I understand. Sorry - having an unminified file won't help you much. You will need to read through the existing code and understand what it does first. I'm afraid that none of your changes are "beginner-level" things, that just require a few quick hacks. Of course it's not magic either - you'll just need to be prepared to spend a bit of time ;-)

To get started, follow the basic developer guidelines here:
https://recogito.github.io/guides/development-setup/

Drawing tools (like the rectangle and polygon) are located here in the source code:
https://github.com/recogito/annotorious/tree/master/src/tools

See, for example the `rectangle` folder. It has three different source files:
- `RubberbandRect.js` handles the drawing of a "fresh" shape (when the user is starting a new annotation)
- `EditableRect.js` handles the drawing and manipulation of an existing shape (when the user selects an existing annotation and wants to modify it)
- `RubberbandRectTool.js` is the actual entry point into the drawing tool. It handles the lifecycle, and must implement a few methods common to all drawing tools, e.g. `startDrawing`, `stop` etc. These enable communication with the rest of Annotorious.

I'd suggest the following:
- check out the Annotorious project first (not Annotorious OSD), and get it running in development mode [as explained in the dev guide](https://recogito.github.io/guides/development-setup/)
- then try to start a basic line drawing tool based on the example of RubberbandRectTool (or RubberbandPolygonTool) and RubberbandRect (RubberbandPolygon)

You can skip the editable shape if you don't need lines to be editable after creation. Once you have things working in Annotorious, you are 90% there. I can help with the steps to get it working in Annotorious OpenSeadragon.

**Comment by ufuk23** [comment]
Thanks for your help. Yes I know I should have some time but I am not sure I have enough time to do that. You mean that I should create RubberbandLine.js, EdtableLine.js, RubberBandLineTool.js into the annotorious project, and build that project via npm. So I will consider this development. If I do these customizations I will lost your master branch developments, and I have to do my customizations again for each next version in the future. Maybe we can develop it together. Could you consider to add a line drawing feature in the next versions? If it is it will be great:)

**Comment by rsimon** [comment]
Exactly, you'd need to develop your own RubberbandLine and RubberbandLineTool. You could skip the EditableLine for now. This way users could create and delete lines, but not modify existing ones. (You could still add that later in the future.)

If you fork the project from https://github.com/recogito/annotorious to your own GitHub account, you can contribute your addtions back to the main code [via a pull request](https://yangsu.github.io/pull-request-tutorial/). This way, everybody benefits from your addition, and future releases of Annotorious can include it.

**Comment by ufuk23** [comment]
Ok, I created the RubberbandLine and RubberbandLineTool files, tested after the npm build annotorious.min.js works perfectly :) The line tool is working as I expected. I forked the project to my own Github as you said. Now how can I use my annotorious.min.js file including line tool for annotorious-openseadragon project ? Could you please help me?

**Comment by rsimon** [comment]
Great! First: I'd definitely recommend finishing the implementation & making line drawing work in normal Annotorious first. Only at the end, you need to go through the final steps to make it work in Annotorious OpenSeadragon.

Once everything is working in Annotorious, run 

```shell
npm run build 
```

in the annotorious directory. Then you are ready to link this into AnnotoriousOSD.

Normally, AnnotoriousOSD imports code from the latest offical published release. You now need to change this, so that your local AnnotoriousOSD project imports from your modfied Annotorious project instead. Here's what you need to do:

```shell
$ cd annotorious
$ npm link # this makes your local annotorious project available as an npm module
$ cd ..
$ cd annotorious-openseadragon
$ npm install # download all external project dependencies
$ npm link @recogito/annotorious # this replaces the official annotorious release with your modified version
$ npm start
```
When your AnnotoriousOSD project starts in development mode, it now pulls code from your modified Annotorious project.

Finally, you can run

```shell
$ npm run build
```

in your AnnotoriousOSD folder, and will find the final JS build in the /dist.
