### ISSUE TITLE
problem "readOnly"

### ISSUE THREAD

**Issue by mynhidwotz** [annotorious/annotorious#55]
Hi,
When using the "readOnly" parameter, the following error is displayed: "**Uncaught TypeError: n.join is not a function**"

`  const anno = new Annotorious({
          image: this.photo.id, 
          readOnly: true,
        })`

https://codesandbox.io/s/dreamy-smoke-iw63p?file=/src/components/PhotoDetail.vue

path->  /src/components/PhotoDetail.vue

Please help, thank you!

**Comment by rsimon** [comment]
Thanks for reporting! I could reproduce this & fix it in the master branch. Will go live with the next release.
