### ISSUE TITLE
Close editor when clicking outside

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious#56]

**Comment by rsimon** [comment]
Clicking outside closes the editor. However, clicking on a different shape also closes. Instead it should directly open the editor on the new shape.

**Comment by adroit91** [comment]
Hi @rsimon 
With the latest version, even if I click outside the editing box, it doesn't close. I'm using latest build of Chrome on Mac.

**Comment by rsimon** [comment]
Are you reporting for "standard" Annotorious? Or the OpenSeadragon plugin? (Click outside only closes for the standard version, the feature isn't implemented in the OpenSeadragon plugin yet.)

For the standard version, it looks like this is working on Chrome + FF.

**Comment by adroit91** [comment]
I'm using standard (stand-alone?) Annotorious. I can continue to interact with the rest of the page, and the widget doesn't close on it's own. If there's some direction regarding what portion of the code to look at to debug, I'd be glad to do that.

**Comment by rsimon** [comment]
That's weird. Is interaction with Annotorious still working? Does the error console say anything?

The trigger for selection is basically this one:
https://github.com/recogito/annotorious/blob/main/src/AnnotationLayer.js#L47

(Whenever you click on the image, the current drawing tools goes active. If you release the mouse immediately - rather than keeping the mouse down and dragging - the drawing tool fires a cancel event, and the `AnnotationLayer` selects the last annotation the mouse has been hovering over.)

**Comment by adroit91** [comment]
Everything else works well, but if I leave the widget hanging, and click on other portions of the web page (nothing to do with Annotorious, but the image changes, for example as a result of the click), the widget stays on top. I will try to see if something in the file you shared helps me. Will share here too, if I find it's a bug rather than a mistake I've done.

**Comment by rsimon** [comment]
> and click on other portions of the web page

Ah that's an important point :-) Yes Annotorious will listen to clicks __outside__ of the current selection, but __inside__ the current image. Clicks outside won't register. I guess there are pros and cons to closing the editor on click outside the image. But that, at least would be fairly easy to change. You'd currently have to change in multiple places (once for each drawing tool). But in principle, you'd only need to attach the listener to the document rather than the SVG annotation layer.

Here's where this is done for the Rectangle Tool. (You'd simply need to repeat for the Polygon tool, in the same place.)

https://github.com/recogito/annotorious/blob/main/src/tools/rectangle/RubberbandRectTool.js#L21-L29

**Comment by rsimon** [comment]
Concerning your second about, about changing the image. Two ideas:

- If you are programmatically changing the image, you can simply delete all Annotation using `anno.clearAnnotations` (this will also close the editor). (At least I'm assuming that the new image has nothing to do with the old one, and would have different annotations? E.g. in the case of an image carousel?)

- Speaking of image carousels etc.: if you wrap the image in a container DIV, Annotorious will attach itself __inside__ the container. Therefore, if you want to remove, change, animate etc. the image (e.g. like sliding it in a carousel), you should manipulate the container rather than the image itself. That will make sure that Annotorious stays attached, and the annotations remain in sync while you animate the position (and/or size) of the image.

**Comment by adroit91** [comment]
Thanks a lot for those pointers. Helps a lot. Will try out attaching the listener to the document.
Cheers!

**Comment by adroit91** [comment]
I was able to use my own document level listener to do this (not inside Annotorious code). But, `clearAnnotations` for ImageAnnotator.jsx might not exist. I achieved success with `anno.cancelSelected()`. It's working fine for me now.

Thanks a lot!

**Comment by rsimon** [comment]
Cool - good to hear it works.

That's right, `clearAnnotations` doesn't exist on the ImageAnnotator class. It's a convenience method on the "outside" API (`index.js`), which then just calls `.setAnnotations([])` on the ImageAnnotator (cf. https://github.com/recogito/annotorious/blob/main/src/index.js#L113-L114).
