### ISSUE TITLE
SeaDragon plugin — after selection is created, shift key should be disabled

### ISSUE THREAD

**Issue by chchch** [annotorious/annotorious#58]
After you have drawn a rectangle, if you click SHIFT again, then it tries to make another selection, but it doesn't cancel the previous selection. You end up with yellow boxes with no annotations that can't be deleted.

I wanted to fix this quickly by using the createSelection hook, but it's unavailable in the SeaDragon plugin.

**Comment by rsimon** [comment]
Ah - good catch. Thanks for reporting. You can't (cleanly) fix this from outside I think. But I'll put it on the list. Should be just a one-liner & available with the next release. (Feel free to also create an issue for the 'createSelection' event. Indeed that doesn't exist on the OpenSeadragon plugin. That always lags behind a bit the "standard" Annotorious version with regard to feature development.)
