### ISSUE TITLE
load annotations from JSON string

### ISSUE THREAD

**Issue by chchch** [annotorious/annotorious#59]
Hi,

I wanted to load annotations from a string rather than a URL (i.e., it'll be a JSON file that the user will select from their computer). I didn't see anything in the API that allows me to do this, so I added a quick function:

`loadAnnotationsString = s => {
    const annotations = JSON.parse(s).map(a => new WebAnnotation(a));
    this._app.current.setAnnotations(annotations);
    return annotations;
  });` 

Not sure if there's a better way to do this. Thanks!

**Comment by rsimon** [comment]
That method exists already, it's called .setAnnotations:
https://recogito.github.io/annotorious/api-docs/annotorious/#setannotations

Also for the OpenSeadragon plugin here:
https://recogito.github.io/annotorious/api-docs/osd-plugin/#setannotations

**Comment by chchch** [comment]
Ah ok, thanks. I thought that setAnnotations had to take an array of WebAnnotation objects.

**Comment by rsimon** [comment]
You have to parse the JSON string to a JS object before handing it to `setAnnotations`. A string isn't directly supported.
