### ISSUE TITLE
Missing translations on strings

### ISSUE THREAD

**Issue by ricardoroth** [annotorious/annotorious#64]
![image](https://user-images.githubusercontent.com/9203988/97367417-ab0a9a00-186e-11eb-828f-e3288f163276.png)

Only some texts are translated with the locale option changed to "es". 
Missing translations:
Edit -> Editar
Delete -> Eliminar
All time indications (minutes ago...)

**Comment by rsimon** [comment]
Thanks for spotting! Indeed, those two labels were missing translations. I fixed that just now, based on your input.

Ah, the time indications. Indeed, these are also missing translations altogether. I'll look into it.

**Comment by rsimon** [comment]
This is now fixed in the master branch of [recogito-client-core](https://github.com/recogito/recogito-client-core) and will be available with the next releases of Annotorious, AnnotoriousOSD and RecogitoJS.
