### ISSUE TITLE
Close Editor when pressing Escape

### ISSUE THREAD

**Issue by ufuk23** [annotorious/annotorious#68]
I realized that we can draw tools while just pressing the SHIFT button. That is so useful. Could you add a listener to close the editor popup when we press ESC? I think that would be another useful feature. So we can use the SHIFT button to draw and the ESC button to cancel the annotation quickly.

**Comment by abrlam** [comment]
@rsimon, I noticed there's a listener for ESC in [headless mode](https://github.com/recogito/annotorious/blob/cecb37c32b1016f6cc161c80c34736fc3e834252/src/ImageAnnotator.jsx#L45). Is it possible to remove the check so the listener works in both modes?

**Comment by rsimon** [comment]
Ah - good point :-) yes, I think there's nothing that speaks against enabling this generally.
