### ISSUE TITLE
Can't get tag suggestions to work

### ISSUE THREAD

**Issue by crees** [annotorious/annotorious#70]
Hello,

Is there something special I have to do to get tags to be suggested?  I only get a text input for the tags.

```
<script>
    (function() {
      var anno = Annotorious.init({
        image: 'testpage',
        locale: 'auto',
    	widgets: [
            'COMMENT',
            { widget: 'TAG', vocabulary: ['Animal', 'Building', 'Waterbody'] }
          ]
      });

      //anno.loadAnnotations('annotations.w3c.json');
    })()
</script>
```
![image](https://user-images.githubusercontent.com/945347/99447949-43001e80-2917-11eb-90ab-91a93e0750cd.png)

**Comment by rsimon** [comment]
It's an autocomplete. Did you try typing? 'a' should bring up the 'Animal' suggestion, for example. If you want to get all suggestions __without__ typing anything, hit the arrow-down key. This seems to work in the current release and master branch.

**Comment by crees** [comment]
D'oh, thanks a lot.
