### ISSUE TITLE
Editor not working properly on Firefox, bug introduced on version 2.1.7

### ISSUE THREAD

**Issue by georgioskap** [annotorious/annotorious#74]
Hi the editor doesn't work on Firefox properly. Most of the times it appears outside the image and far away from the selection rectangle. I tested using the Release Tag zips (and the provided example with Hallstatt image) going backwards from current release and it looks like the bug was introduced on v2.1.7. I would have tried to fix it and submit a Pull request but my JS is only basic.

![Editor Issue](https://user-images.githubusercontent.com/7262119/104181756-fec16400-5417-11eb-8d59-2e4e101ebac2.png)

**Comment by georgioskap** [comment]
Also, just realised that this is the case for high resolutions. I am working on 4K (3840x2160). When downgrading to 1920x1080 it works fine. Chrome and Edge are working fine irrespective of the screen resolution.

**Comment by rsimon** [comment]
Interesting... thanks for reporting! Just to confirm: high-res is the only situation where this occurs, right? (Must have something to do with the device pixel ratio then...)

**Comment by georgioskap** [comment]
I just did a bit more testing. Problem also occurs on 1920x1080 and (for the Hallstatt image I tested) from when the browser height (I checked quickly using window.innerHeight on Console) goes above 730 or something. Initially, selections towards the top of the image have their editor placed incorrectly, but as you increase browser height, more areas of the image are affected.

**Comment by rsimon** [comment]
Ok, thanks - I can reproduce it. Happens only in FF, and only when the popup is in the normal, downwards position. I'll investigate!
