### ISSUE TITLE
Using portal for the editor

### ISSUE THREAD

**Issue by fcollonval** [annotorious/annotorious#76]
Hey, thanks for this great tool.

I'm trying to create a [Jupyter Widget](ipywidgets.readthedocs.io) to integrate this annotation tool in [Jupyter Notebook](https://jupyter.org/). Unfortunately I'm facing CSS styling issue. Due to the DOM structure, the editor is not on top of the other nodes due to the stacking rules of child within positionned parent (https://coder-coder.com/z-index-isnt-working/)

![image](https://user-images.githubusercontent.com/8435071/105037165-dc55c900-5a5d-11eb-9fae-c727938fcab4.png)

I think rendering the editor in a portal attach directly to the body will solve it - what do you think?

The code is available at https://github.com/fcollonval/ipannotoryous

**Comment by rsimon** [comment]
Wow - Annotorious in Jupyter Notebooks? That's excellent! :-) Attaching the editor to the body directly could probably solve this particular issue, true, but creates a bunch of other positioning issues. (I've tried ;-)

However I don't think that's a z-index issue. Looks more like the DOM element Annotorious is attached to has `overflow` set to `hidden`. It might be possible to override this with `overflow: visible !important`, which would allow the Annotorious components to exceed outside of the bounds of their container element.

Do you have a sample Notebook online anywhere?

**Comment by fcollonval** [comment]
Awesome!

![image](https://user-images.githubusercontent.com/8435071/105068651-7a0ebf80-5a81-11eb-8032-2d6b0bdead62.png)

That did it. Thanks a lot for the suggestion.

> there is an example in the `examples` folder in the GitHub repository.

**Comment by rsimon** [comment]
Great to see this works!

I tried to get the sample running from the repo, but couldn't get the development install working for some reason (but probably due to me lacking sufficient Python skills...).

Out of interest: what is going to be the primary use case for this? Are you planning to use this in relation to ML and machine learning? If so, perhaps of interest: there is a new `.getSelectedImageSnippet()` method in Annotorious (and Annotorious OpenSeadragon) which returns a Canvas element with the selected image area (and the image data rendered to the Canvas). It's not documented yet. Do let me know if this is of interest to you and I can provide details.

**Comment by fcollonval** [comment]
I set up a link for online testing: https://mybinder.org/v2/gh/fcollonval/ipannotoryous/master?filepath=examples/introduction.ipynb

The overflow trouble is still present (for the correction I changed too much styling - I need to set up smart tuning for allowing overflow on parent containers).

> Out of interest: what is going to be the primary use case for this? Are you planning to use this in relation to ML and machine learning?

Yes, the tool will be used internally by our image research team. The annotations are then mainly processed by OCR and/or machine learning analysis.

> If so, perhaps of interest: there is a new .getSelectedImageSnippet() method in Annotorious (and Annotorious OpenSeadragon) which returns a Canvas element with the selected image area (and the image data rendered to the Canvas). It's not documented yet. Do let me know if this is of interest to you and I can provide details.

Amazing, that will definitely be handy
