### ISSUE TITLE
Colors for Rectangle

### ISSUE THREAD

**Issue by Nithinbs18** [annotorious/annotorious#81]
Dear team,

Greetings!!

I am quite new to using Annotorious, I wanted to know if there is a way to add different colours to the different set of tags. 
Something like in the below image;
![2021-02-11_12h13_07](https://user-images.githubusercontent.com/44024922/107629591-a245a480-6c62-11eb-8fae-8f8b5ef301dd.png)
I looked it up for a while but found no concrete solution. Any help on this is highly appreciated. 
Thanks.

Regards

**Comment by rsimon** [comment]
Yes, there is - [formatters](https://recogito.github.io/annotorious/api-docs/annotorious/#formatters)!

What you would need to do is write your own formatter function that assigns, for example a CSS class based on the label you're storing in the annotation.

```js
var formatter = function(annotation) {

  var tagBodies = annotation.bodies.filter(function(body) {
    return body.type === 'TextualBody' && body.purpose === 'tagging';
  });

  // E.g. you could return the first tag, and Annotorious will add it as a CSS class name
  return tagBodies[0].value;
}

var anno = Annotorious.init({
  image: document.getElementyById('my-image'),
  locale: 'auto',
  formatter: formatter
});
```

And then add some CSS

```css
.a9s-annotation.MyTagA {
  stroke-width:4;
  stroke:red;
}

.a9s-annotation.MyTagB {
  stroke-width:2;
  stroke:green;
}
```

It does require a bit of plumbing on your own, but offers a lot of flexibility in return. Let me know if that works for you!

**Comment by rsimon** [comment]
P.S: placing a label like in your example above is currently not possible - but I'm planning to extend formatters for doing such things in the future.

**Comment by Nithinbs18** [comment]
Hi @rsimon Thanks for the response!! I have an additional question I use the OpenSeadragon-Annotorious, so is the below code the right approach of using the formatted?

```
var formatter = function (annotation) {
      var tagBodies = annotation.bodies.filter(function (body) {
        return body.type === "TextualBody" && body.purpose === "tagging";
      });
      return tagBodies[0].value;
    };
    const config = {
      formatter: formatter,
      widgets: [
        {
          widget: "TAG",
          vocabulary: ["Animal", "Animals", "Building", "Waterbody"],
        },
      ],
    };
    var anno = Annotorious(viewer, config);
```

Thanks in advance.

**Comment by rsimon** [comment]
Yes, that should work.

**Comment by Nithinbs18** [comment]
Okay got it coloured now, but CSS was a little tricky it did not work straight forward as you suggested I had to use;

```
.a9s-annotation .a9s-inner,
.a9s-annotation.red {
  stroke-width: 1;
  stroke: red;
}
```
For someone in future who has the same problems as me.
