### ISSUE TITLE
Suggestions of TAG widget being covered by COMMENT

### ISSUE THREAD

**Issue by jbogdani** [annotorious/annotorious#82]
Hello,
if TAG widget is listed before the COMMENT one, the last covers the `ul.downshift-1-menu` element. I guess setting z-index to `ul.downshift-1-menu` would fix the issue, as the images demonstrate.

Current behaviour:
![image](https://user-images.githubusercontent.com/1449293/107881606-4c346380-6ee5-11eb-95f4-f7db12c15c1c.png)

Expected behaviour
![image](https://user-images.githubusercontent.com/1449293/107881578-39ba2a00-6ee5-11eb-8a9f-52f23ce53169.png)

**Comment by rsimon** [comment]
Indeed - thanks for reporting & figuring out the solution! I added the fix just now: https://github.com/recogito/recogito-client-core/commit/23141325642b06f3849e0574d013b5d1204edd1b
