### ISSUE TITLE
Loading annotation with setAnnotations or addAnnotation prevents adding of new annotations

### ISSUE THREAD

**Issue by Nithinbs18** [annotorious/annotorious#83]
Hello,

I am working with Annotorious for a while now, I have a use case where I need to load annotations from a different source on to the image and also allow users to add additional tags.
I tried methods setAnnotations and addAnnotation for the same, but there are problems when I use these;

Problem with **addAnnotation**: it works fine but when there are labels with same tag value (i.e. w3 annotation-->body-->value) it only adds one bounding box to the image and all other annotations are not displayed.

Problem with **setAnnotations**: it displays all the bounding box including the ones with the same value in tags, also creating new bounding box is possible, but I have problems deleting the tags/bounding box after they are loaded, currently how I select the tag within the container and click the 'close' button to remove the tag and delete the box, when I do this a different bounding box with the same is deleted. Is there a better approach to delete the annotation? or any idea how to fix this?

https://user-images.githubusercontent.com/44024922/108364700-a6d80300-71f6-11eb-90e7-8d2e6818715a.mp4

Thank you very much in advance.

**Comment by rsimon** [comment]
I doubt this can be related to the bodies. What are you using for annotation IDs?

**Comment by Nithinbs18** [comment]
Hi,

Bounding boxes with the same name have the same ID, do you think that's causing this?

**Comment by rsimon** [comment]
Yes, that's very likely. You definitely have to have unique IDs for the annotations. (It doesn't matter what you use for IDs. Any string will do. Just make sure they are unique.)

**Comment by Nithinbs18** [comment]
Awesome, that works. Thank you very much for the swift reply you're amazing :)
One additional question I use annotorious with openseadragon is there any way that I could hide a bounding box based on tag value or ID or anything else?

**Comment by rsimon** [comment]
You could try using a [formatter function](https://recogito.github.io/annotorious/api-docs/annotorious/#formatters). Through the function, you can add your own CSS class, e.g. `hide`. And then apply a CSS rule `.hide { display:none; }`.

**Comment by Nithinbs18** [comment]
Okay, thanks will try it out I need it to work dynamically on user selection of a certain tag from the dropdown. If I figure it out I will post it here. Thanks again!!

**Comment by rsimon** [comment]
Then you could add the tag label as a CSS class. And then apply styles dynamically as the user chooses from the dropdown.

**Comment by Nithinbs18** [comment]
This is exactly what I am doing for box colours and borders, based on the tag labels the CSS classes are created dynamically and are assigned to the box each time when created, but now if I need to hide the existing the boxes I need to re-run the formatter function each time a dropdown is selected by the user. Is there a way to trigger the formatter function each time a selection is made?

**Comment by rsimon** [comment]
No the formatter is only going to run when the annotation is rendered. And actually there's no need to re-run it. What you can do instead:

- Add the labels as CSS classes, as you have done already
- You can get a handle on all annotation SVG shapes via JS, e.g. using `document.querySelector('.a9s-annotation');`
- When the user changes the dropdown, grab the selected annotation shapes, e.g. using `document.querySelector('.a9s-annotation.mytag');`
- Now you have references to all selected annotations, you can loop through them. E.g. first set `style.display = 'none';` on all except the `mytag` ones.

Another option would be to programmatically manipuate the stylesheet. Don't know off the top of my head how to do it, but it's easily possible. (I think searching StackOverlow for "dynamic style rules CSS" or whatever will have plenty of examples.)

Last but not least, you can always keep a copy of the annotation list in your own app, and then delete and re-add annotations to Annotorious as needed. (That's a bit hacky tough.)
