### ISSUE TITLE
Does not work with absolutely positioned image

### ISSUE THREAD

**Issue by AntonDriemin** [annotorious/annotorious#85]
In the example to this plugin, change the image
`<img id="hallstatt" src="640px-Hallstatt.jpg" />`
to 
`<img id="hallstatt" src="640px-Hallstatt.jpg" style="position:absolute;top:0px;left:0px;">`
and then refresh the page.
Result:
1. Image disappeared
2. Even if I find a workaround to keep the image visible, the plugin still not working.

**Comment by rsimon** [comment]
Hi,

yes, good point. It's not currently possible to use images with absolute positioning, I'm afraid. (The reason: Annotorious needs to wrap the image with a DIV, which will then automatically grow to the size of the image. If you use absolute position, you take the image out of the rendering order, which means Annotorious' wrapper div shrinks to a size of 0x0.)

If you need to work with absolute positioning, here's what you can do instead:

```html
<div style="position:absolute;top:0px;left:0px;">
  <img id="hallstatt" src="640px-Hallstatt.jpg">
</div>
```
This will allow you to position the image at an absolute position, while Annotorious can still wrap the image correctly.

P.S.: FWIW the same workaround is necessary if you want to apply CSS margin or padding to the image.
I think it would be possible to implement in

**Comment by rsimon** [comment]
P.P.S.: in the long run, Annotorious could support this by stripping all image styles and moving them to its own wrapper DIV instead. That would only work for styles directly added to the element, I think, not CSS style rules. I.e. probably not a robust approach either.

**Comment by AntonDriemin** [comment]
The idea in your example works perfectly, thank you so much for the quick response!
I think stripping all image styles is not possible, especially in the case of CSS:
`div img { width:100px }`
but I believe you can copy workaround to the documentation to add more value to the time you spend on this answer :)

**Comment by rsimon** [comment]
Added information about this issue to the 'Getting Started' section of the website.
