### ISSUE TITLE
Annotation positioning error

### ISSUE THREAD

**Issue by AntonDriemin** [annotorious/annotorious#86]
In your example, remove CSS
`img { max-width:100%;}`
and change image width:
`<img id="hallstatt" src="640px-Hallstatt.jpg" style="width:10000px">`
refresh the page and scroll right to the middle of image, and add new annotation.
![Screenshot_1_zoom25](https://user-images.githubusercontent.com/7961622/109210611-bedef200-77b5-11eb-8ba0-68437935eb1b.png)
![Screenshot_2_zoom100](https://user-images.githubusercontent.com/7961622/109210616-bf778880-77b5-11eb-9ef3-91f9f89fc948.png)

**Comment by rsimon** [comment]
Thanks for reporting I'll look into it. I'd you're looking to annotate 10.000 pixel wide images, you might also want to look into the OpenSeadragon version of Annotorious BTW.

**Comment by AntonDriemin** [comment]
p.s. I'm working on a project that visualizes microscope slides that contain, for example, 30x30 slides ~500px width each.
So, comments are applied on top of this layout. I was able to apply annotorious to the div instead of an image implementing this before initialize annotorious:
`
var main = $("#main-container");
$("#anno")[0].naturalWidth = main.width();
$("#anno")[0].naturalHeight = main.height();
$("#anno").width(main.width());
$("#anno").height(main.height());

`
OpenSeadragon with additional functionality is not something I need (or I should disable all additional stuff like icons, zooming, etc).
![Screenshot_s](https://user-images.githubusercontent.com/7961622/109213626-7e817300-77b9-11eb-8907-55aec0e1835f.png)

**Comment by AntonDriemin** [comment]
Upd.
Here:
`
            var r = e.getBoundingClientRect()
              , o = window
              , i = o.pageXOffset
              , a = o.pageYOffset;
            t.className = "r6o-editor",
            t.style.opacity = 1;
            var u = n.getBoundingClientRect()
              , c = u.left
              , s = u.top
              , l = u.right
              , f = u.height;
            t.style.top = "".concat(s + f - r.top, "px"),
            t.style.left = "".concat(c + i - r.left, "px");
            var p = t.getBoundingClientRect();
            if (p.right > window.innerWidth && (t.classList.add("align-right"),
            t.style.left = "".concat(l - p.width + i - r.left, "px")),
            p.bottom > window.innerHeight) {
                var d = s + a
                  , h = r.bottom + a;
                t.classList.add("align-bottom"),
                t.style.top = "auto",
                t.style.bottom = "".concat(h - d, "px")
            }

`
remove " - r.left" in both places (works for me in chromium)

**Comment by rsimon** [comment]
Fixed in https://github.com/recogito/recogito-client-core/commit/0c83d309a28882dc2041e5504e8c54d1e242099d
