### ISSUE TITLE
cancelSelected  event

### ISSUE THREAD

**Issue by gstoychev-despark** [annotorious/annotorious#87]
In the moment, selection of an existing annotation triggers a ``selectAnnotation`` event,  and the annotation is being re-rendered.
But when a selection is canceled, no event is triggered, and all of the annotations re-rendered.

Fire an event when a selection is canceled, i.e. when the editor cancel button is clicked, outside selection is clicked, etc.

This would be especially useful for when additional elements are being added to the SVG using ``annotation.id`` as grouping element in the ``DOM``.

Update: ( I've noticed that such event was introduced in 2.2.0, but it's only for ``headless`` mode)

**Comment by mfarre** [comment]
@rsimon we are also having problems with this. It would be fantastic if you could take a look. Thanks for your time!

**Comment by rsimon** [comment]
This is now available in the main branch. When the user hits 'Cancel', or clicks outside the annotation (which technically equals a  'Cancel'), Annotorious fires a `cancelSelected` event. The annotation that was selected before is provided as argument to the handler function.

```js
anno.on('cancelSelected', function(selected) {
  console.log('cancel', selected);
});
``` 

This behavior works both when the selection is canceled for an annotation that existed already, or when canceling a newly drawn selection. You can distinguish both cases by checking the `type` of the `selected` object, which will be either `Annotation` or `Selection`, respectively.

**Comment by rsimon** [comment]
P.S.: I'll issue an updated relase to npm later today or tomorrow!
