### ISSUE TITLE
.getAnnotations  error out when called from updateAnnotation event

### ISSUE THREAD

**Issue by gstoychev-despark** [annotorious/annotorious#88]
I've created a codesandbox where it can be checked:

https://codesandbox.io/s/mystifying-poincare-hcc8u?file=/src/index.js:199-215

**Comment by rsimon** [comment]
Thanks for reporting - I can reproduce this & will look into it.

**Comment by mfarre** [comment]
hello @rsimon!
We would love to use annotorious in one of our projects and this bug is blocking us to move forward. Do you know approximately when we can expect to have a bugfix? Thanks for the time that you put on this.
Miquel

**Comment by rsimon** [comment]
Hi @mfarre,

It's an issue with the sequence of the event flow (the event getting triggered too early, before stuff gets cleaned up internally). I just pushed a "fix" which resolves the issue. Frankly, I need to do a bit more testing to be sure that this fix doesn't have other unforeseen consequences :-) But for the immediate issue, it should help. Do let me know if you observe any other weird behavior after applying the fix!

Cheers,
R

**Comment by mfarre** [comment]
wow that was fast @rsimon, we will give it a shot right now

**Comment by gstoychev-despark** [comment]
Hey @rsimon,

I've just updated the package to the latest commit. It seams that the fix works - create, delete update (resize, move and change of tags) of annotations. :tada: 
Can you please create a release or add a tag to the latest commit so it's easier for testing. Currently I'm able to test this only locally and I need to manually call `yarn install &&  yarn build` in order to work.

Thanks in advance,
George

**Comment by rsimon** [comment]
Hi @gstoychev-despark, I'll issue a new release later today or tomorrow.

Cheers,
R
