### ISSUE TITLE
Weird interaction in demo page

### ISSUE THREAD

**Issue by PonteIneptique** [annotorious/annotorious#9]
Firefox 75.0 - Windows 10

When I start a rectangle outside the already drawn rectangle, as soon as I enter the first rectangle, selection goes wildly in other directions.

**Comment by rsimon** [comment]
Yikes - thanks, I can reproduce & think I have a vague idea what could be going on. Looks pretty bad though since there seems to be a significant difference between how Firefox and Chrome/Webkit handle mouse event offsets on SVG shapes... in any case, I'll investigate.

**Comment by rsimon** [comment]
Learned something today about leftover Internet Explorer events and modern Mozilla replacements. Anyways: this should be fixed now :-)

**Comment by PonteIneptique** [comment]
YAY ;)
