### ISSUE TITLE
Annotorius website APIdocs content does not scroll correctly

### ISSUE THREAD

**Issue by portfolio-systems** [annotorious/annotorious#94]
https://recogito.github.io/annotorious/api-docs/annotorious/

Left hand list does not scroll on Mac OS Firefox/Safari

**Comment by rsimon** [comment]
Thx for reporting. The project website is, frankly, quite overdue for a revision in various respects. Definitely planning to do that... hopefully in the not too distant future ;-)

**Comment by portfolio-systems** [comment]
Well done and thanks for the update (:-)

I’ve ended up using markerjs2 in the meantime as it provides an svg marker more suited to my requirements (variable ‘pointer’ which can point in any direction/length etc)

Integrating into my Svelte project was harder than is should have been though … probably just me being thick.

Cheers

Ron

+++
