### ISSUE TITLE
Polygon selection doesn't stop in example file

### ISSUE THREAD

**Issue by adamwern** [annotorious/annotorious#96]
I can't get polygon selection to stop when trying the "Basic example" on my system. Tried clicking on the first point again (completing the loop), pressing enter/esc/space, but It just keep adding new points whatever I do. 

Changing to rectangle selection while in polygon selection mode doesn't cancel it either, it just makes possible to create two selections (polygon+rectangle) at the same time:
<img width="342" alt="Screenshot 2021-03-28 at 12 52 01" src="https://user-images.githubusercontent.com/7722099/112749939-d46a5600-8fc5-11eb-8612-761e1a4f2b29.png">

Rectangle annotations work fine.
Am I doing anything wrong, or is it a bug?

**System**: Annotorious 2.3.0, Chrome, macOs Catalina, trackpad

**Comment by rsimon** [comment]
Currently, double click closes the polygon. (Clicking on the first point as an alternative is planned.)

**Comment by rsimon** [comment]
Or touch + hold for ~1/2 sec of you're on a touch device.

**Comment by rsimon** [comment]
But: switching tools while a selection is still in progress is actually a situation I'm not currently handling... Will look into that, thanks!

**Comment by adamwern** [comment]
Nice, that that worked. Thank you!

I should then probably handle keydown events for **Esc** and **Enter** to cancel or finish polygon selections. And add some sort of tooltip explaining that double-click/hold finishes selections.

**Comment by rsimon** [comment]
Just fixed the issue that the old tool keeps drawing when switching to a new one: 4b3c4deadd62c56a318245273242198e4e76eca1.
