### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by mdelz** [annotorious/annotorious#97]
Hello, thank you for this tool. 

I just wanted to point out that the documentation has some outdated info like [applyTemplate](https://recogito.github.io/annotorious/api-docs/annotorious/#applytemplate)

**Comment by rsimon** [comment]
Thanks! Yes, absolutely. The website is in need of thorough revision (see also here #94). I'm still wrapping up a few things for the next milestone releases (Annotorious and Annotorious OpenSeadragon). That should be done in a few days, though, and then website and documentation will be the main priority.

**Comment by rsimon** [comment]
API docs are now up to date! (The 'Guides' section is still work in progress. But I can hopefully update it over the coming days.)
